"""Exact tropical semiring scalars and idempotent addition."""

from jacobian.math.polynomials.tropical._models import (
    PolynomialActiveTermsRequest,
    PolynomialActiveTermsResult,
    ScalarAddResult,
    ScalarDualResult,
    TropicalActiveTerm,
)
from jacobian.math.polynomials.tropical.hypersurface import (
    tropical_bivariate_hypersurface,
)
from jacobian.math.polynomials.tropical.operations import (
    tropical_assignment_profile,
    tropical_matrix_finite_power_sum,
    tropical_matrix_multiply,
    tropical_matrix_power,
    tropical_polynomial_active_terms,
    tropical_polynomial_add,
    tropical_polynomial_evaluate,
    tropical_polynomial_multiply,
    tropical_polynomial_power,
    tropical_polynomial_univariate_newton_polygon,
    tropical_polynomial_univariate_roots,
    tropical_scalar_add,
    tropical_scalar_dual,
    tropical_scalar_multiply,
    tropical_scalar_power,
    tropical_vector_add,
    tropical_vector_projectivize,
    tropical_vector_scale,
)
from jacobian.math.polynomials.tropical.regular_subdivision import (
    tropical_bivariate_regular_subdivision,
)
from jacobian.math.polynomials.tropical.values import (
    TropicalHypersurface,
    TropicalHypersurfaceCell,
    TropicalLiftedSubdivisionFace,
    TropicalMatrix,
    TropicalNewtonPolygonEdge,
    TropicalNewtonPolygonProfile,
    TropicalNewtonPolygonVertex,
    TropicalPolynomial,
    TropicalPolynomialTerm,
    TropicalRegularSubdivision,
    TropicalScalar,
    TropicalSemiring,
    TropicalSubdivisionFaceSupport,
    TropicalUnivariateRootProfile,
    TropicalVector,
    require_scalar_budget,
)

__all__ = [
    "PolynomialActiveTermsRequest",
    "PolynomialActiveTermsResult",
    "ScalarAddResult",
    "ScalarDualResult",
    "TropicalActiveTerm",
    "TropicalHypersurface",
    "TropicalHypersurfaceCell",
    "TropicalLiftedSubdivisionFace",
    "TropicalMatrix",
    "TropicalNewtonPolygonEdge",
    "TropicalNewtonPolygonProfile",
    "TropicalNewtonPolygonVertex",
    "TropicalPolynomial",
    "TropicalPolynomialTerm",
    "TropicalRegularSubdivision",
    "TropicalScalar",
    "TropicalSemiring",
    "TropicalSubdivisionFaceSupport",
    "TropicalUnivariateRootProfile",
    "TropicalVector",
    "require_scalar_budget",
    "tropical_assignment_profile",
    "tropical_bivariate_hypersurface",
    "tropical_bivariate_regular_subdivision",
    "tropical_matrix_finite_power_sum",
    "tropical_matrix_multiply",
    "tropical_matrix_power",
    "tropical_polynomial_active_terms",
    "tropical_polynomial_add",
    "tropical_polynomial_evaluate",
    "tropical_polynomial_multiply",
    "tropical_polynomial_power",
    "tropical_polynomial_univariate_newton_polygon",
    "tropical_polynomial_univariate_roots",
    "tropical_scalar_add",
    "tropical_scalar_dual",
    "tropical_scalar_multiply",
    "tropical_scalar_power",
    "tropical_vector_add",
    "tropical_vector_projectivize",
    "tropical_vector_scale",
]
