"""Exact discrete Morse theory on finite simplicial complexes."""

from jacobian.math.topology.discrete_morse._models import (
    CriticalCellBasis,
    CriticalCellProfile,
    DiscreteMorseMatchingResult,
    GradientPath,
    GradientPathCount,
    GradientPathsResult,
    GradientPathStep,
    IntegerMorseComplexResult,
    MatchingPair,
    MinimumMorseMatchingResult,
    MorseBoundaryEntry,
    MorseChainContractionRequest,
    MorseChainContractionResult,
    MorseComplexResult,
    MorseGradientStepKind,
    MorseMatchingFault,
    MorseMatchingOutcome,
)
from jacobian.math.topology.discrete_morse.extensions import (
    CollapseSequenceResult,
    collapse_sequence,
    greedy_collapse,
    greedy_matching,
)
from jacobian.math.topology.discrete_morse.operations import (
    compute_chain_contraction,
    compute_gradient_paths,
    compute_integer_morse_complex,
    compute_minimum_matching,
    compute_morse_complex,
    construct_matching,
)

__all__ = [
    "CollapseSequenceResult",
    "CriticalCellBasis",
    "CriticalCellProfile",
    "DiscreteMorseMatchingResult",
    "GradientPath",
    "GradientPathCount",
    "GradientPathStep",
    "GradientPathsResult",
    "IntegerMorseComplexResult",
    "MatchingPair",
    "MinimumMorseMatchingResult",
    "MorseBoundaryEntry",
    "MorseChainContractionRequest",
    "MorseChainContractionResult",
    "MorseComplexResult",
    "MorseGradientStepKind",
    "MorseMatchingFault",
    "MorseMatchingOutcome",
    "collapse_sequence",
    "compute_chain_contraction",
    "compute_gradient_paths",
    "compute_integer_morse_complex",
    "compute_minimum_matching",
    "compute_morse_complex",
    "construct_matching",
    "greedy_collapse",
    "greedy_matching",
]
