"""Galois theory operations."""

from jacobian.math.number_theory.galois.operations import (
    apply_automorphism,
    apply_automorphism_to_element,
    automorphisms,
    compose_automorphisms,
    element_embedding_orbit,
    frobenius_cycle,
    galois_correspondence,
    galois_factor,
    galois_fixed_field,
    galois_group,
    galois_subgroup,
    intermediate_field_stabilizer,
    inverse_automorphism,
    polynomial_discriminant,
    solvable,
    splitting_field,
    verify_galois_group,
    verify_solvable,
)

__all__ = [
    "apply_automorphism",
    "apply_automorphism_to_element",
    "automorphisms",
    "compose_automorphisms",
    "element_embedding_orbit",
    "frobenius_cycle",
    "galois_correspondence",
    "galois_factor",
    "galois_fixed_field",
    "galois_group",
    "galois_subgroup",
    "intermediate_field_stabilizer",
    "inverse_automorphism",
    "polynomial_discriminant",
    "solvable",
    "splitting_field",
    "verify_galois_group",
    "verify_solvable",
]
