"""Typed wire contracts for finite semigroup operations."""

from __future__ import annotations

from typing import Self

from pydantic import Field, model_validator

from jacobian._models import StrictModel

MAX_ELEMENTS = 50
MAX_LABEL_LENGTH = 64


class FiniteSemigroup(StrictModel):
    """A finite semigroup: a finite set with an associative binary operation."""

    elements: tuple[str, ...] = Field(min_length=1, max_length=MAX_ELEMENTS)
    multiplication: tuple[tuple[str, ...], ...]

    @model_validator(mode="after")
    def require_valid_semigroup(self) -> Self:
        labels = set(self.elements)
        if len(labels) != len(self.elements):
            raise ValueError("element labels must be distinct")
        if len(self.multiplication) != len(self.elements):
            raise ValueError("multiplication table must have one row per element")
        for row in self.multiplication:
            if len(row) != len(self.elements):
                raise ValueError("multiplication table must be square")
            for cell in row:
                if cell not in labels:
                    raise ValueError("every product must be a declared element")
        self._check_associativity(labels)
        return self

    def _check_associativity(self, labels: set[str]) -> None:
        idx = {label: i for i, label in enumerate(self.elements)}
        n = len(self.elements)
        for i in range(n):
            for j in range(n):
                for k in range(n):
                    ij = self.multiplication[i][j]
                    jk = self.multiplication[j][k]
                    left = self.multiplication[idx[ij]][k]
                    right = self.multiplication[i][idx[jk]]
                    if left != right:
                        raise ValueError(
                            f"semigroup must be associative: "
                            f"({self.elements[i]}*{self.elements[j]})*{self.elements[k]} "
                            f"!= {self.elements[i]}*({self.elements[j]}*{self.elements[k]})"
                        )


class PowerProfileRequest(StrictModel):
    """Request the power profile of one element in a finite semigroup."""

    semigroup: FiniteSemigroup
    element: str

    @model_validator(mode="after")
    def require_element_exists(self) -> Self:
        if self.element not in set(self.semigroup.elements):
            raise ValueError("element must be in the semigroup")
        return self


class PowerProfileResult(StrictModel):
    """The power profile of one element in a finite semigroup."""

    element: str
    powers: tuple[str, ...]
    index: int = Field(ge=0)
    period: int = Field(ge=1)
    idempotent: str
    cyclic_subsemigroup: tuple[str, ...]


class GeneratedSubsemigroupRequest(StrictModel):
    """Request the subsemigroup generated by a set of elements."""

    semigroup: FiniteSemigroup
    generators: tuple[str, ...] = Field(min_length=1)

    @model_validator(mode="after")
    def require_generators_exist(self) -> Self:
        labels = set(self.semigroup.elements)
        for gen in self.generators:
            if gen not in labels:
                raise ValueError("every generator must be in the semigroup")
        return self


class GeneratedSubsemigroupResult(StrictModel):
    """The subsemigroup generated by a set of elements."""

    generators: tuple[str, ...]
    elements: tuple[str, ...]
