"""Exact bounded finite semigroup operations."""

from jacobian.math.finite_semigroups._models import (
    GeneratedSubsemigroupRequest,
    GeneratedSubsemigroupResult,
    PowerProfileRequest,
    PowerProfileResult,
)


def compute_power_profile(request: PowerProfileRequest) -> PowerProfileResult:
    """Compute the power profile of one element in a finite semigroup."""

    elements = request.semigroup.elements
    mult = request.semigroup.multiplication
    idx = {label: i for i, label in enumerate(elements)}

    a = request.element
    powers: list[str] = [a]
    seen: dict[str, int] = {a: 0}

    current = a
    while True:
        # Compute next power: mult[current][a]
        next_power = mult[idx[current]][idx[a]]
        if next_power in seen:
            # Found repeat
            index = seen[next_power]
            period = len(powers) - index
            break
        seen[next_power] = len(powers)
        powers.append(next_power)
        current = next_power

    # Find idempotent: the identity of the cyclic group in the eventual cycle
    # The cycle is powers[index:index+period]
    # The idempotent is a^(k*period) where k is such that k*period >= index
    # and k*period is 0 mod the cycle length
    # Actually: e = a^(m * ceil(index/period) * period) but simpler:
    # The idempotent in the cycle is powers[index + ((period - (index % period)) % period)]
    # or equivalently: powers[index + ((-index) % period)]
    # But we need the idempotent power, which is the power that equals itself when multiplied by itself
    # In a finite cyclic semigroup with index m and period p, the idempotent is a^(m + ((p - (m % p)) % p))
    # Actually: the idempotent is a^(k) where k >= m and k % p == 0, so k = m + ((p - m % p) % p)
    m = index
    p = period
    k = m + ((p - m % p) % p)
    idempotent = (
        powers[k] if k < len(powers) else powers[index + ((k - index) % period)]
    )

    # Cyclic subsemigroup = {a, a^2, ..., a^(m+p-1)}
    cyclic_subsemigroup = tuple(powers[: m + p])

    return PowerProfileResult(
        element=a,
        powers=tuple(powers),
        index=index,
        period=period,
        idempotent=idempotent,
        cyclic_subsemigroup=cyclic_subsemigroup,
    )


def compute_generated_subsemigroup(
    request: GeneratedSubsemigroupRequest,
) -> GeneratedSubsemigroupResult:
    """Compute the subsemigroup generated by a set of elements."""

    elements = request.semigroup.elements
    mult = request.semigroup.multiplication
    idx = {label: i for i, label in enumerate(elements)}

    generated = set(request.generators)
    changed = True
    while changed:
        changed = False
        current = list(generated)
        for a in current:
            for b in current:
                product = mult[idx[a]][idx[b]]
                if product not in generated:
                    generated.add(product)
                    changed = True

    # Sort by original element ordering
    result_elements = tuple(e for e in elements if e in generated)
    return GeneratedSubsemigroupResult(
        generators=request.generators,
        elements=result_elements,
    )
