"""Finite semigroup operation declarations."""

from typing import Any

from jacobian.catalog.models import MathTool, OperationExample
from jacobian.math.finite_semigroups._models import (
    ElementPowerRequest,
    ElementPowerResult,
    GeneratedSubsemigroupRequest,
    GeneratedSubsemigroupResult,
    GreenRelationsRequest,
    GreenRelationsResult,
    IdempotentsRequest,
    IdempotentsResult,
    PowerProfileRequest,
    PowerProfileResult,
    PrincipalIdealsRequest,
    PrincipalIdealsResult,
)
from jacobian.math.finite_semigroups.operations import (
    element_power,
    generated_subsemigroup,
    green_relations,
    idempotents,
    power_profile,
    principal_ideals,
)


def _run_power_profile(request: PowerProfileRequest) -> PowerProfileResult:
    return power_profile(request.semigroup, request.element)


def _run_generated_subsemigroup(
    request: GeneratedSubsemigroupRequest,
) -> GeneratedSubsemigroupResult:
    return generated_subsemigroup(request.semigroup, request.generators)


def _run_element_power(request: ElementPowerRequest) -> ElementPowerResult:
    return element_power(request.semigroup, request.element, request.exponent)


def _run_idempotents(request: IdempotentsRequest) -> IdempotentsResult:
    return idempotents(request.semigroup)


def _run_principal_ideals(request: PrincipalIdealsRequest) -> PrincipalIdealsResult:
    return principal_ideals(request.semigroup, request.elements)


def _run_green_relations(request: GreenRelationsRequest) -> GreenRelationsResult:
    return green_relations(request.semigroup)


# The cyclic group Z/3Z as a semigroup (which is also a group)
# Elements: 0, 1, 2 with addition mod 3
_SEMIGROUP = {
    "elements": ["0", "1", "2"],
    "multiplication": [
        ["0", "1", "2"],
        ["1", "2", "0"],
        ["2", "0", "1"],
    ],
}


TOOLS: tuple[MathTool[Any, Any], ...] = (
    MathTool(
        operation_id="semigroup.element.power_profile.compute",
        title="Compute the power profile of a semigroup element",
        description="Compute the sequence a, a^2, a^3, ... until the first repeat, "
        "determining the one-based index, period, idempotent limit, and "
        "complete cyclic subsemigroup of one element in a finite semigroup.",
        request_type=PowerProfileRequest,
        result_type=PowerProfileResult,
        run=_run_power_profile,
        tags=("algebra", "semigroup", "exact"),
        examples=(
            OperationExample(
                name="cyclic_group_z3",
                description="Compute the power profile of element 1 in Z/3Z; "
                "the semigroup must be associative.",
                input={
                    "semigroup": _SEMIGROUP,
                    "element": "1",
                },
            ),
        ),
    ),
    MathTool(
        operation_id="semigroup.generated_subsemigroup.compute",
        title="Compute the subsemigroup generated by a set of elements",
        description="Compute the closure of a set of generators under the semigroup "
        "multiplication, returning all elements in the generated "
        "subsemigroup.",
        request_type=GeneratedSubsemigroupRequest,
        result_type=GeneratedSubsemigroupResult,
        run=_run_generated_subsemigroup,
        tags=("algebra", "semigroup", "exact"),
        examples=(
            OperationExample(
                name="generate_from_1_in_z3",
                description="Compute the subsemigroup generated by {1} in Z/3Z; "
                "generators must be in the semigroup.",
                input={
                    "semigroup": _SEMIGROUP,
                    "generators": ["1"],
                },
            ),
        ),
    ),
    MathTool(
        operation_id="semigroup.element.power.compute",
        title="Compute the power of a semigroup element",
        description="Compute the exact iterated product element^exponent for a positive "
        "exponent in a finite semigroup using its finite eventual period.",
        request_type=ElementPowerRequest,
        result_type=ElementPowerResult,
        run=_run_element_power,
        tags=("algebra", "semigroup", "exact"),
        examples=(
            OperationExample(
                name="power_2_in_cyclic_group",
                description="Compute 1^2 in Z/3Z.",
                input={
                    "semigroup": _SEMIGROUP,
                    "element": "1",
                    "exponent": 2,
                },
            ),
        ),
    ),
    MathTool(
        operation_id="semigroup.idempotents.compute",
        title="Find the idempotent elements of a finite semigroup",
        description="Return every element e with e*e = e in a finite semigroup.",
        request_type=IdempotentsRequest,
        result_type=IdempotentsResult,
        run=_run_idempotents,
        tags=("algebra", "semigroup", "exact"),
        examples=(
            OperationExample(
                name="idempotents_of_z3",
                description="Find the idempotents of Z/3Z; only the zero element is idempotent.",
                input={
                    "semigroup": _SEMIGROUP,
                },
            ),
        ),
    ),
    MathTool(
        operation_id="semigroup.principal_ideals.compute",
        title="Compute principal ideals in a finite semigroup",
        description="For each requested element compute its principal two-sided ideal S^1 a S^1.",
        request_type=PrincipalIdealsRequest,
        result_type=PrincipalIdealsResult,
        run=_run_principal_ideals,
        tags=("algebra", "semigroup", "exact"),
        examples=(
            OperationExample(
                name="ideal_in_z3",
                description="Compute the principal ideal of 1 in Z/3Z.",
                input={
                    "semigroup": _SEMIGROUP,
                    "elements": ["1"],
                },
            ),
        ),
    ),
    MathTool(
        operation_id="semigroup.green_relations.compute",
        title="Compute Green relations of a finite semigroup",
        description="Compute the Green relations L, R, H, D, and J of a finite semigroup. "
        "L relates elements with the same principal left ideal, R with the "
        "same principal right ideal, H = L ∩ R, D = L ∨ R (join), and J is "  # noqa: RUF001
        "the two-sided Green relation defined by principal two-sided ideals.",
        request_type=GreenRelationsRequest,
        result_type=GreenRelationsResult,
        run=_run_green_relations,
        tags=("algebra", "semigroup", "exact"),
        examples=(
            OperationExample(
                name="green_relations_z3",
                description="Compute the Green relations of Z/3Z.",
                input={
                    "semigroup": _SEMIGROUP,
                },
            ),
        ),
    ),
)

__all__ = ["TOOLS"]
