"""Supported exact values and operations for bounded modular-form spaces."""

from jacobian.math.number_theory.modular_forms._models import ModularFormEqualityResult
from jacobian.math.number_theory.modular_forms.basis import (
    modular_form_basis_frame,
    modular_form_basis_q_expansions,
    modular_form_coordinates_atkin_lehner,
    modular_form_coordinates_equal,
    modular_form_coordinates_from_frame,
    modular_form_coordinates_hecke,
    modular_form_coordinates_product,
    modular_form_coordinates_q_expansion,
    modular_form_coordinates_to_frame,
    modular_form_coordinates_transport,
    modular_form_coordinates_u2,
    modular_form_coordinates_v2,
    modular_form_coordinates_v3,
    modular_form_coordinates_v_degeneracy,
    modular_form_hecke_matrix,
    modular_form_hecke_matrix_in_frame,
    modular_form_operator_image,
    modular_form_operator_image_q_expansion,
    modular_form_space_inclusion,
)
from jacobian.math.number_theory.modular_forms.character_basis import (
    modular_character_basis_q_expansions,
    modular_character_coordinates_hecke,
    modular_character_coordinates_product,
    modular_character_coordinates_q_expansion,
    modular_character_hecke_matrix,
)
from jacobian.math.number_theory.modular_forms.character_basis_models import (
    ModularCharacterBasis,
    ModularCharacterBasisElement,
    ModularCharacterBasisRequest,
    ModularCharacterCoordinatesProductRequest,
    ModularCharacterCoordinatesRequest,
    ModularCharacterHeckeMatrix,
    ModularCharacterHeckeMatrixRequest,
    ModularCharacterHeckeRequest,
    ModularCharacterQExpansion,
)
from jacobian.math.number_theory.modular_forms.character_degeneracy import (
    modular_character_coordinates_v_degeneracy,
)
from jacobian.math.number_theory.modular_forms.character_degeneracy_models import (
    ModularCharacterVDegeneracyRequest,
)
from jacobian.math.number_theory.modular_forms.field_coordinates import (
    modular_form_coordinates_extend_field,
    modular_form_field_coordinates_q_expansion,
)
from jacobian.math.number_theory.modular_forms.operations import (
    level_one_named_q_expansion,
    modular_form_character_space_inclusion,
    named_q_expansion,
    space_dimension,
    sturm_bound,
)
from jacobian.math.number_theory.modular_forms.transforms import (
    formal_q_series_u_operator,
    formal_q_series_v_operator,
)
from jacobian.math.number_theory.modular_forms.values import (
    LevelOneModularQExpansion,
    ModularCharacterSpaceInclusion,
    ModularFormBasis,
    ModularFormChangeOfBasisFrame,
    ModularFormCoordinates,
    ModularFormFieldQExpansion,
    ModularFormFramedCoordinates,
    ModularFormFramedHeckeMatrix,
    ModularFormHeckeMatrix,
    ModularFormOperatorImage,
    ModularFormOperatorImagePrefix,
    ModularFormSpace,
    ModularFormSpaceInclusion,
    ModularQExpansion,
)

__all__ = [
    "LevelOneModularQExpansion",
    "ModularCharacterBasis",
    "ModularCharacterBasisElement",
    "ModularCharacterBasisRequest",
    "ModularCharacterCoordinatesProductRequest",
    "ModularCharacterCoordinatesRequest",
    "ModularCharacterHeckeMatrix",
    "ModularCharacterHeckeMatrixRequest",
    "ModularCharacterHeckeRequest",
    "ModularCharacterQExpansion",
    "ModularCharacterSpaceInclusion",
    "ModularCharacterVDegeneracyRequest",
    "ModularFormBasis",
    "ModularFormChangeOfBasisFrame",
    "ModularFormCoordinates",
    "ModularFormEqualityResult",
    "ModularFormFieldQExpansion",
    "ModularFormFramedCoordinates",
    "ModularFormFramedHeckeMatrix",
    "ModularFormHeckeMatrix",
    "ModularFormOperatorImage",
    "ModularFormOperatorImagePrefix",
    "ModularFormSpace",
    "ModularFormSpaceInclusion",
    "ModularQExpansion",
    "formal_q_series_u_operator",
    "formal_q_series_v_operator",
    "level_one_named_q_expansion",
    "modular_character_basis_q_expansions",
    "modular_character_coordinates_hecke",
    "modular_character_coordinates_product",
    "modular_character_coordinates_q_expansion",
    "modular_character_coordinates_v_degeneracy",
    "modular_character_hecke_matrix",
    "modular_form_basis_frame",
    "modular_form_basis_q_expansions",
    "modular_form_character_space_inclusion",
    "modular_form_coordinates_atkin_lehner",
    "modular_form_coordinates_equal",
    "modular_form_coordinates_extend_field",
    "modular_form_coordinates_from_frame",
    "modular_form_coordinates_hecke",
    "modular_form_coordinates_product",
    "modular_form_coordinates_q_expansion",
    "modular_form_coordinates_to_frame",
    "modular_form_coordinates_transport",
    "modular_form_coordinates_u2",
    "modular_form_coordinates_v2",
    "modular_form_coordinates_v3",
    "modular_form_coordinates_v_degeneracy",
    "modular_form_field_coordinates_q_expansion",
    "modular_form_hecke_matrix",
    "modular_form_hecke_matrix_in_frame",
    "modular_form_operator_image",
    "modular_form_operator_image_q_expansion",
    "modular_form_space_inclusion",
    "named_q_expansion",
    "space_dimension",
    "sturm_bound",
]
