"""Exact canonical-form kernels and typed contracts over QQ."""

from jacobian.math.matrices.canonical_forms._models import (
    CentralizerResult,
    InvariantFactorEntry,
    InvariantFactorProfileResult,
    MatrixPolynomialEvaluationResult,
    MatrixPolynomialRemainderResult,
    MinimalPolynomialResult,
    MonicPolynomial,
    PrimaryDecompositionResult,
    RationalCanonicalFormResult,
    SimilarityResult,
)
from jacobian.math.matrices.canonical_forms.operations import (
    centralizer_basis,
    characteristic_polynomial,
    decide_similarity,
    evaluate_matrix_polynomial_value,
    invariant_factor_profile,
    invariant_factors,
    minimal_polynomial,
    primary_decomposition,
    reduce_matrix_polynomial,
    verify_minimal_polynomial,
    verify_primary_decomposition,
    verify_rational_canonical_form,
)

__all__ = [
    "CentralizerResult",
    "InvariantFactorEntry",
    "InvariantFactorProfileResult",
    "MatrixPolynomialEvaluationResult",
    "MatrixPolynomialRemainderResult",
    "MinimalPolynomialResult",
    "MonicPolynomial",
    "PrimaryDecompositionResult",
    "RationalCanonicalFormResult",
    "SimilarityResult",
    "centralizer_basis",
    "characteristic_polynomial",
    "decide_similarity",
    "evaluate_matrix_polynomial_value",
    "invariant_factor_profile",
    "invariant_factors",
    "minimal_polynomial",
    "primary_decomposition",
    "reduce_matrix_polynomial",
    "verify_minimal_polynomial",
    "verify_primary_decomposition",
    "verify_rational_canonical_form",
]
