"""Domain functions for finite semigroup operations."""

from __future__ import annotations

from jacobian.math.finite_semigroups_ops._models import (
    ElementPowerRequest,
    ElementPowerResult,
    GeneratedSubsemigroupRequest,
    GeneratedSubsemigroupResult,
    IdempotentsRequest,
    IdempotentsResult,
    PrincipalIdealsRequest,
    PrincipalIdealsResult,
)


def _multiply(table: tuple[tuple[int, ...], ...], a: int, b: int) -> int:
    return table[a][b]


def compute_element_power(request: ElementPowerRequest) -> ElementPowerResult:
    """Compute element^exponent using iterated multiplication."""
    if request.exponent == 0:
        raise ValueError("exponent 0 requires an identity element")
    result = request.element
    table = request.multiplication_table
    for _ in range(request.exponent - 1):
        result = _multiply(table, result, request.element)
    return ElementPowerResult(result=result)


def compute_idempotents(request: IdempotentsRequest) -> IdempotentsResult:
    """Find all idempotent elements e such that e*e = e."""
    table = request.multiplication_table
    idempotents = tuple(i for i in range(len(table)) if table[i][i] == i)
    return IdempotentsResult(idempotents=idempotents)


def compute_generated_subsemigroup(
    request: GeneratedSubsemigroupRequest,
) -> GeneratedSubsemigroupResult:
    """Compute the subsemigroup generated by the given generators."""
    table = request.multiplication_table
    elements = set(request.generators)
    queue = list(request.generators)
    while queue:
        current = queue.pop(0)
        for other in list(elements):
            product = table[current][other]
            if product not in elements:
                elements.add(product)
                queue.append(product)
            product2 = table[other][current]
            if product2 not in elements:
                elements.add(product2)
                queue.append(product2)
    result = tuple(sorted(elements))
    return GeneratedSubsemigroupResult(elements=result, size=len(result))


def compute_principal_ideals(
    request: PrincipalIdealsRequest,
) -> PrincipalIdealsResult:
    """Compute principal ideals (left and right) for each element.

    The principal ideal of element a is {a} union {x*a : x in S} union {a*x : x in S}.
    """
    table = request.multiplication_table
    n = len(table)
    ideals = []
    for elem in request.elements:
        ideal = {elem}
        for x in range(n):
            ideal.add(table[x][elem])
            ideal.add(table[elem][x])
        ideals.append(tuple(sorted(ideal)))
    return PrincipalIdealsResult(ideals=tuple(ideals))
