"""Finite semigroup operation declarations."""

from collections.abc import Callable
from typing import Any

from jacobian._models import StrictModel
from jacobian.catalog._examples import example
from jacobian.catalog.models import MathTool, OperationExample
from jacobian.math.finite_semigroups_ops._models import (
    ElementPowerRequest,
    ElementPowerResult,
    GeneratedSubsemigroupRequest,
    GeneratedSubsemigroupResult,
    IdempotentsRequest,
    IdempotentsResult,
    PrincipalIdealsRequest,
    PrincipalIdealsResult,
)
from jacobian.math.finite_semigroups_ops._operations import (
    compute_element_power,
    compute_generated_subsemigroup,
    compute_idempotents,
    compute_principal_ideals,
)


def _op[RequestT: StrictModel, ResultT: StrictModel](
    operation_id: str,
    title: str,
    description: str,
    request_model: type[RequestT],
    result_model: type[ResultT],
    operation: Callable[[RequestT], ResultT],
    *tags: str,
    examples: tuple[OperationExample, ...] = (),
    version: str = "1",
) -> MathTool[RequestT, ResultT]:
    return MathTool(
        operation_id=operation_id,
        version=version,
        title=title,
        description=description,
        request_type=request_model,
        result_type=result_model,
        run=operation,
        tags=tags,
        examples=examples,
    )


TOOLS: tuple[MathTool[Any, Any], ...] = (
    _op(
        "semigroup.element.power.compute",
        "Compute element^exponent in a finite semigroup",
        "Compute the power of an element using iterated multiplication in "
        "the semigroup's multiplication table.",
        ElementPowerRequest,
        ElementPowerResult,
        compute_element_power,
        "semigroup",
        "power",
        "exact",
        examples=(
            example(
                "power_2_in_cyclic_group",
                "Compute element 1^2 in the cyclic group Z/3.",
                {
                    "multiplication_table": [[0, 1, 2], [1, 2, 0], [2, 0, 1]],
                    "element": 1,
                    "exponent": 2,
                },
            ),
        ),
    ),
    _op(
        "semigroup.idempotents.compute",
        "Find all idempotent elements in a finite semigroup",
        "Find all elements e such that e*e = e in the given semigroup.",
        IdempotentsRequest,
        IdempotentsResult,
        compute_idempotents,
        "semigroup",
        "idempotents",
        "exact",
        examples=(
            example(
                "idempotents_of_band",
                "Find idempotents in a 2-element semilattice {0, 1}.",
                {
                    "multiplication_table": [[0, 0], [0, 1]],
                },
            ),
        ),
    ),
    _op(
        "semigroup.generated_subsemigroup.compute",
        "Compute the subsemigroup generated by a set of elements",
        "Compute the closure of the given generators under the semigroup "
        "multiplication, returning all elements in the generated subsemigroup.",
        GeneratedSubsemigroupRequest,
        GeneratedSubsemigroupResult,
        compute_generated_subsemigroup,
        "semigroup",
        "generated-subsemigroup",
        "exact",
        examples=(
            example(
                "generated_by_1_in_z3",
                "Subsemigroup generated by 1 in Z/3.",
                {
                    "multiplication_table": [[0, 1, 2], [1, 2, 0], [2, 0, 1]],
                    "generators": [1],
                },
            ),
        ),
    ),
    _op(
        "semigroup.principal_ideals.compute",
        "Compute principal ideals of elements in a finite semigroup",
        "For each input element, compute its principal ideal "
        "{a} union {x*a, a*x : x in S}.",
        PrincipalIdealsRequest,
        PrincipalIdealsResult,
        compute_principal_ideals,
        "semigroup",
        "principal-ideals",
        "exact",
        examples=(
            example(
                "ideal_in_z3",
                "Principal ideal of 1 in Z/3.",
                {
                    "multiplication_table": [[0, 1, 2], [1, 2, 0], [2, 0, 1]],
                    "elements": [1],
                },
            ),
        ),
    ),
)

__all__ = ["TOOLS"]
