"""Provider-independent exact combinatorics values and functions."""

from jacobian.math.combinatorics.exact_cover import (
    ExactCoverItemMultiplicity,
    ExactCoverRow,
    ExactCoverSearchStatus,
    GeneralizedExactCoverInstance,
    GeneralizedExactCoverResult,
    find_generalized_exact_cover,
)
from jacobian.math.combinatorics.operations import (
    bell_number,
    bernoulli_number,
    binomial,
    catalan_number,
    central_binomial,
    compositions,
    derangement_number,
    double_factorial,
    evaluate_linear_recurrence,
    evaluate_polynomial_coefficient_recurrence,
    factorial,
    fibonacci_number,
    integer_partitions,
    lucas_number,
    motzkin_number,
    multinomial,
    partition_number,
    permutations,
    progression_hypergraph,
    rational_generating_function_coefficients,
    stirling_first,
    stirling_second,
)
from jacobian.math.combinatorics.recurrence_tables import (
    IndexedRecurrenceResidual,
    PolynomialCoefficientRecurrenceTableResult,
    recurrence_table_residuals,
)

__all__ = [
    "ExactCoverItemMultiplicity",
    "ExactCoverRow",
    "ExactCoverSearchStatus",
    "GeneralizedExactCoverInstance",
    "GeneralizedExactCoverResult",
    "IndexedRecurrenceResidual",
    "PolynomialCoefficientRecurrenceTableResult",
    "bell_number",
    "bernoulli_number",
    "binomial",
    "catalan_number",
    "central_binomial",
    "compositions",
    "derangement_number",
    "double_factorial",
    "evaluate_linear_recurrence",
    "evaluate_polynomial_coefficient_recurrence",
    "factorial",
    "fibonacci_number",
    "find_generalized_exact_cover",
    "integer_partitions",
    "lucas_number",
    "motzkin_number",
    "multinomial",
    "partition_number",
    "permutations",
    "progression_hypergraph",
    "rational_generating_function_coefficients",
    "recurrence_table_residuals",
    "stirling_first",
    "stirling_second",
]
