"""Exact bounded finite group-action operations."""

from __future__ import annotations

from math import comb

from pydantic import ValidationError

from jacobian.catalog.models import OperationDomainValidationError
from jacobian.math.groups.actions._models import (
    MAX_COLORS,
    MAX_FAMILY_MEMBERS,
    MAX_GROUP_ORDER,
    MAX_ORBIT_PROFILE_IMAGES,
    MAX_ORBIT_PROFILE_INCIDENCES,
    MAX_ORBIT_PROFILE_TRANSPORTERS,
    MAX_POLYA_WORK,
    MAX_TERMS,
    ActionBoundSubset,
    BurnsideCountResult,
    CycleIndexResult,
    ElementCyclesResult,
    FinitePermutationAction,
    PolyaInventoryResult,
    SubsetCanonicalizationResult,
    SubsetFamilyOrbitProfileResult,
    SubsetFamilyOrbitProfileRow,
)

CycleTypeCount = tuple[tuple[int, ...], int]


def _compose(a: tuple[int, ...], b: tuple[int, ...]) -> tuple[int, ...]:
    """Return ``a ∘ b`` so that ``(a ∘ b)[i] = a[b[i]]`` (left action)."""
    return tuple(a[b[i]] for i in range(len(a)))


def _identity(n: int) -> tuple[int, ...]:
    return tuple(range(n))


def _enumerate_group(
    action: FinitePermutationAction,
) -> tuple[tuple[int, ...], ...]:
    """Enumerate the group generated by the action's generators under composition.

    The identity element is always at index 0.  The remaining elements are
    ordered by first discovery in a breadth-first closure.  The group order
    must not exceed the bounded maximum.
    """

    n = len(action.domain)
    identity = _identity(n)
    seen: dict[tuple[int, ...], int] = {identity: 0}
    elements: list[tuple[int, ...]] = [identity]
    frontier: list[tuple[int, ...]] = [identity]
    while frontier:
        new_frontier: list[tuple[int, ...]] = []
        for elem in frontier:
            for gen in action.generators:
                composed = _compose(gen, elem)
                if composed not in seen:
                    seen[composed] = len(elements)
                    elements.append(composed)
                    new_frontier.append(composed)
                    if len(elements) > MAX_GROUP_ORDER:
                        raise OperationDomainValidationError(
                            location=("action",),
                            code="finite_group_action.group_order_exceeds_bound",
                            message=(
                                "group order exceeds the bounded maximum "
                                f"{MAX_GROUP_ORDER}"
                            ),
                        )
        frontier = new_frontier
    return tuple(elements)


def _transport_subset(
    permutation: tuple[int, ...],
    subset: tuple[int, ...],
) -> tuple[int, ...]:
    return tuple(sorted(permutation[position] for position in subset))


def _subset_canonicalization_data(
    action: FinitePermutationAction,
    source_subset: tuple[int, ...],
) -> tuple[tuple[int, ...], tuple[int, ...], int, int]:
    """Return canonical image, transporter, orbit size, and stabilizer size."""
    group = _enumerate_group(action)
    image_transporters: dict[tuple[int, ...], tuple[int, ...]] = {}
    stabilizer_size = 0
    for permutation in group:
        image = _transport_subset(permutation, source_subset)
        previous = image_transporters.get(image)
        if previous is None or permutation < previous:
            image_transporters[image] = permutation
        if image == source_subset:
            stabilizer_size += 1

    canonical_subset = min(image_transporters)
    transporter = image_transporters[canonical_subset]
    orbit_size = len(image_transporters)
    if orbit_size * stabilizer_size != len(group):
        raise ValueError("subset orbit and stabilizer sizes violate orbit-stabilizer")
    return canonical_subset, transporter, orbit_size, stabilizer_size


def _cycle_decomposition(
    perm: tuple[int, ...],
) -> tuple[
    tuple[tuple[int, ...], ...], tuple[int, ...], tuple[int, ...], tuple[int, ...]
]:
    """Return ``(cycles, lengths, cycle_type, fixed)`` for one permutation.

    Cycles use the canonical representative starting with the smallest index
    and are ordered by their smallest element.  Fixed points are cycles of
    length 1.  ``cycle_type`` is the integer partition of ``n`` given by cycle
    lengths in non-increasing order.  ``fixed`` lists fixed-point indices in
    increasing order.
    """
    n = len(perm)
    visited = [False] * n
    cycles: list[tuple[int, ...]] = []
    for start in range(n):
        if visited[start]:
            continue
        cycle: list[int] = []
        current = start
        while not visited[current]:
            visited[current] = True
            cycle.append(current)
            current = perm[current]
        cycles.append(tuple(cycle))
    # Canonical: order cycles by smallest element, rotate each to start there.
    cycles.sort(key=lambda c: min(c))
    lengths = tuple(sorted((len(c) for c in cycles), reverse=True))
    fixed = tuple(i for i in range(n) if perm[i] == i)
    return tuple(cycles), lengths, lengths, fixed


def _canonical_family_subset(
    action: FinitePermutationAction, subset: tuple[int, ...]
) -> tuple[int, ...]:
    """Canonicalize one family row or fail with the owner-local typed error."""

    try:
        return ActionBoundSubset(action=action, positions=subset).positions
    except ValidationError as error:
        detail = error.errors()[0]
        raise OperationDomainValidationError(
            location=("subsets", *tuple(detail.get("loc", ()))),
            code=detail["type"],
            message=detail["msg"],
        ) from error


def _support(perm: tuple[int, ...]) -> tuple[int, ...]:
    return tuple(i for i in range(len(perm)) if perm[i] != i)


def _element_cycles_data(
    action: FinitePermutationAction,
    element: int,
) -> tuple[
    tuple[int, ...],
    tuple[tuple[int, ...], ...],
    tuple[int, ...],
    tuple[int, ...],
    tuple[int, ...],
    tuple[int, ...],
]:
    group = _enumerate_group(action)
    if element < 0 or element >= len(group):
        raise OperationDomainValidationError(
            location=("element",),
            code="finite_group_action.element_out_of_range",
            message="element index is out of range for the group order",
        )
    perm = group[element]
    cycles, lengths, cycle_type, fixed = _cycle_decomposition(perm)
    support = _support(perm)
    return perm, cycles, lengths, cycle_type, fixed, support


def _permutation_cycle_type(permutation: tuple[int, ...]) -> tuple[int, ...]:
    """Return only a permutation's cycle type for aggregate claim checking."""
    visited = [False] * len(permutation)
    lengths: list[int] = []
    for start in range(len(permutation)):
        if visited[start]:
            continue
        current = start
        length = 0
        while not visited[current]:
            visited[current] = True
            current = permutation[current]
            length += 1
        lengths.append(length)
    return tuple(sorted(lengths, reverse=True))


def _cycle_type_counts(
    group: tuple[tuple[int, ...], ...],
) -> tuple[CycleTypeCount, ...]:
    """Return the cycle-type multiplicity table as a sorted tuple of (type, count)."""
    counts: dict[tuple[int, ...], int] = {}
    for perm in group:
        _, _, cycle_type, _ = _cycle_decomposition(perm)
        counts[cycle_type] = counts.get(cycle_type, 0) + 1
    return tuple(sorted(counts.items()))


def _cycle_index_data(
    action: FinitePermutationAction,
) -> tuple[int, int, tuple[CycleTypeCount, ...]]:
    """Return ``(group_order, degree, cycle_type_counts)``."""
    group = _enumerate_group(action)
    degree = len(action.domain)
    counts = _cycle_type_counts(group)
    return len(group), degree, counts


def _burnside_data(
    action: FinitePermutationAction,
) -> tuple[int, tuple[int, ...], int]:
    """Return ``(group_order, fixed_point_contributions, orbit_count)``."""
    group = _enumerate_group(action)
    contributions: list[int] = []
    for perm in group:
        _, _, _, fixed = _cycle_decomposition(perm)
        contributions.append(len(fixed))
    group_order = len(group)
    total = sum(contributions)
    if total % group_order != 0:
        raise ValueError("Burnside orbit count is not an integer")
    orbit_count = total // group_order
    return group_order, tuple(contributions), orbit_count


def _polya_terms_from_group(
    group: tuple[tuple[int, ...], ...], colors: int
) -> tuple[tuple[tuple[int, ...], int], ...]:
    """Expand the cycle-index substitution for an already admitted group."""
    if type(colors) is not int or not 1 <= colors <= MAX_COLORS:
        raise OperationDomainValidationError(
            location=("colors",),
            code="finite_group_action.colors_out_of_range",
            message=(
                "colors must be an integer between 1 and "
                f"{MAX_COLORS}"
            ),
        )
    # The state space after k cycle factors is bounded by the number of
    # colour-count vectors of length k.  Charge this upper bound once before
    # expanding so the dynamic program cannot start an admitted request whose
    # transition budget is already too large.
    estimated_work = 0
    for permutation in group:
        cycle_count = len(_permutation_cycle_type(permutation))
        for prefix_length in range(cycle_count):
            estimated_work += colors * min(
                MAX_TERMS, comb(prefix_length + colors - 1, colors - 1)
            )
            if estimated_work > MAX_POLYA_WORK:
                raise OperationDomainValidationError(
                    location=("colors",),
                    code="finite_group_action.polya_work_exceeded",
                    message=(
                        "Pólya inventory dynamic-programming work exceeds the "
                        f"bounded maximum of {MAX_POLYA_WORK} transitions"
                    ),
                )

    orbit_count: dict[tuple[int, ...], int] = {}
    for perm in group:
        cycle_lengths = _permutation_cycle_type(perm)
        states: dict[tuple[int, ...], int] = {(0,) * colors: 1}
        for length in cycle_lengths:
            next_states: dict[tuple[int, ...], int] = {}
            for monomial, coefficient in states.items():
                for color in range(colors):
                    updated = list(monomial)
                    updated[color] += length
                    updated_monomial = tuple(updated)
                    next_states[updated_monomial] = (
                        next_states.get(updated_monomial, 0) + coefficient
                    )
            if len(next_states) > MAX_TERMS:
                raise OperationDomainValidationError(
                    location=("colors",),
                    code="finite_group_action.polya_terms_exceeded",
                    message=(
                        "Pólya inventory has more than the bounded maximum "
                        f"of {MAX_TERMS} sparse terms"
                    ),
                )
            states = next_states
        for monomial, coefficient in states.items():
            orbit_count[monomial] = orbit_count.get(monomial, 0) + coefficient
        if len(orbit_count) > MAX_TERMS:
            raise OperationDomainValidationError(
                location=("colors",),
                code="finite_group_action.polya_terms_exceeded",
                message=(
                    "Pólya inventory has more than the bounded maximum "
                    f"of {MAX_TERMS} sparse terms"
                ),
            )
    group_order = len(group)
    terms: list[tuple[tuple[int, ...], int]] = []
    for monomial, count in orbit_count.items():
        if count % group_order != 0:
            raise ValueError("Pólya inventory coefficient is not an integer")
        terms.append((monomial, count // group_order))
    terms.sort(key=lambda t: t[0])
    return tuple(terms)


def _polya_inventory_data(
    action: FinitePermutationAction,
    colors: int,
) -> tuple[int, tuple[tuple[tuple[int, ...], int], ...]]:
    """Return ``(degree, terms)`` for the Pólya inventory polynomial.

    For a colouring ``X -> {1..k}``, each group element ``g`` contributes
    ``prod_i a_i^{c_i(g)}`` to the cycle index.  Substituting
    ``a_i <- sum_c y_c^i`` and expanding gives the inventory polynomial whose
    monomials are exponent tuples of length ``colors`` and coefficients count
    colouring orbits by colour multiplicity.
    """
    group = _enumerate_group(action)
    return len(action.domain), _polya_terms_from_group(group, colors)


def subset_family_orbit_profile(
    action: FinitePermutationAction, subsets: tuple[tuple[int, ...], ...]
) -> SubsetFamilyOrbitProfileResult:
    """Partition a materialized family by ambient permutation-action orbits.

    The kernel expands the generated group once. It materializes only the
    distinct ambient orbits represented by the supplied family, then binds every
    source index to its orbit class. Admission charges source incidences,
    generated images, representative transporters, and retained output rather
    than the unrelated carrier size alone.
    """

    if len(subsets) > MAX_FAMILY_MEMBERS:
        raise OperationDomainValidationError(
            location=("subsets",),
            code="finite_group_action.subset_family_size_exceeded",
            message=f"at most {MAX_FAMILY_MEMBERS} subsets are admitted",
        )
    source_positions = tuple(
        _canonical_family_subset(action, subset) for subset in subsets
    )
    if len(set(source_positions)) != len(source_positions):
        raise OperationDomainValidationError(
            location=("subsets",),
            code="finite_group_action.subset_family_duplicates",
            message="supplied subsets must be pairwise distinct",
        )
    group = _enumerate_group(action)
    group_order = len(group)

    source_index = {
        positions: index for index, positions in enumerate(source_positions)
    }
    unclassified = set(source_positions)
    orbit_rows: list[SubsetFamilyOrbitProfileRow] = []
    generated_images = 0
    generated_transporters = 0
    retained_incidences = 0

    while unclassified:
        seed = min(unclassified)
        orbit_images: set[tuple[int, ...]] = set()
        for permutation in group:
            orbit_images.add(_transport_subset(permutation, seed))
            generated_images += 1
            if generated_images > MAX_ORBIT_PROFILE_IMAGES:
                raise OperationDomainValidationError(
                    location=("subsets",),
                    code="finite_group_action.subset_family_orbit_work_exceeded",
                    message=(
                        f"generated orbit-image work exceeds the bounded maximum "
                        f"{MAX_ORBIT_PROFILE_IMAGES}"
                    ),
                )

        orbit_size = len(orbit_images)
        representative = min(orbit_images)
        generated_transporters += orbit_size
        if generated_transporters > MAX_ORBIT_PROFILE_TRANSPORTERS:
            raise OperationDomainValidationError(
                location=("subsets",),
                code="finite_group_action.subset_family_orbit_transport_work_exceeded",
                message=(
                    f"generated orbit-canonicalization work exceeds the bounded "
                    f"maximum {MAX_ORBIT_PROFILE_TRANSPORTERS}"
                ),
            )
        supplied = sorted(
            index
            for image in orbit_images
            if (index := source_index.get(image)) is not None
        )
        if not supplied:
            raise ValueError("orbit generation lost the representative source subset")
        # Each serialized representative currently retains its action carrier;
        # charge that repeated projection for every output row.
        retained_incidences += len(representative) * (1 + len(supplied)) + len(
            action.domain
        ) * (1 + len(action.generators))
        if retained_incidences > MAX_ORBIT_PROFILE_INCIDENCES:
            raise OperationDomainValidationError(
                location=("subsets",),
                code="finite_group_action.subset_family_orbit_result_exceeded",
                message=(
                    "retained orbit-profile incidence work exceeds the bounded "
                    f"maximum {MAX_ORBIT_PROFILE_INCIDENCES}"
                ),
            )
        orbit_rows.append(
            SubsetFamilyOrbitProfileRow(
                representative=ActionBoundSubset(
                    action=action, positions=representative
                ),
                source_indices=tuple(supplied),
                supplied_count=len(supplied),
                orbit_size=orbit_size,
                stabilizer_size=group_order // orbit_size,
            )
        )
        unclassified -= set(orbit_images)

    rows = tuple(
        sorted(
            orbit_rows,
            key=lambda row: (
                row.representative.positions,
                row.representative.action.domain,
                row.representative.action.generators,
            ),
        )
    )
    return SubsetFamilyOrbitProfileResult._from_kernel(
        action=action,
        group_order=group_order,
        family_size=len(source_positions),
        subsets=source_positions,
        rows=rows,
    )


def element_cycles(
    action: FinitePermutationAction, element: int
) -> ElementCyclesResult:
    """Compute the cycle decomposition of one group element."""
    perm, cycles, lengths, cycle_type, fixed, support = _element_cycles_data(
        action, element
    )
    return ElementCyclesResult._from_kernel(
        action,
        element,
        perm,
        cycles,
        lengths,
        cycle_type,
        fixed,
        support,
    )


def subset_canonicalization(
    subset: ActionBoundSubset,
) -> SubsetCanonicalizationResult:
    """Canonicalize one action-bound subset under its permutation action."""
    action = subset.action
    canonical, transporter, orbit_size, stabilizer_size = _subset_canonicalization_data(
        action, subset.positions
    )
    return SubsetCanonicalizationResult._from_kernel(
        subset,
        ActionBoundSubset(action=action, positions=canonical),
        transporter,
        orbit_size,
        stabilizer_size,
    )


def cycle_index(action: FinitePermutationAction) -> CycleIndexResult:
    """Compute the cycle-index polynomial of the action."""
    group_order, degree, counts = _cycle_index_data(action)
    return CycleIndexResult._from_kernel(action, group_order, degree, counts)


def burnside_count(action: FinitePermutationAction) -> BurnsideCountResult:
    """Compute the number of orbits under the action via Burnside's lemma."""
    group_order, contributions, orbit_count = _burnside_data(action)
    return BurnsideCountResult._from_kernel(
        action, group_order, contributions, orbit_count
    )


def polya_inventory(
    action: FinitePermutationAction, colors: int
) -> PolyaInventoryResult:
    """Compute the Pólya enumeration inventory polynomial."""
    degree, terms = _polya_inventory_data(action, colors)
    return PolyaInventoryResult._from_kernel(action, colors, degree, terms)


def verify_element_cycles(claim: ElementCyclesResult) -> bool:
    """Check one supplied cycle-decomposition claim at its consumer boundary."""
    if not isinstance(claim, ElementCyclesResult):
        return False
    try:
        group = _enumerate_group(claim.action)
        if not 0 <= claim.element < len(group):
            return False
        permutation = group[claim.element]
        if claim.permutation != permutation:
            return False
        n = len(permutation)
        if not claim.cycles or sorted(
            position for cycle in claim.cycles for position in cycle
        ) != list(range(n)):
            return False
        if claim.cycles != tuple(sorted(claim.cycles, key=min)):
            return False
        for cycle in claim.cycles:
            if cycle[0] != min(cycle) or any(
                permutation[position] != cycle[(index + 1) % len(cycle)]
                for index, position in enumerate(cycle)
            ):
                return False
        lengths = tuple(sorted((len(cycle) for cycle in claim.cycles), reverse=True))
        fixed_points = tuple(
            position for position in range(n) if permutation[position] == position
        )
        support = tuple(
            position for position in range(n) if permutation[position] != position
        )
        return (
            claim.cycle_lengths == lengths
            and claim.cycle_type == lengths
            and claim.fixed_points == fixed_points
            and claim.fixed_point_count == len(fixed_points)
            and claim.support == support
        )
    except (AttributeError, IndexError, KeyError, TypeError, ValueError):
        return False


def verify_cycle_index(claim: CycleIndexResult) -> bool:
    """Check a supplied cycle-index multiplicity claim against its action."""
    if not isinstance(claim, CycleIndexResult):
        return False
    try:
        group = _enumerate_group(claim.action)
        if claim.group_order != len(group) or claim.degree != len(claim.action.domain):
            return False
        counts: dict[tuple[int, ...], int] = {}
        for permutation in group:
            cycle_type = _permutation_cycle_type(permutation)
            counts[cycle_type] = counts.get(cycle_type, 0) + 1
        return claim.cycle_type_counts == tuple(sorted(counts.items()))
    except (AttributeError, IndexError, KeyError, TypeError, ValueError):
        return False


def verify_burnside_count(claim: BurnsideCountResult) -> bool:
    """Check a supplied Burnside sum and quotient against its action."""
    if not isinstance(claim, BurnsideCountResult):
        return False
    try:
        group = _enumerate_group(claim.action)
        if claim.group_order != len(group):
            return False
        contributions = tuple(
            sum(permutation[position] == position for position in range(len(permutation)))
            for permutation in group
        )
        total = sum(contributions)
        return (
            claim.fixed_point_contributions == contributions
            and claim.fixed_point_sum == total
            and total % len(group) == 0
            and claim.orbit_count == total // len(group)
        )
    except (AttributeError, IndexError, KeyError, TypeError, ValueError):
        return False


def verify_polya_inventory(claim: PolyaInventoryResult) -> bool:
    """Check a supplied Pólya inventory claim against its bounded action."""
    if not isinstance(claim, PolyaInventoryResult):
        return False
    try:
        group = _enumerate_group(claim.action)
        if claim.degree != len(claim.action.domain):
            return False
        expected_terms = _polya_terms_from_group(group, claim.colors)
        return claim.terms == expected_terms
    except (AttributeError, IndexError, KeyError, TypeError, ValueError):
        return False


def verify_subset_family_orbit_profile(
    claim: SubsetFamilyOrbitProfileResult,
) -> bool:
    """Check every orbit-profile summary against its retained source family."""
    if not isinstance(claim, SubsetFamilyOrbitProfileResult):
        return False
    try:
        return subset_family_orbit_profile(claim.action, claim.subsets) == claim
    except (AttributeError, IndexError, KeyError, TypeError, ValueError):
        return False


__all__ = [
    "burnside_count",
    "cycle_index",
    "element_cycles",
    "polya_inventory",
    "subset_canonicalization",
    "subset_family_orbit_profile",
    "verify_burnside_count",
    "verify_cycle_index",
    "verify_element_cycles",
    "verify_polya_inventory",
    "verify_subset_family_orbit_profile",
]
