"""Divisibility-owned exact number-theory capabilities."""

from jacobian.contracts.number_theory import (
    BooleanResult,
    DivisibilityRequest,
    ExtendedGcdResult,
    IntegerPairRequest,
    IntegerValueRequest,
    IntegerValueResult,
    NonnegativeIntegerRequest,
    PositiveIntegerRequest,
    ValuationRequest,
)
from jacobian.domains._examples import example
from jacobian.domains.number_theory._support import (
    number_theory_operation,
)
from jacobian.domains.number_theory.divisibility_operations import (
    compute_aliquot_sum,
    compute_divisor_count,
    compute_divisor_sum,
    compute_extended_gcd,
    compute_gcd,
    compute_lcm,
    compute_valuation,
    decide_abundant,
    decide_coprime,
    decide_deficient,
    decide_divides,
    decide_even,
    decide_odd,
    decide_perfect,
    decide_square,
)
from jacobian.domains.number_theory.factorization import FACTORIZATION_CAPABILITIES

DIVISIBILITY_CAPABILITIES = (
    *FACTORIZATION_CAPABILITIES,
    number_theory_operation(
        "integer.compute.gcd",
        "Compute integer gcd",
        "Compute the nonnegative greatest common divisor of two integers.",
        IntegerPairRequest,
        IntegerValueResult,
        compute_gcd,
        "number-theory",
        "divisibility",
        invocation_examples=(
            example("gcd_84_30", "Compute gcd(84, 30).", {"left": "84", "right": "30"}),
        ),
    ),
    number_theory_operation(
        "integer.compute.lcm",
        "Compute integer lcm",
        "Compute the nonnegative least common multiple of two integers.",
        IntegerPairRequest,
        IntegerValueResult,
        compute_lcm,
        "number-theory",
        "divisibility",
        invocation_examples=(
            example("lcm_12_18", "Compute lcm(12, 18).", {"left": "12", "right": "18"}),
        ),
    ),
    number_theory_operation(
        "integer.compute.extended_gcd",
        "Compute Bezout coefficients",
        "Compute a gcd and exact Bezout coefficients for two integers.",
        IntegerPairRequest,
        ExtendedGcdResult,
        compute_extended_gcd,
        "number-theory",
        "certificate",
        invocation_examples=(
            example(
                "bezout_84_30",
                "Compute Bezout coefficients for 84 and 30.",
                {"left": "84", "right": "30"},
            ),
        ),
    ),
    number_theory_operation(
        "integer.compute.valuation",
        "Compute prime-adic valuation",
        "Compute the exponent of a prime in one nonzero integer.",
        ValuationRequest,
        IntegerValueResult,
        compute_valuation,
        "number-theory",
        "valuation",
        invocation_examples=(
            example(
                "valuation_40_at_2",
                "Compute the 2-adic valuation of 40.",
                {"value": "40", "prime": "2"},
            ),
        ),
    ),
    number_theory_operation(
        "integer.compute.divisor_count",
        "Count positive divisors",
        "Compute the number of positive divisors of one positive integer.",
        PositiveIntegerRequest,
        IntegerValueResult,
        compute_divisor_count,
        "number-theory",
        "divisibility",
        invocation_examples=(
            example(
                "divisor_count_36", "Count the positive divisors of 36.", {"n": 36}
            ),
        ),
    ),
    number_theory_operation(
        "integer.compute.divisor_sum",
        "Sum positive divisors",
        "Compute the sum of every positive divisor of one positive integer.",
        PositiveIntegerRequest,
        IntegerValueResult,
        compute_divisor_sum,
        "number-theory",
        "divisibility",
        invocation_examples=(
            example("divisor_sum_12", "Sum the positive divisors of 12.", {"n": 12}),
        ),
    ),
    number_theory_operation(
        "integer.compute.aliquot_sum",
        "Compute aliquot sum",
        "Compute the sum of positive proper divisors of one positive integer.",
        PositiveIntegerRequest,
        IntegerValueResult,
        compute_aliquot_sum,
        "number-theory",
        "divisibility",
        invocation_examples=(
            example("aliquot_sum_12", "Compute the aliquot sum of 12.", {"n": 12}),
        ),
    ),
    number_theory_operation(
        "integer.decide.coprime",
        "Decide coprimality",
        "Decide whether two integers have gcd one.",
        IntegerPairRequest,
        BooleanResult,
        decide_coprime,
        "number-theory",
        "predicate",
        invocation_examples=(
            example(
                "coprime_14_25",
                "Check whether 14 and 25 are coprime.",
                {"left": "14", "right": "25"},
            ),
        ),
    ),
    number_theory_operation(
        "integer.decide.divides",
        "Decide divisibility",
        "Decide whether the first nonzero integer divides the second.",
        DivisibilityRequest,
        BooleanResult,
        decide_divides,
        "number-theory",
        "predicate",
        invocation_examples=(
            example(
                "divides_6_42",
                "Check whether 6 divides 42.",
                {"divisor": "6", "dividend": "42"},
            ),
        ),
    ),
    number_theory_operation(
        "integer.decide.even",
        "Decide evenness",
        "Decide whether one integer is divisible by two.",
        IntegerValueRequest,
        BooleanResult,
        decide_even,
        "integer",
        "predicate",
        invocation_examples=(
            example("even_42", "Check whether 42 is even.", {"value": "42"}),
        ),
    ),
    number_theory_operation(
        "integer.decide.odd",
        "Decide oddness",
        "Decide whether one integer is not divisible by two.",
        IntegerValueRequest,
        BooleanResult,
        decide_odd,
        "integer",
        "predicate",
        invocation_examples=(
            example("odd_41", "Check whether 41 is odd.", {"value": "41"}),
        ),
    ),
    number_theory_operation(
        "integer.decide.square",
        "Decide perfect square",
        "Decide whether a nonnegative integer is a square.",
        NonnegativeIntegerRequest,
        BooleanResult,
        decide_square,
        "number-theory",
        "predicate",
        invocation_examples=(
            example("square_144", "Check whether 144 is a perfect square.", {"n": 144}),
        ),
    ),
    number_theory_operation(
        "integer.decide.perfect",
        "Decide perfect number",
        "Decide whether a positive integer equals its aliquot sum.",
        NonnegativeIntegerRequest,
        BooleanResult,
        decide_perfect,
        "number-theory",
        "predicate",
        invocation_examples=(
            example("perfect_28", "Check whether 28 is perfect.", {"n": 28}),
        ),
    ),
    number_theory_operation(
        "integer.decide.abundant",
        "Decide abundant number",
        "Decide whether a positive integer has aliquot sum greater than itself.",
        NonnegativeIntegerRequest,
        BooleanResult,
        decide_abundant,
        "number-theory",
        "predicate",
        invocation_examples=(
            example("abundant_12", "Check whether 12 is abundant.", {"n": 12}),
        ),
    ),
    number_theory_operation(
        "integer.decide.deficient",
        "Decide deficient number",
        "Decide whether a positive integer has aliquot sum below itself.",
        NonnegativeIntegerRequest,
        BooleanResult,
        decide_deficient,
        "number-theory",
        "predicate",
        invocation_examples=(
            example("deficient_10", "Check whether 10 is deficient.", {"n": 10}),
        ),
    ),
)
