"""Numerical semigroup operations backed by exact integer arithmetic."""

from __future__ import annotations

from jacobian.contracts.numerical_semigroup import (
    NumericalSemigroupMembershipRequest,
    NumericalSemigroupMembershipResult,
    NumericalSemigroupRequest,
    NumericalSemigroupSummary,
)


def _compute_gaps(generators: tuple[int, ...]) -> tuple[int, ...]:
    """Compute all gaps of the numerical semigroup using the Apéry set method."""
    m = min(generators)
    gen_set = set(generators)

    # Compute Apéry set: for each residue r mod m, find the least element in S congruent to r
    # Then all gaps are the numbers not representable
    # Frobenius number F = max(Apéry) - m
    # Conductor c = F + 1
    # All numbers >= c are in the semigroup
    # We enumerate gaps below the conductor

    # First compute Apéry set
    apery = {}
    for r in range(m):
        # Find least s in S with s % m == r
        # s = r if r == 0, else find the smallest nonneg solution
        # Start with r and add m until we find a representable number
        candidate = r if r > 0 else m
        if r == 0:
            apery[0] = m  # Actually 0 is in S, but conventionally apery[0] = 0
            apery[0] = 0
            continue
        # Find the smallest s >= 0 with s % m == r and s in S
        found = None
        # Try increasing values
        s = r
        while True:
            if _is_in_semigroup(generators, s):
                found = s
                break
            s += m
            if s > 10000:  # safety bound
                break
        if found is None:
            apery[r] = -1  # shouldn't happen for gcd=1
        else:
            apery[r] = found

    # Frobenius number
    max_apery = max(apery.values())
    frobenius = max_apery - m

    conductor = frobenius + 1

    # Enumerate gaps
    gaps = []
    for n in range(conductor):
        if not _is_in_semigroup(generators, n):
            gaps.append(n)

    return tuple(gaps)


def _is_in_semigroup(generators: tuple[int, ...], n: int) -> bool:
    """Check if n is in the numerical semigroup generated by generators."""
    if n == 0:
        return True
    if n < 0:
        return False
    # Use dynamic programming for bounded n
    reachable = [False] * (n + 1)
    reachable[0] = True
    for i in range(1, n + 1):
        for g in generators:
            if i >= g and reachable[i - g]:
                reachable[i] = True
                break
    return reachable[n]


def _compute_aperey_set(generators: tuple[int, ...]) -> dict[int, int]:
    """Compute the Apéry set of the semigroup with respect to its multiplicity."""
    m = min(generators)
    apery = {0: 0}
    for r in range(1, m):
        s = r
        while s <= 10000:
            if _is_in_semigroup(generators, s):
                apery[r] = s
                break
            s += m
    return apery


def _compute_minimal_generators(generators: tuple[int, ...]) -> tuple[int, ...]:
    """Compute the minimal generating set by removing redundant generators."""
    gen_list = sorted(set(generators))
    minimal = []
    for g in gen_list:
        if not _is_in_semigroup(tuple(x for x in gen_list if x != g), g):
            minimal.append(g)
    return tuple(minimal)


def compute_numerical_semigroup_summary(
    request: NumericalSemigroupRequest,
) -> NumericalSemigroupSummary:
    """Compute a summary of a numerical semigroup."""
    generators = tuple(sorted(set(request.generators)))
    m = generators[0]  # multiplicity = least generator

    # Compute minimal generators
    minimal_gens = _compute_minimal_generators(generators)

    # Compute Apéry set
    apery = _compute_aperey_set(generators)

    # Frobenius number
    max_apery = max(apery.values())
    frobenius = max_apery - m

    conductor = frobenius + 1
    genus = len([n for n in range(conductor) if not _is_in_semigroup(generators, n)])
    gaps = tuple(n for n in range(conductor) if not _is_in_semigroup(generators, n))

    apery_tuple = tuple((r, s) for r, s in sorted(apery.items()))

    return NumericalSemigroupSummary(
        minimal_generators=minimal_gens,
        multiplicity=m,
        embedding_dimension=len(minimal_gens),
        frobenius_number=frobenius,
        conductor=conductor,
        genus=genus,
        gaps=gaps,
        aperey_set=apery_tuple,
    )


def check_numerical_semigroup_membership(
    request: NumericalSemigroupMembershipRequest,
) -> NumericalSemigroupMembershipResult:
    """Check if an element is in a numerical semigroup."""
    is_member = _is_in_semigroup(tuple(request.generators), request.element)
    return NumericalSemigroupMembershipResult(
        is_member=is_member,
        element=request.element,
        detail=f"{request.element} is {'in' if is_member else 'not in'} the numerical semigroup.",
    )
