"""MathTool declarations for numerical semigroup operations."""

from __future__ import annotations

from jacobian.contracts.numerical_semigroup import (
    NumericalSemigroupMembershipRequest,
    NumericalSemigroupMembershipResult,
    NumericalSemigroupRequest,
    NumericalSemigroupSummary,
)
from jacobian.domains._examples import example
from jacobian.domains.number_theory.numerical_semigroup_operations import (
    check_numerical_semigroup_membership,
    compute_numerical_semigroup_summary,
)
from jacobian.math_tools import MathTool


NUMERICAL_SEMIGROUP_OPERATIONS: tuple[MathTool, ...] = (
    MathTool(
        operation_id="number_theory.numerical_semigroup.summary.compute",
        version="1",
        title="Compute a numerical semigroup summary",
        description=(
            "Compute the minimal generators, multiplicity, embedding "
            "dimension, Apéry set, Frobenius number, conductor, genus, "
            "and gap list for a numerical semigroup generated by a finite "
            "set of positive integers with gcd one."
        ),
        request_type=NumericalSemigroupRequest,
        result_type=NumericalSemigroupSummary,
        run=compute_numerical_semigroup_summary,
        tags=(
            "number-theory",
            "numerical-semigroup",
            "gaps",
            "frobenius",
            "apery",
            "conductor",
            "genus",
        ),
        examples=(
            example(
                "semigroup_3_5",
                "Summary of the numerical semigroup generated by {3, 5}.",
                {"generators": [3, 5]},
            ),
        ),
    ),
    MathTool(
        operation_id="number_theory.numerical_semigroup.membership.check",
        version="1",
        title="Check membership in a numerical semigroup",
        description=(
            "Check whether a non-negative integer is a member of the "
            "numerical semigroup generated by a finite set of positive "
            "integers with gcd one."
        ),
        request_type=NumericalSemigroupMembershipRequest,
        result_type=NumericalSemigroupMembershipResult,
        run=check_numerical_semigroup_membership,
        tags=(
            "number-theory",
            "numerical-semigroup",
            "membership",
            "predicate",
        ),
        examples=(
            example(
                "check_7_in_3_5",
                "Check if 7 is in the semigroup generated by {3, 5}.",
                {"generators": [3, 5], "element": 7},
            ),
        ),
    ),
)

__all__ = ["NUMERICAL_SEMIGROUP_OPERATIONS"]
