"""Typed bounded values for initial ideals and Hilbert-function prefixes."""

from __future__ import annotations

from math import comb
from typing import Annotated, Literal, Self

from pydantic import Field, StrictInt, model_validator

from jacobian._exact import CanonicalRational, ExactInteger
from jacobian._models import StrictModel
from jacobian.math.polynomials.ideals._models import (
    IdealComputationBudget,
)
from jacobian.math.polynomials.values import (
    MAX_POLYNOMIAL_VARIABLES,
    MAX_RATIONAL_FUNCTION_EXPONENT,
    RationalFunction,
    RationalPolynomial,
    RationalPolynomialIdeal,
    RationalPolynomialTerm,
    SparseRationalPolynomial,
)

MAX_GRADED_DEGREE = 32
MAX_STANDARD_MONOMIALS = 20_000
MAX_HILBERT_SERIES_GENERATORS = 8
MAX_HILBERT_PREFIX = 16

NonnegativeHilbertCount = Annotated[StrictInt, Field(ge=0)]
GradedMonomial = Annotated[
    tuple[StrictInt, ...],
    Field(max_length=MAX_POLYNOMIAL_VARIABLES),
]


class InitialMonomialIdealRequest(StrictModel):
    ideal: RationalPolynomialIdeal
    monomial_order: Literal["lex", "grlex", "grevlex"] = "grevlex"
    resource_budget: IdealComputationBudget = Field(
        default_factory=IdealComputationBudget
    )


class InitialMonomialIdealResult(StrictModel):
    ideal: RationalPolynomialIdeal
    groebner_basis: RationalPolynomialIdeal
    initial_ideal: RationalPolynomialIdeal
    monomial_order: Literal["lex", "grlex", "grevlex"]

    @model_validator(mode="after")
    def require_same_ring(self) -> Self:
        if not (
            self.ideal.variables
            == self.groebner_basis.variables
            == self.initial_ideal.variables
        ):
            raise ValueError("initial-ideal values must share one ordered ring")
        for generator in self.initial_ideal.generators:
            terms = generator.polynomial.terms
            if not terms:
                continue
            if len(terms) != 1 or terms[0].coefficient != CanonicalRational(
                num=1, den=1
            ):
                raise ValueError(
                    "initial ideals must be generated by unit monomials or zero"
                )
        return self


class StandardMonomialsRequest(StrictModel):
    initial_ideal: RationalPolynomialIdeal
    degree: StrictInt = Field(ge=0, le=MAX_GRADED_DEGREE)


class StandardMonomialsResult(StrictModel):
    initial_ideal: RationalPolynomialIdeal
    degree: StrictInt = Field(ge=0, le=MAX_GRADED_DEGREE)
    monomials: tuple[GradedMonomial, ...] = Field(max_length=MAX_STANDARD_MONOMIALS)
    count: StrictInt = Field(ge=0, le=MAX_STANDARD_MONOMIALS)

    @model_validator(mode="after")
    def require_count(self) -> Self:
        if self.count != len(self.monomials):
            raise ValueError("standard-monomial count must match the returned list")
        if any(
            len(monomial) != len(self.initial_ideal.variables)
            or sum(monomial) != self.degree
            or any(exponent < 0 for exponent in monomial)
            for monomial in self.monomials
        ):
            raise ValueError(
                "standard monomials must match the ordered ring and degree"
            )
        if self.monomials != tuple(sorted(set(self.monomials), reverse=True)):
            raise ValueError("standard monomials must be unique and canonical")
        return self


class HilbertFunctionRequest(StrictModel):
    ideal: RationalPolynomialIdeal
    monomial_order: Literal["lex", "grlex", "grevlex"] = "grevlex"
    max_degree: StrictInt = Field(default=0, ge=0, le=MAX_GRADED_DEGREE)
    resource_budget: IdealComputationBudget = Field(
        default_factory=IdealComputationBudget
    )


class HilbertFunctionResult(StrictModel):
    ideal: RationalPolynomialIdeal
    initial_ideal: RationalPolynomialIdeal
    monomial_order: Literal["lex", "grlex", "grevlex"]
    values: tuple[NonnegativeHilbertCount, ...] = Field(
        min_length=1, max_length=MAX_GRADED_DEGREE + 1
    )

    @model_validator(mode="after")
    def require_source_ring(self) -> Self:
        if self.ideal.variables != self.initial_ideal.variables:
            raise ValueError("Hilbert-function values must share the source ring")
        return self


class HilbertSeriesRequest(StrictModel):
    ideal: RationalPolynomialIdeal
    monomial_order: Literal["lex", "grlex", "grevlex"] = "grevlex"
    prefix_degree: StrictInt = Field(default=0, ge=0, le=MAX_HILBERT_PREFIX)
    resource_budget: IdealComputationBudget = Field(
        default_factory=IdealComputationBudget
    )


class HilbertPolynomialRequest(StrictModel):
    ideal: RationalPolynomialIdeal
    monomial_order: Literal["lex", "grlex", "grevlex"] = "grevlex"
    resource_budget: IdealComputationBudget = Field(
        default_factory=IdealComputationBudget
    )


def _monic_t_minus_one_power(degree: int) -> SparseRationalPolynomial:
    terms = tuple(
        RationalPolynomialTerm(
            coefficient=CanonicalRational(
                num=comb(degree, index) * ((-1) ** (degree - index)), den=1
            ),
            exponents=(index,),
        )
        for index in range(degree, -1, -1)
        if comb(degree, index) != 0
    )
    return SparseRationalPolynomial(terms=terms)


class HilbertSeriesResult(StrictModel):
    """A bounded Hilbert series with both canonical and graded numerator axes.

    ``reduced_numerator`` is the numerator owned by the canonical rational
    function carrier, whose denominator is monic.  ``h_numerator`` is the
    sign-corrected numerator in the mathematical convention
    ``H(t) = h(t)/(1-t)^d``; the two differ when ``d`` is odd.
    """

    ideal: RationalPolynomialIdeal
    initial_ideal: RationalPolynomialIdeal
    monomial_order: Literal["lex", "grlex", "grevlex"]
    ambient_numerator: RationalPolynomial
    ambient_denominator_exponent: StrictInt = Field(ge=0)
    series: RationalFunction
    reduced_numerator: RationalPolynomial
    h_numerator: RationalPolynomial
    denominator_exponent: StrictInt = Field(ge=0, le=MAX_RATIONAL_FUNCTION_EXPONENT)
    prefix: tuple[NonnegativeHilbertCount, ...] = Field(
        min_length=1, max_length=MAX_HILBERT_PREFIX + 1
    )

    @model_validator(mode="after")
    def require_source_and_axes(self) -> Self:
        if self.ideal.variables != self.initial_ideal.variables:
            raise ValueError("Hilbert-series values must share the source ring")
        if self.ambient_denominator_exponent != len(self.ideal.variables):
            raise ValueError(
                "ambient denominator exponent must equal the source-ring dimension"
            )
        if self.denominator_exponent > len(self.ideal.variables):
            raise ValueError(
                "Hilbert-series dimension cannot exceed the source-ring dimension"
            )
        if self.ambient_numerator.variables != ("t",):
            raise ValueError("Hilbert-series numerators use the t axis")
        if (
            self.series.variables != ("t",)
            or self.reduced_numerator.variables != ("t",)
            or self.h_numerator.variables != ("t",)
        ):
            raise ValueError("Hilbert-series values use the t axis")
        if self.series.numerator != self.reduced_numerator.polynomial:
            raise ValueError("reduced numerator must match the rational-series carrier")
        if self.denominator_exponent > MAX_RATIONAL_FUNCTION_EXPONENT:
            raise ValueError(
                "Hilbert-series denominator exponent exceeds the rational-function envelope"
            )
        expected_denominator = _monic_t_minus_one_power(self.denominator_exponent)
        if self.series.denominator != expected_denominator:
            raise ValueError(
                "Hilbert-series denominator must be the monic (t-1)^d form"
            )
        sign = -1 if self.denominator_exponent % 2 else 1
        expected_h = tuple(
            RationalPolynomialTerm(
                coefficient=CanonicalRational(
                    num=sign * term.coefficient.num, den=term.coefficient.den
                ),
                exponents=term.exponents,
            )
            for term in self.reduced_numerator.polynomial.terms
        )
        if self.h_numerator.polynomial.terms != expected_h:
            raise ValueError("h-numerator must match the (1-t)^d sign convention")
        return self


class HilbertPolynomialResult(StrictModel):
    ideal: RationalPolynomialIdeal
    initial_ideal: RationalPolynomialIdeal
    monomial_order: Literal["lex", "grlex", "grevlex"]
    dimension: StrictInt = Field(ge=0)
    polynomial: RationalPolynomial
    stabilization_degree: StrictInt = Field(ge=0)

    @model_validator(mode="after")
    def require_source_and_axis(self) -> Self:
        if self.ideal.variables != self.initial_ideal.variables:
            raise ValueError("Hilbert-polynomial values must share the source ring")
        if self.dimension > len(self.ideal.variables):
            raise ValueError(
                "Hilbert-polynomial dimension cannot exceed the source-ring dimension"
            )
        if self.polynomial.variables != ("m",):
            raise ValueError("Hilbert polynomial uses the m axis")
        return self


class HilbertDimensionResult(StrictModel):
    ideal: RationalPolynomialIdeal
    initial_ideal: RationalPolynomialIdeal
    monomial_order: Literal["lex", "grlex", "grevlex"]
    dimension: StrictInt = Field(ge=0)

    @model_validator(mode="after")
    def require_source_ring(self) -> Self:
        if self.ideal.variables != self.initial_ideal.variables:
            raise ValueError("Hilbert-dimension values must share the source ring")
        if self.dimension > len(self.ideal.variables):
            raise ValueError(
                "Hilbert-dimension cannot exceed the source-ring dimension"
            )
        return self


class HilbertMultiplicityResult(StrictModel):
    ideal: RationalPolynomialIdeal
    initial_ideal: RationalPolynomialIdeal
    monomial_order: Literal["lex", "grlex", "grevlex"]
    dimension: StrictInt = Field(ge=0)
    multiplicity: ExactInteger = Field(ge=0)

    @model_validator(mode="after")
    def require_source_ring(self) -> Self:
        if self.ideal.variables != self.initial_ideal.variables:
            raise ValueError("Hilbert-multiplicity values must share the source ring")
        if self.dimension > len(self.ideal.variables):
            raise ValueError(
                "Hilbert-multiplicity dimension cannot exceed the source-ring dimension"
            )
        return self


class HVectorResult(StrictModel):
    ideal: RationalPolynomialIdeal
    initial_ideal: RationalPolynomialIdeal
    monomial_order: Literal["lex", "grlex", "grevlex"]
    dimension: StrictInt = Field(ge=0)
    h_vector: tuple[ExactInteger, ...] = Field(
        max_length=MAX_RATIONAL_FUNCTION_EXPONENT + 1
    )

    @model_validator(mode="after")
    def require_source_ring(self) -> Self:
        if self.ideal.variables != self.initial_ideal.variables:
            raise ValueError("h-vector values must share the source ring")
        if self.dimension > len(self.ideal.variables):
            raise ValueError(
                "h-vector dimension cannot exceed the source-ring dimension"
            )
        return self


__all__ = [
    "MAX_GRADED_DEGREE",
    "MAX_HILBERT_PREFIX",
    "MAX_HILBERT_SERIES_GENERATORS",
    "MAX_STANDARD_MONOMIALS",
    "HVectorResult",
    "HilbertDimensionResult",
    "HilbertFunctionRequest",
    "HilbertFunctionResult",
    "HilbertMultiplicityResult",
    "HilbertPolynomialRequest",
    "HilbertPolynomialResult",
    "HilbertSeriesRequest",
    "HilbertSeriesResult",
    "InitialMonomialIdealRequest",
    "InitialMonomialIdealResult",
    "StandardMonomialsRequest",
    "StandardMonomialsResult",
]
