"""Supported native combinatorial-map API."""

from jacobian.math.topology.combinatorial_maps.operations import (
    check_multigraph_embedding,
    check_orientable_embedding,
    check_signed_embedding,
    connected_components,
    connected_components_vertices,
    dual_map,
    euler_characteristic,
    face_orbits,
    find_rotation_system,
    minimum_orientable_genus,
    orientable_genus,
    orientation_reverse,
    rotation_successor,
    verify_dual,
    verify_minimum_orientable_genus,
    verify_multigraph_embedding,
    verify_orientable_embedding,
    verify_orientation_reverse,
    verify_rotation_system_find,
    verify_signed_embedding,
    verify_vertex_face_incidence,
    vertex_face_incidence,
)
from jacobian.math.topology.combinatorial_maps.values import (
    FacialWalk,
    FiniteCombinatorialMap,
)

__all__ = [
    "FacialWalk",
    "FiniteCombinatorialMap",
    "check_multigraph_embedding",
    "check_orientable_embedding",
    "check_signed_embedding",
    "connected_components",
    "connected_components_vertices",
    "dual_map",
    "euler_characteristic",
    "face_orbits",
    "find_rotation_system",
    "minimum_orientable_genus",
    "orientable_genus",
    "orientation_reverse",
    "rotation_successor",
    "verify_dual",
    "verify_minimum_orientable_genus",
    "verify_multigraph_embedding",
    "verify_orientable_embedding",
    "verify_orientation_reverse",
    "verify_rotation_system_find",
    "verify_signed_embedding",
    "verify_vertex_face_incidence",
    "vertex_face_incidence",
]
