"""Numerical semigroup operation declarations."""

from collections.abc import Callable
from typing import Any

from jacobian.contracts.base import ContractModel
from jacobian.contracts.numerical_semigroups import (
    NumericalSemigroupSummaryRequest,
    NumericalSemigroupSummaryResult,
    SemigroupMembershipRequest,
    SemigroupMembershipResult,
)
from jacobian.contracts.operations import OperationExample
from jacobian.domains._examples import example
from jacobian.domains.numerical_semigroups.operations import (
    compute_membership,
    compute_summary,
)
from jacobian.math_tools import MathTool


def _operation[
    RequestT: ContractModel,
    ResultT: ContractModel,
](
    operation_id: str,
    title: str,
    description: str,
    request_model: type[RequestT],
    result_model: type[ResultT],
    operation: Callable[[RequestT], ResultT],
    *tags: str,
    examples: tuple[OperationExample, ...] = (),
    version: str = "1",
) -> MathTool[RequestT, ResultT]:
    return MathTool(
        operation_id=operation_id,
        version=version,
        title=title,
        description=description,
        request_type=request_model,
        result_type=result_model,
        run=operation,
        tags=tags,
        examples=examples,
    )


NUMERICAL_SEMIGROUP_OPERATIONS: tuple[MathTool[Any, Any], ...] = (
    _operation(
        "number_theory.numerical_semigroup.summary.compute",
        "Compute numerical semigroup summary",
        "Given a finite set of positive generators with gcd 1, compute "
        "minimal generators, multiplicity, embedding dimension, Frobenius "
        "number, conductor, genus, and gap list.",
        NumericalSemigroupSummaryRequest,
        NumericalSemigroupSummaryResult,
        compute_summary,
        "number-theory",
        "numerical-semigroup",
        "exact",
        examples=(
            example(
                "semigroup_3_5",
                "Summary of <3,5>.",
                {"generators": ["3", "5"]},
            ),
        ),
    ),
    _operation(
        "number_theory.numerical_semigroup.membership.compute",
        "Check numerical semigroup membership",
        "Check whether a given integer is in the numerical semigroup "
        "generated by the given generators.",
        SemigroupMembershipRequest,
        SemigroupMembershipResult,
        compute_membership,
        "number-theory",
        "numerical-semigroup",
        "exact",
        examples=(
            example(
                "membership_8_in_3_5",
                "Check if 8 is in <3,5>.",
                {"generators": ["3", "5"], "value": "8"},
            ),
        ),
    ),
)


__all__ = ["NUMERICAL_SEMIGROUP_OPERATIONS"]
