"""Domain adapter for numerical semigroup operations."""

from __future__ import annotations

from jacobian.contracts.numerical_semigroups import (
    NumericalSemigroupSummaryRequest,
    NumericalSemigroupSummaryResult,
    SemigroupMembershipRequest,
    SemigroupMembershipResult,
)


def _normalize_generators(gens: tuple[str, ...]) -> list[int]:
    """Return sorted unique positive generators."""
    seen = set()
    result = []
    for g in sorted(int(x) for x in gens):
        if g > 0 and g not in seen:
            seen.add(g)
            result.append(g)
    return result


def _gcd(a: int, b: int) -> int:
    while b:
        a, b = b, a % b
    return a


def _check_gcd_one(gens: list[int]) -> None:
    g = gens[0]
    for x in gens[1:]:
        g = _gcd(g, x)
    if g != 1:
        raise ValueError(f"generators must have gcd 1, got gcd {g}")


def _compute_summary(gens: list[int]) -> NumericalSemigroupSummaryResult:
    _check_gcd_one(gens)
    multiplicity = gens[0]
    # Compute membership up to conductor using dynamic programming
    # A value n is in the semigroup if n is 0 or n-g_i is in for some g_i
    max_check = multiplicity * multiplicity  # Frobenius < m^2 for gcd=1
    in_sg = [False] * (max_check + 1)
    in_sg[0] = True
    for i in range(1, max_check + 1):
        for g in gens:
            if i >= g and in_sg[i - g]:
                in_sg[i] = True
                break

    gaps = [i for i in range(max_check + 1) if i > 0 and not in_sg[i]]
    genus = len(gaps)
    frobenius = max(gaps) if gaps else -1
    conductor = frobenius + 1

    # Minimal generators: generators not expressible as a non-negative
    # combination of the others
    min_gens = []
    for g in gens:
        # Check if g is in the semigroup generated by the others
        others = [x for x in gens if x != g]
        if not others:
            min_gens.append(g)
            continue
        # Check if g is a non-negative combination of others
        can_reach = [False] * (g + 1)
        can_reach[0] = True
        for i in range(1, g + 1):
            for og in others:
                if i >= og and can_reach[i - og]:
                    can_reach[i] = True
                    break
        if not can_reach[g]:
            min_gens.append(g)

    return NumericalSemigroupSummaryResult(
        minimal_generators=tuple(str(g) for g in min_gens),
        multiplicity=str(multiplicity),
        embedding_dimension=len(min_gens),
        frobenius_number=str(frobenius),
        conductor=str(conductor),
        genus=genus,
        gaps=tuple(str(g) for g in gaps),
    )


def compute_summary(
    request: NumericalSemigroupSummaryRequest,
) -> NumericalSemigroupSummaryResult:
    gens = _normalize_generators(request.generators)
    return _compute_summary(gens)


def compute_membership(
    request: SemigroupMembershipRequest,
) -> SemigroupMembershipResult:
    gens = _normalize_generators(request.generators)
    value = int(request.value)
    if value < 0:
        return SemigroupMembershipResult(value=request.value, in_semigroup=False)
    if value == 0:
        return SemigroupMembershipResult(value=request.value, in_semigroup=True)
    # Dynamic programming
    can_reach = [False] * (value + 1)
    can_reach[0] = True
    for i in range(1, value + 1):
        for g in gens:
            if i >= g and can_reach[i - g]:
                can_reach[i] = True
                break
    return SemigroupMembershipResult(
        value=request.value,
        in_semigroup=can_reach[value],
    )


__all__ = ["compute_summary", "compute_membership"]
