"""Algebraic combinatorics operations."""

from jacobian.math.combinatorics.algebraic._models import (
    LongestDecreasingSubsequenceResult,
    LongestIncreasingSubsequenceResult,
    PartitionDominanceResult,
    PlacticEquivalenceRequest,
    PlacticEquivalenceResult,
    PlacticNormalFormResult,
    RSKWordInverseTraceResult,
    RSKWordTraceResult,
    SemistandardTableauCheckResult,
    SemistandardYoungTableauCountResult,
    StandardTableauCheckResult,
)
from jacobian.math.combinatorics.algebraic.biword import (
    Biword,
    BiwordRSKPair,
    GreeneWitnessResult,
    NonnegativeIntegerMatrix,
)
from jacobian.math.combinatorics.algebraic.biword_ops import (
    greene,
    inverse_biword,
    inverse_matrix,
    matrix_biword,
    normalize_biword,
    rsk_biword,
)
from jacobian.math.combinatorics.algebraic.greene_witnesses import (
    compute_greene_witnesses,
)
from jacobian.math.combinatorics.algebraic.operations import (
    check_semistandard_tableau,
    check_standard_tableau,
    conjugate_partition,
    hook_lengths,
    inverse_permutation_rsk,
    inverse_row_insertion_rsk,
    inverse_row_insertion_rsk_trace,
    knuth_moves,
    partition_dominance,
    permutation_rsk,
    plactic_equivalence,
    plactic_normal_form,
    row_insertion_rsk,
    row_insertion_rsk_trace,
    semistandard_young_tableaux_count,
    standard_young_tableaux_count,
    tableau_row_reading_word,
)
from jacobian.math.combinatorics.algebraic.subsequences import (
    longest_decreasing_subsequence,
    longest_increasing_subsequence,
)
from jacobian.math.combinatorics.algebraic.values import (
    FinitePermutation,
    PermutationRSKPair,
    RSKBumpStep,
    RSKInsertionEvent,
    RSKReverseBumpStep,
    RSKReverseInsertionEvent,
    RSKTableauPair,
)
from jacobian.math.combinatorics.algebraic.weighted_monotone._models import (
    EndpointProfileEntry,
    EndpointProfileResult,
    WeightedOrderedWord,
)
from jacobian.math.combinatorics.algebraic.weighted_monotone.operations import (
    compute_endpoint_profile,
)

__all__ = [
    "Biword",
    "BiwordRSKPair",
    "EndpointProfileEntry",
    "EndpointProfileResult",
    "FinitePermutation",
    "GreeneWitnessResult",
    "LongestDecreasingSubsequenceResult",
    "LongestIncreasingSubsequenceResult",
    "NonnegativeIntegerMatrix",
    "PartitionDominanceResult",
    "PermutationRSKPair",
    "PlacticEquivalenceRequest",
    "PlacticEquivalenceResult",
    "PlacticNormalFormResult",
    "RSKBumpStep",
    "RSKInsertionEvent",
    "RSKReverseBumpStep",
    "RSKReverseInsertionEvent",
    "RSKTableauPair",
    "RSKWordInverseTraceResult",
    "RSKWordTraceResult",
    "SemistandardTableauCheckResult",
    "SemistandardYoungTableauCountResult",
    "StandardTableauCheckResult",
    "WeightedOrderedWord",
    "check_semistandard_tableau",
    "check_standard_tableau",
    "compute_endpoint_profile",
    "compute_greene_witnesses",
    "conjugate_partition",
    "greene",
    "hook_lengths",
    "inverse_biword",
    "inverse_matrix",
    "inverse_permutation_rsk",
    "inverse_row_insertion_rsk",
    "inverse_row_insertion_rsk_trace",
    "knuth_moves",
    "longest_decreasing_subsequence",
    "longest_increasing_subsequence",
    "matrix_biword",
    "normalize_biword",
    "partition_dominance",
    "permutation_rsk",
    "plactic_equivalence",
    "plactic_normal_form",
    "row_insertion_rsk",
    "row_insertion_rsk_trace",
    "rsk_biword",
    "semistandard_young_tableaux_count",
    "standard_young_tableaux_count",
    "tableau_row_reading_word",
]
