"""Explicit bundle for exact declared graph-symmetry actions."""

from jacobian.contracts.capabilities import CapabilityDiagnostic
from jacobian.domains.graph_symmetry.checkers import (
    GRAPH_SYMMETRY_EXACT_REPLAY_CHECKERS,
)
from jacobian.domains.graph_symmetry.operations import GRAPH_SYMMETRY_CAPABILITIES
from jacobian.operations import DomainBundle, DomainDiagnostics, DomainSemantics
from jacobian.provider_runtime import NETWORKX_VERSION, known_provider_runtime


def build_graph_symmetry_bundle() -> DomainBundle:
    """Build this domain-owned installation unit explicitly."""
    return DomainBundle(
        domain_id="graph_symmetry",
        schema_namespace="jacobian.graph-symmetry",
        semantics=DomainSemantics(
            name="jacobian.declared-graph-symmetry",
            version="1",
            definition={
                "description": (
                    "exact vertex and edge orbit partitions under a subgroup generated "
                    "by explicit color-preserving graph automorphisms"
                ),
                "graph_class": "finite labelled simple undirected graph",
                "generator_scope": "only the subgroup generated by declared mappings",
                "vertex_colors": "optional complete color binding in graph vertex order",
                "edge_colors": "optional complete color binding in graph edge order",
                "orbit_completeness": "complete for the declared generator subgroup",
                "excluded": (
                    "full automorphism-group discovery, group order, canonical labeling, "
                    "quotient adjacency, edge-state orbits, and reliability equivalence"
                ),
            },
        ),
        provider_runtime=known_provider_runtime(
            "jacobian.networkx",
            features=(
                "declared-graph-automorphisms",
                "color-preserving-actions",
                "vertex-orbit-partition",
                "edge-orbit-partition",
                "union-find-orbit-closure",
            ),
        ),
        backend_version=NETWORKX_VERSION,
        capabilities=GRAPH_SYMMETRY_CAPABILITIES,
        diagnostics=DomainDiagnostics(
            invalid_request=CapabilityDiagnostic(
                code="INVALID_GRAPH_SYMMETRY_REQUEST",
                stage="graph_symmetry_input_validation",
                message="Input does not satisfy the bounded declared-symmetry contract.",
                hint=(
                    "Supply total vertex permutations that preserve every graph edge "
                    "and every declared vertex or edge color."
                ),
            )
        ),
        scope_description=(
            "the complete vertex and edge actions of every declared graph automorphism "
            "generator"
        ),
        completeness_basis=(
            "finite orbit closure under every declared generator and its inverse "
            "via NetworkX UnionFind"
        ),
        assurance_basis=(
            "exact NetworkX UnionFind computation capped at COMPUTED; independent "
            "replay is available through graph.symmetry.generator_orbits.verify"
        ),
        checker_declarations=GRAPH_SYMMETRY_EXACT_REPLAY_CHECKERS,
    )


__all__ = ["build_graph_symmetry_bundle"]
