"""Typed wire contracts for finite group-action operations."""

from __future__ import annotations

from typing import Annotated, Self

from pydantic import Field, model_validator
from pydantic_core import PydanticCustomError

from jacobian._models import StrictModel

MAX_DOMAIN_SIZE = 50
MAX_GROUP_ORDER = 10000
MAX_GENERATORS = 50
MAX_LABEL_LENGTH = 64
MAX_COLORS = 50
MAX_TERMS = 5000


def _validation_error(reason: str, message: str) -> PydanticCustomError:
    """Build stable owner-local validation errors for finite actions."""

    return PydanticCustomError(f"finite_group_action.{reason}", message)


DomainPosition = Annotated[int, Field(ge=0, le=MAX_DOMAIN_SIZE - 1)]
FiniteActionSubset = Annotated[
    tuple[DomainPosition, ...],
    Field(max_length=MAX_DOMAIN_SIZE),
]


class FinitePermutationAction(StrictModel):
    """A finite permutation group acting on a labelled set.

    ``domain`` is the tuple of unique string labels for the set ``X`` being
    acted on.  ``generators`` is a tuple of permutations of ``{0, ..., n-1}``
    (each a tuple of length ``n`` where ``permutation[i]`` is the image of
    ``domain[i]``).  The group is generated by the generators under
    composition; the action convention is a left action.
    """

    domain: tuple[str, ...] = Field(min_length=1, max_length=MAX_DOMAIN_SIZE)
    generators: tuple[tuple[int, ...], ...] = Field(
        min_length=1,
        max_length=MAX_GENERATORS,
        description=(
            f"One to {MAX_GENERATORS} generator permutations in array form; "
            "each must have length equal to the domain size."
        ),
    )

    @model_validator(mode="after")
    def require_valid_action(self) -> Self:
        labels = set(self.domain)
        if len(labels) != len(self.domain):
            raise _validation_error(
                "domain_labels_not_distinct", "domain labels must be distinct"
            )
        for label in self.domain:
            if len(label) > MAX_LABEL_LENGTH:
                raise _validation_error(
                    "domain_label_too_long",
                    "domain label exceeds the bounded length budget",
                )
        n = len(self.domain)
        for perm in self.generators:
            if len(perm) != n:
                raise _validation_error(
                    "generator_length_mismatch",
                    "every generator must be a permutation of the domain",
                )
            if sorted(perm) != list(range(n)):
                raise _validation_error(
                    "generator_not_permutation",
                    "every generator must be a total permutation of the domain",
                )
        return self


def _canonical_subset_positions(
    action: FinitePermutationAction,
    subset: FiniteActionSubset,
) -> tuple[int, ...]:
    if len(set(subset)) != len(subset):
        raise _validation_error(
            "subset_positions_not_distinct", "subset positions must be distinct"
        )
    if any(position >= len(action.domain) for position in subset):
        raise _validation_error(
            "subset_position_out_of_range",
            "every subset position must index the action domain",
        )
    return tuple(sorted(subset))


def _generated_group_order(action: FinitePermutationAction) -> int:
    """Return the exact generated-group order without enumerating its elements."""
    from sympy.combinatorics import Permutation, PermutationGroup

    generators = [Permutation(list(generator)) for generator in action.generators]
    return int(PermutationGroup(generators).order())


class _ActionRequest(StrictModel):
    """Shared request shape: one finite permutation action."""

    action: FinitePermutationAction


# ---------------------------------------------------------------------------
# group_action.subset.canonicalize
# ---------------------------------------------------------------------------


class ActionBoundSubset(StrictModel):
    """A subset of the acted-on labelled set, bound to its permutation action.

    ``positions`` are distinct 0-based indices into ``action.domain``, so the
    value denotes the exact labelled subset
    ``{action.domain[position] for position in positions}``.  Because the
    action travels inside the value, serializing and reloading it cannot
    silently reinterpret the same positions under a different labelled
    domain.  Wire order is immaterial and is normalized to increasing domain
    position.
    """

    action: FinitePermutationAction
    positions: FiniteActionSubset = Field(
        description=(
            "Distinct 0-based positions in action.domain; input order is "
            "normalized to increasing domain position."
        )
    )

    @model_validator(mode="after")
    def bind_positions_to_domain(self) -> Self:
        object.__setattr__(
            self,
            "positions",
            _canonical_subset_positions(self.action, self.positions),
        )
        return self


class SubsetCanonicalizationRequest(StrictModel):
    """Request a canonical image of an action-bound subset under its action.

    The subset carries the action giving its positions meaning, so a dumped
    canonical result replays into this request as one unchanged canonical
    value.  The generated group must have order at most 10000; validation
    establishes that bound with SymPy's Schreier--Sims order computation
    before the kernel enumerates any group elements.
    """

    subset: ActionBoundSubset = Field(
        description=(
            "The subset to canonicalize, bound to its permutation action. "
            f"The generated group must have order at most {MAX_GROUP_ORDER}."
        )
    )

    @model_validator(mode="after")
    def bound_generated_group_order(self) -> Self:
        order = _generated_group_order(self.subset.action)
        if order > MAX_GROUP_ORDER:
            raise _validation_error(
                "group_order_exceeds_bound",
                f"group order {order} exceeds the bounded maximum {MAX_GROUP_ORDER}",
            )
        return self


class SubsetCanonicalizationResult(StrictModel):
    """Action-bound canonical subset image, transporter, and orbit--stabilizer data.

    ``source_subset`` and ``canonical_subset`` share one action and carry it
    inside the value; their positions are increasing tuples indexing that
    action's domain.  The canonical image is the lexicographically least
    transported position tuple.  ``transporter`` is the lexicographically
    least array-form group element sending ``source_subset`` to
    ``canonical_subset``.  Deserialization checks their local structure only;
    exact group replay belongs to the explicit owner verifier.
    """

    source_subset: ActionBoundSubset = Field(
        description="Source subset in increasing action-domain position order."
    )
    canonical_subset: ActionBoundSubset = Field(
        description=(
            "Lexicographically least increasing position tuple among all "
            "images of source_subset under the generated group, bound to "
            "the source action."
        )
    )
    transporter: tuple[DomainPosition, ...] = Field(
        min_length=1,
        max_length=MAX_DOMAIN_SIZE,
        description=(
            "Lexicographically least generated-group permutation mapping "
            "source_subset exactly to canonical_subset."
        ),
    )
    orbit_size: int = Field(
        ge=1,
        le=MAX_GROUP_ORDER,
        description="Number of distinct images of source_subset under the group.",
    )
    stabilizer_size: int = Field(
        ge=1,
        le=MAX_GROUP_ORDER,
        description=(
            "Order of the subgroup fixing source_subset setwise; its product "
            "with orbit_size equals the generated group order."
        ),
    )

    @model_validator(mode="after")
    def bind_subset_canonicalization(self) -> Self:
        action = self.source_subset.action
        if self.canonical_subset.action != action:
            raise _validation_error(
                "canonical_subset_action_mismatch",
                "canonical_subset must be bound to the source action",
            )
        n = len(action.domain)
        if len(self.transporter) != n or sorted(self.transporter) != list(range(n)):
            raise _validation_error(
                "transporter_not_permutation",
                "transporter must be a permutation of the source action domain",
            )
        if (
            tuple(
                sorted(
                    self.transporter[position]
                    for position in self.source_subset.positions
                )
            )
            != self.canonical_subset.positions
        ):
            raise _validation_error(
                "transporter_mismatch",
                "transporter must map source_subset to canonical_subset",
            )
        if self.orbit_size * self.stabilizer_size > MAX_GROUP_ORDER:
            raise _validation_error(
                "orbit_stabilizer_product_exceeds_bound",
                "orbit_size * stabilizer_size must stay within the group-order bound",
            )
        return self

    @classmethod
    def _from_kernel(
        cls,
        source_subset: ActionBoundSubset,
        canonical_subset: ActionBoundSubset,
        transporter: tuple[int, ...],
        orbit_size: int,
        stabilizer_size: int,
    ) -> Self:
        return cls(
            source_subset=source_subset,
            canonical_subset=canonical_subset,
            transporter=transporter,
            orbit_size=orbit_size,
            stabilizer_size=stabilizer_size,
        )


# ---------------------------------------------------------------------------
# group_action.element_cycles.compute
# ---------------------------------------------------------------------------


class ElementCyclesRequest(_ActionRequest):
    """Request the cycle decomposition of one group element.

    ``element`` is the index (0-based) into the enumerated group order of the
    action; the identity element is always at index 0.
    """

    element: int = Field(ge=0)


class ElementCyclesResult(StrictModel):
    """Cycle decomposition of one group element acting on the domain.

    Each ``cycle`` is a tuple of 0-based position indices in the domain.  The
    canonical representative starts with the smallest index and cycles are
    ordered by their smallest element.  ``cycle_lengths`` is the sorted list
    of cycle lengths; ``cycle_type`` is the integer partition of ``|X|`` given
    by the cycle lengths in non-increasing order.  ``fixed_points`` lists the
    domain indices fixed by the element.
    """

    action: FinitePermutationAction
    element: int
    permutation: tuple[int, ...]
    cycles: tuple[tuple[int, ...], ...]
    cycle_lengths: tuple[int, ...]
    cycle_type: tuple[int, ...]
    fixed_points: tuple[int, ...]
    fixed_point_count: int
    support: tuple[int, ...]

    @model_validator(mode="after")
    def bind_element_cycles(self) -> Self:
        n = len(self.action.domain)
        if self.element < 0:
            raise _validation_error("element_negative", "element must be non-negative")
        if len(self.permutation) != n or sorted(self.permutation) != list(range(n)):
            raise _validation_error(
                "permutation_not_permutation",
                "permutation must be a permutation of the action domain",
            )
        flattened = tuple(position for cycle in self.cycles for position in cycle)
        if (
            not self.cycles
            or any(not cycle for cycle in self.cycles)
            or sorted(flattened) != list(range(n))
        ):
            raise _validation_error(
                "cycles_not_partition", "cycles must partition the action domain"
            )
        if any(
            self.permutation[position] != cycle[(index + 1) % len(cycle)]
            for cycle in self.cycles
            for index, position in enumerate(cycle)
        ):
            raise _validation_error(
                "cycles_not_permutation_cycles",
                "cycles must describe the claimed permutation",
            )
        lengths = tuple(sorted((len(cycle) for cycle in self.cycles), reverse=True))
        if self.cycle_lengths != lengths or self.cycle_type != lengths:
            raise _validation_error(
                "cycle_type_mismatch",
                "cycle lengths and cycle type must match the cycle decomposition",
            )
        fixed = tuple(
            position for position in range(n) if self.permutation[position] == position
        )
        if self.fixed_points != fixed or self.fixed_point_count != len(fixed):
            raise _validation_error(
                "fixed_point_count_mismatch",
                "fixed-point fields must match the claimed permutation",
            )
        support = tuple(
            position for position in range(n) if self.permutation[position] != position
        )
        if self.support != support:
            raise _validation_error(
                "support_mismatch", "support must match the claimed permutation"
            )
        return self

    @classmethod
    def _from_kernel(
        cls,
        action: FinitePermutationAction,
        element: int,
        permutation: tuple[int, ...],
        cycles: tuple[tuple[int, ...], ...],
        cycle_lengths: tuple[int, ...],
        cycle_type: tuple[int, ...],
        fixed_points: tuple[int, ...],
        support: tuple[int, ...],
    ) -> Self:
        return cls(
            action=action,
            element=element,
            permutation=permutation,
            cycles=cycles,
            cycle_lengths=cycle_lengths,
            cycle_type=cycle_type,
            fixed_points=fixed_points,
            fixed_point_count=len(fixed_points),
            support=support,
        )


# ---------------------------------------------------------------------------
# group_action.cycle_index.compute
# ---------------------------------------------------------------------------


class CycleIndexRequest(_ActionRequest):
    """Request the cycle-index polynomial of the action."""


class CycleIndexResult(StrictModel):
    """The cycle-index polynomial Z(G) as sparse coefficient data.

    ``cycle_type -> coefficient`` maps a cycle-type tuple (an integer partition
    of ``|X|`` given by cycle counts) to the number of group elements with
    that cycle type.  ``group_order`` is ``|G|`` and ``degree`` is ``|X|``.
    Each coefficient is exact; the cycle index is ``coeff / group_order``.
    """

    action: FinitePermutationAction
    group_order: int
    degree: int
    cycle_type_counts: tuple[tuple[tuple[int, ...], int], ...]

    @model_validator(mode="after")
    def bind_cycle_index(self) -> Self:
        if not 1 <= self.group_order <= MAX_GROUP_ORDER:
            raise _validation_error(
                "group_order_exceeds_bound",
                "group_order must stay within the group-order bound",
            )
        if self.degree != len(self.action.domain):
            raise _validation_error("degree_mismatch", "degree must equal |X|")
        if (
            not self.cycle_type_counts
            or tuple(sorted(self.cycle_type_counts)) != self.cycle_type_counts
        ):
            raise _validation_error(
                "cycle_type_counts_not_canonical",
                "cycle_type_counts must be a nonempty sorted tuple",
            )
        if len({cycle_type for cycle_type, _ in self.cycle_type_counts}) != len(
            self.cycle_type_counts
        ):
            raise _validation_error(
                "cycle_type_counts_duplicate", "cycle types must be unique"
            )
        if any(
            not cycle_type
            or any(part < 1 for part in cycle_type)
            or sum(cycle_type) != self.degree
            or count < 1
            for cycle_type, count in self.cycle_type_counts
        ):
            raise _validation_error(
                "cycle_type_counts_invalid",
                "each cycle type must partition degree with positive count",
            )
        if sum(count for _, count in self.cycle_type_counts) != self.group_order:
            raise _validation_error(
                "cycle_type_counts_total", "cycle-type counts must total group_order"
            )
        return self

    @classmethod
    def _from_kernel(
        cls,
        action: FinitePermutationAction,
        group_order: int,
        degree: int,
        cycle_type_counts: tuple[tuple[tuple[int, ...], int], ...],
    ) -> Self:
        return cls(
            action=action,
            group_order=group_order,
            degree=degree,
            cycle_type_counts=cycle_type_counts,
        )


# ---------------------------------------------------------------------------
# group_action.burnside_count.compute
# ---------------------------------------------------------------------------


class BurnsideCountRequest(_ActionRequest):
    """Request the number of orbits under the action via Burnside's lemma."""


class BurnsideCountResult(StrictModel):
    """The number of point-orbits under the action.

    ``orbit_count`` is the exact integer ``|G\\X| = (1/|G|) sum_g |Fix(g)|``.
    ``fixed_point_contributions`` lists, for each group element, its
    ``|Fix(g)|`` value in enumerated order.  ``group_order`` is ``|G|``.
    """

    action: FinitePermutationAction
    group_order: int
    fixed_point_sum: int
    orbit_count: int
    fixed_point_contributions: tuple[int, ...]

    @model_validator(mode="after")
    def bind_burnside(self) -> Self:
        if not 1 <= self.group_order <= MAX_GROUP_ORDER:
            raise _validation_error(
                "group_order_exceeds_bound",
                "group_order must stay within the group-order bound",
            )
        if len(self.fixed_point_contributions) != self.group_order or any(
            contribution < 0 or contribution > len(self.action.domain)
            for contribution in self.fixed_point_contributions
        ):
            raise _validation_error(
                "fixed_point_contributions_invalid",
                "fixed-point contributions must be bounded and one per group element",
            )
        if self.fixed_point_sum != sum(self.fixed_point_contributions):
            raise _validation_error(
                "fixed_point_sum_mismatch",
                "fixed_point_sum must equal the sum of contributions",
            )
        if (
            self.fixed_point_sum % self.group_order != 0
            or self.orbit_count != self.fixed_point_sum // self.group_order
        ):
            raise _validation_error(
                "orbit_count_mismatch",
                "orbit_count must be the integral Burnside average",
            )
        return self

    @classmethod
    def _from_kernel(
        cls,
        action: FinitePermutationAction,
        group_order: int,
        fixed_point_contributions: tuple[int, ...],
        orbit_count: int,
    ) -> Self:
        return cls(
            action=action,
            group_order=group_order,
            fixed_point_sum=sum(fixed_point_contributions),
            orbit_count=orbit_count,
            fixed_point_contributions=fixed_point_contributions,
        )


# ---------------------------------------------------------------------------
# group_action.polya_inventory.compute
# ---------------------------------------------------------------------------


class PolyaInventoryRequest(_ActionRequest):
    """Request the Pólya enumeration inventory polynomial.

    ``colors`` is the number of colours ``k``.  The inventory polynomial counts
    colouring orbits of ``X`` by colour multiplicity.  Its monomials are
    ``k``-tuples ``(e_1, ..., e_k)`` summing to ``|X|`` and its coefficients
    count orbits of colourings with exactly ``e_c`` points of colour ``c``.
    """

    colors: int = Field(ge=1, le=MAX_COLORS)


class PolyaInventoryResult(StrictModel):
    """The Pólya enumeration inventory polynomial as sparse data.

    ``terms`` maps each monomial exponent tuple (a ``k``-tuple of non-negative
    integers summing to ``degree``) to its integer coefficient.  ``colors`` is
    the number of colours and ``degree`` is ``|X|``.  The coefficient sum is
    ``k^|X| / |G| * |G| = k^|X|`` only when the action is trivial; in general
    the coefficients are the Pólya inventory coefficients.
    """

    action: FinitePermutationAction
    colors: int = Field(ge=1, le=MAX_COLORS)
    degree: int
    terms: tuple[tuple[tuple[int, ...], int], ...]

    @model_validator(mode="after")
    def bind_polya(self) -> Self:
        if self.degree != len(self.action.domain):
            raise _validation_error("degree_mismatch", "degree must equal |X|")
        if len(self.terms) > MAX_TERMS or tuple(sorted(self.terms)) != self.terms:
            raise _validation_error(
                "terms_not_canonical", "terms must be a bounded sorted tuple"
            )
        if len({monomial for monomial, _ in self.terms}) != len(self.terms):
            raise _validation_error("terms_duplicate", "monomials must be unique")
        if any(
            len(monomial) != self.colors
            or any(exponent < 0 for exponent in monomial)
            or sum(monomial) != self.degree
            or coefficient < 1
            for monomial, coefficient in self.terms
        ):
            raise _validation_error(
                "terms_invalid",
                "each term must be a positive coefficient on a degree monomial",
            )
        return self

    @classmethod
    def _from_kernel(
        cls,
        action: FinitePermutationAction,
        colors: int,
        degree: int,
        terms: tuple[tuple[tuple[int, ...], int], ...],
    ) -> Self:
        return cls(action=action, colors=colors, degree=degree, terms=terms)
