"""Typed wire contracts for finite group-action operations."""

from __future__ import annotations

from typing import Annotated, Self

from pydantic import Field, model_validator
from pydantic_core import PydanticCustomError

from jacobian._models import StrictModel

MAX_DOMAIN_SIZE = 50
MAX_GROUP_ORDER = 10000
MAX_GENERATORS = 50
MAX_LABEL_LENGTH = 64
MAX_COLORS = 50
MAX_TERMS = 5000


def _validation_error(reason: str, message: str) -> PydanticCustomError:
    """Build stable owner-local validation errors for finite actions."""

    return PydanticCustomError(f"finite_group_action.{reason}", message)


DomainPosition = Annotated[int, Field(ge=0, le=MAX_DOMAIN_SIZE - 1)]
FiniteActionSubset = Annotated[
    tuple[DomainPosition, ...],
    Field(max_length=MAX_DOMAIN_SIZE),
]


class FinitePermutationAction(StrictModel):
    """A finite permutation group acting on a labelled set.

    ``domain`` is the tuple of unique string labels for the set ``X`` being
    acted on.  ``generators`` is a tuple of permutations of ``{0, ..., n-1}``
    (each a tuple of length ``n`` where ``permutation[i]`` is the image of
    ``domain[i]``).  The group is generated by the generators under
    composition; the action convention is a left action.
    """

    domain: tuple[str, ...] = Field(min_length=1, max_length=MAX_DOMAIN_SIZE)
    generators: tuple[tuple[int, ...], ...] = Field(
        min_length=1,
        max_length=MAX_GENERATORS,
        description=(
            f"One to {MAX_GENERATORS} generator permutations in array form; "
            "each must have length equal to the domain size."
        ),
    )

    @model_validator(mode="after")
    def require_valid_action(self) -> Self:
        labels = set(self.domain)
        if len(labels) != len(self.domain):
            raise _validation_error(
                "domain_labels_not_distinct", "domain labels must be distinct"
            )
        for label in self.domain:
            if len(label) > MAX_LABEL_LENGTH:
                raise _validation_error(
                    "domain_label_too_long",
                    "domain label exceeds the bounded length budget",
                )
        n = len(self.domain)
        for perm in self.generators:
            if len(perm) != n:
                raise _validation_error(
                    "generator_length_mismatch",
                    "every generator must be a permutation of the domain",
                )
            if sorted(perm) != list(range(n)):
                raise _validation_error(
                    "generator_not_permutation",
                    "every generator must be a total permutation of the domain",
                )
        return self


def _canonical_subset_positions(
    action: FinitePermutationAction,
    subset: FiniteActionSubset,
) -> tuple[int, ...]:
    if len(set(subset)) != len(subset):
        raise _validation_error(
            "subset_positions_not_distinct", "subset positions must be distinct"
        )
    if any(position >= len(action.domain) for position in subset):
        raise _validation_error(
            "subset_position_out_of_range",
            "every subset position must index the action domain",
        )
    return tuple(sorted(subset))


def _generated_group_order(action: FinitePermutationAction) -> int:
    """Return the exact generated-group order without enumerating its elements."""
    from sympy.combinatorics import Permutation, PermutationGroup

    generators = [Permutation(list(generator)) for generator in action.generators]
    return int(PermutationGroup(generators).order())


class _ActionRequest(StrictModel):
    """Shared request shape: one finite permutation action."""

    action: FinitePermutationAction


# ---------------------------------------------------------------------------
# group_action.subset.canonicalize
# ---------------------------------------------------------------------------


class ActionBoundSubset(StrictModel):
    """A subset of the acted-on labelled set, bound to its permutation action.

    ``positions`` are distinct 0-based indices into ``action.domain``, so the
    value denotes the exact labelled subset
    ``{action.domain[position] for position in positions}``.  Because the
    action travels inside the value, serializing and reloading it cannot
    silently reinterpret the same positions under a different labelled
    domain.  Wire order is immaterial and is normalized to increasing domain
    position.
    """

    action: FinitePermutationAction
    positions: FiniteActionSubset = Field(
        description=(
            "Distinct 0-based positions in action.domain; input order is "
            "normalized to increasing domain position."
        )
    )

    @model_validator(mode="after")
    def bind_positions_to_domain(self) -> Self:
        object.__setattr__(
            self,
            "positions",
            _canonical_subset_positions(self.action, self.positions),
        )
        return self


class SubsetCanonicalizationRequest(StrictModel):
    """Request a canonical image of an action-bound subset under its action.

    The subset carries the action giving its positions meaning, so a dumped
    canonical result replays into this request as one unchanged canonical
    value.  The generated group must have order at most 10000; validation
    establishes that bound with SymPy's Schreier--Sims order computation
    before the kernel enumerates any group elements.
    """

    subset: ActionBoundSubset = Field(
        description=(
            "The subset to canonicalize, bound to its permutation action. "
            f"The generated group must have order at most {MAX_GROUP_ORDER}."
        )
    )

    @model_validator(mode="after")
    def bound_generated_group_order(self) -> Self:
        order = _generated_group_order(self.subset.action)
        if order > MAX_GROUP_ORDER:
            raise _validation_error(
                "group_order_exceeds_bound",
                f"group order {order} exceeds the bounded maximum {MAX_GROUP_ORDER}",
            )
        return self


class SubsetCanonicalizationResult(StrictModel):
    """Action-bound canonical subset image, transporter, and orbit--stabilizer data.

    ``source_subset`` and ``canonical_subset`` share one action and carry it
    inside the value; their positions are increasing tuples indexing that
    action's domain.  The canonical image is the lexicographically least
    transported position tuple.  ``transporter`` is the lexicographically
    least array-form group element sending ``source_subset`` to
    ``canonical_subset``.  The result is bound to its source by replaying
    those relations and ``orbit_size * stabilizer_size = |G|``.
    """

    source_subset: ActionBoundSubset = Field(
        description="Source subset in increasing action-domain position order."
    )
    canonical_subset: ActionBoundSubset = Field(
        description=(
            "Lexicographically least increasing position tuple among all "
            "images of source_subset under the generated group, bound to "
            "the source action."
        )
    )
    transporter: tuple[DomainPosition, ...] = Field(
        min_length=1,
        max_length=MAX_DOMAIN_SIZE,
        description=(
            "Lexicographically least generated-group permutation mapping "
            "source_subset exactly to canonical_subset."
        ),
    )
    orbit_size: int = Field(
        ge=1,
        le=MAX_GROUP_ORDER,
        description="Number of distinct images of source_subset under the group.",
    )
    stabilizer_size: int = Field(
        ge=1,
        le=MAX_GROUP_ORDER,
        description=(
            "Order of the subgroup fixing source_subset setwise; its product "
            "with orbit_size equals the generated group order."
        ),
    )

    @model_validator(mode="after")
    def bind_subset_canonicalization(self) -> Self:
        from jacobian.math.finite_group_actions._operations import (
            _subset_canonicalization_data,
        )

        action = self.source_subset.action
        if self.canonical_subset.action != action:
            raise _validation_error(
                "canonical_subset_action_mismatch",
                "canonical_subset must be bound to the source action",
            )
        canonical, transporter, orbit_size, stabilizer_size = (
            _subset_canonicalization_data(action, self.source_subset.positions)
        )
        if self.canonical_subset.positions != canonical:
            raise _validation_error(
                "canonical_subset_not_minimal",
                "canonical_subset must be the lexicographically least orbit image",
            )
        if self.transporter != transporter:
            raise _validation_error(
                "transporter_mismatch",
                "transporter must be the exact canonical generated-group witness",
            )
        if self.orbit_size != orbit_size:
            raise _validation_error(
                "orbit_size_mismatch",
                "orbit_size must equal the exact subset-orbit size",
            )
        if self.stabilizer_size != stabilizer_size:
            raise _validation_error(
                "stabilizer_size_mismatch",
                "stabilizer_size must equal the exact setwise-stabilizer order",
            )
        return self


# ---------------------------------------------------------------------------
# group_action.element_cycles.compute
# ---------------------------------------------------------------------------


class ElementCyclesRequest(_ActionRequest):
    """Request the cycle decomposition of one group element.

    ``element`` is the index (0-based) into the enumerated group order of the
    action; the identity element is always at index 0.
    """

    element: int = Field(ge=0)


class ElementCyclesResult(StrictModel):
    """Cycle decomposition of one group element acting on the domain.

    Each ``cycle`` is a tuple of 0-based position indices in the domain.  The
    canonical representative starts with the smallest index and cycles are
    ordered by their smallest element.  ``cycle_lengths`` is the sorted list
    of cycle lengths; ``cycle_type`` is the integer partition of ``|X|`` given
    by the cycle lengths in non-increasing order.  ``fixed_points`` lists the
    domain indices fixed by the element.
    """

    action: FinitePermutationAction
    element: int
    permutation: tuple[int, ...]
    cycles: tuple[tuple[int, ...], ...]
    cycle_lengths: tuple[int, ...]
    cycle_type: tuple[int, ...]
    fixed_points: tuple[int, ...]
    fixed_point_count: int
    support: tuple[int, ...]

    @model_validator(mode="after")
    def bind_element_cycles(self) -> Self:
        from jacobian.math.finite_group_actions._operations import _element_cycles_data

        permutation, cycles, lengths, cycle_type, fixed, support = _element_cycles_data(
            self.action, self.element
        )
        if self.permutation != permutation:
            raise _validation_error(
                "permutation_mismatch",
                "permutation must be the exact enumerated group element",
            )
        if self.cycles != cycles:
            raise _validation_error(
                "cycles_mismatch", "cycles must be the exact cycle decomposition"
            )
        if self.cycle_lengths != lengths:
            raise _validation_error(
                "cycle_lengths_mismatch",
                "cycle_lengths must match the computed cycle lengths",
            )
        if self.cycle_type != cycle_type:
            raise _validation_error(
                "cycle_type_mismatch", "cycle_type must be the integer partition of |X|"
            )
        if self.fixed_points != fixed:
            raise _validation_error(
                "fixed_points_mismatch",
                "fixed_points must be the exact fixed-point set",
            )
        if self.fixed_point_count != len(fixed):
            raise _validation_error(
                "fixed_point_count_mismatch",
                "fixed_point_count must equal len(fixed_points)",
            )
        if self.support != support:
            raise _validation_error(
                "support_mismatch", "support must be the exact support set"
            )
        return self


# ---------------------------------------------------------------------------
# group_action.cycle_index.compute
# ---------------------------------------------------------------------------


class CycleIndexRequest(_ActionRequest):
    """Request the cycle-index polynomial of the action."""


class CycleIndexResult(StrictModel):
    """The cycle-index polynomial Z(G) as sparse coefficient data.

    ``cycle_type -> coefficient`` maps a cycle-type tuple (an integer partition
    of ``|X|`` given by cycle counts) to the number of group elements with
    that cycle type.  ``group_order`` is ``|G|`` and ``degree`` is ``|X|``.
    Each coefficient is exact; the cycle index is ``coeff / group_order``.
    """

    action: FinitePermutationAction
    group_order: int
    degree: int
    cycle_type_counts: tuple[tuple[tuple[int, ...], int], ...]

    @model_validator(mode="after")
    def bind_cycle_index(self) -> Self:
        from jacobian.math.finite_group_actions._operations import _cycle_index_data

        order, degree, counts = _cycle_index_data(self.action)
        if self.group_order != order:
            raise _validation_error(
                "group_order_mismatch", "group_order must equal the exact |G|"
            )
        if self.degree != degree:
            raise _validation_error("degree_mismatch", "degree must equal |X|")
        if self.cycle_type_counts != counts:
            raise _validation_error(
                "cycle_type_counts_mismatch",
                "cycle_type_counts must be the exact cycle-type multiplicity table",
            )
        return self


# ---------------------------------------------------------------------------
# group_action.burnside_count.compute
# ---------------------------------------------------------------------------


class BurnsideCountRequest(_ActionRequest):
    """Request the number of orbits under the action via Burnside's lemma."""


class BurnsideCountResult(StrictModel):
    """The number of point-orbits under the action.

    ``orbit_count`` is the exact integer ``|G\\X| = (1/|G|) sum_g |Fix(g)|``.
    ``fixed_point_contributions`` lists, for each group element, its
    ``|Fix(g)|`` value in enumerated order.  ``group_order`` is ``|G|``.
    """

    action: FinitePermutationAction
    group_order: int
    fixed_point_sum: int
    orbit_count: int
    fixed_point_contributions: tuple[int, ...]

    @model_validator(mode="after")
    def bind_burnside(self) -> Self:
        from jacobian.math.finite_group_actions._operations import _burnside_data

        order, contributions, orbit_count = _burnside_data(self.action)
        if self.group_order != order:
            raise _validation_error(
                "group_order_mismatch", "group_order must equal the exact |G|"
            )
        if self.fixed_point_contributions != contributions:
            raise _validation_error(
                "fixed_point_contributions_mismatch",
                "fixed_point_contributions must be the exact |Fix(g)| table",
            )
        if self.fixed_point_sum != sum(contributions):
            raise _validation_error(
                "fixed_point_sum_mismatch",
                "fixed_point_sum must equal the sum of contributions",
            )
        if self.orbit_count != orbit_count:
            raise _validation_error(
                "orbit_count_mismatch",
                "orbit_count must equal the exact Burnside orbit count",
            )
        return self


# ---------------------------------------------------------------------------
# group_action.polya_inventory.compute
# ---------------------------------------------------------------------------


class PolyaInventoryRequest(_ActionRequest):
    """Request the Pólya enumeration inventory polynomial.

    ``colors`` is the number of colours ``k``.  The inventory polynomial counts
    colouring orbits of ``X`` by colour multiplicity.  Its monomials are
    ``k``-tuples ``(e_1, ..., e_k)`` summing to ``|X|`` and its coefficients
    count orbits of colourings with exactly ``e_c`` points of colour ``c``.
    """

    colors: int = Field(ge=1, le=MAX_COLORS)


class PolyaInventoryResult(StrictModel):
    """The Pólya enumeration inventory polynomial as sparse data.

    ``terms`` maps each monomial exponent tuple (a ``k``-tuple of non-negative
    integers summing to ``degree``) to its integer coefficient.  ``colors`` is
    the number of colours and ``degree`` is ``|X|``.  The coefficient sum is
    ``k^|X| / |G| * |G| = k^|X|`` only when the action is trivial; in general
    the coefficients are the Pólya inventory coefficients.
    """

    action: FinitePermutationAction
    colors: int = Field(ge=1, le=MAX_COLORS)
    degree: int
    terms: tuple[tuple[tuple[int, ...], int], ...]

    @model_validator(mode="after")
    def bind_polya(self) -> Self:
        from jacobian.math.finite_group_actions._operations import _polya_inventory_data

        degree, terms = _polya_inventory_data(self.action, self.colors)
        if self.degree != degree:
            raise _validation_error("degree_mismatch", "degree must equal |X|")
        if self.terms != terms:
            raise _validation_error(
                "terms_mismatch", "terms must be the exact Pólya inventory polynomial"
            )
        return self
