"""Exact bounded finite group-action operations."""

from __future__ import annotations

from jacobian.math.finite_group_actions._models import (
    MAX_GROUP_ORDER,
    ActionBoundSubset,
    BurnsideCountRequest,
    BurnsideCountResult,
    CycleIndexRequest,
    CycleIndexResult,
    ElementCyclesRequest,
    ElementCyclesResult,
    FinitePermutationAction,
    PolyaInventoryRequest,
    PolyaInventoryResult,
    SubsetCanonicalizationRequest,
    SubsetCanonicalizationResult,
)

CycleTypeCount = tuple[tuple[int, ...], int]


def _compose(a: tuple[int, ...], b: tuple[int, ...]) -> tuple[int, ...]:
    """Return ``a ∘ b`` so that ``(a ∘ b)[i] = a[b[i]]`` (left action)."""
    return tuple(a[b[i]] for i in range(len(a)))


def _identity(n: int) -> tuple[int, ...]:
    return tuple(range(n))


def _enumerate_group(
    action: FinitePermutationAction,
) -> tuple[tuple[int, ...], ...]:
    """Enumerate the group generated by the action's generators under composition.

    The identity element is always at index 0.  The remaining elements are
    ordered by first discovery in a breadth-first closure.  The group order
    must not exceed the bounded maximum.
    """

    n = len(action.domain)
    identity = _identity(n)
    seen: dict[tuple[int, ...], int] = {identity: 0}
    elements: list[tuple[int, ...]] = [identity]
    frontier: list[tuple[int, ...]] = [identity]
    while frontier:
        new_frontier: list[tuple[int, ...]] = []
        for elem in frontier:
            for gen in action.generators:
                composed = _compose(gen, elem)
                if composed not in seen:
                    seen[composed] = len(elements)
                    elements.append(composed)
                    new_frontier.append(composed)
                    if len(elements) > MAX_GROUP_ORDER:
                        raise ValueError(
                            f"group order exceeds the bounded maximum {MAX_GROUP_ORDER}"
                        )
        frontier = new_frontier
    return tuple(elements)


def _transport_subset(
    permutation: tuple[int, ...],
    subset: tuple[int, ...],
) -> tuple[int, ...]:
    return tuple(sorted(permutation[position] for position in subset))


def _subset_canonicalization_data(
    action: FinitePermutationAction,
    source_subset: tuple[int, ...],
) -> tuple[tuple[int, ...], tuple[int, ...], int, int]:
    """Return canonical image, transporter, orbit size, and stabilizer size."""
    group = _enumerate_group(action)
    image_transporters: dict[tuple[int, ...], tuple[int, ...]] = {}
    stabilizer_size = 0
    for permutation in group:
        image = _transport_subset(permutation, source_subset)
        previous = image_transporters.get(image)
        if previous is None or permutation < previous:
            image_transporters[image] = permutation
        if image == source_subset:
            stabilizer_size += 1

    canonical_subset = min(image_transporters)
    transporter = image_transporters[canonical_subset]
    orbit_size = len(image_transporters)
    if orbit_size * stabilizer_size != len(group):
        raise ValueError("subset orbit and stabilizer sizes violate orbit-stabilizer")
    return canonical_subset, transporter, orbit_size, stabilizer_size


def _cycle_decomposition(
    perm: tuple[int, ...],
) -> tuple[
    tuple[tuple[int, ...], ...], tuple[int, ...], tuple[int, ...], tuple[int, ...]
]:
    """Return ``(cycles, lengths, cycle_type, fixed)`` for one permutation.

    Cycles use the canonical representative starting with the smallest index
    and are ordered by their smallest element.  Fixed points are cycles of
    length 1.  ``cycle_type`` is the integer partition of ``n`` given by cycle
    lengths in non-increasing order.  ``fixed`` lists fixed-point indices in
    increasing order.
    """
    n = len(perm)
    visited = [False] * n
    cycles: list[tuple[int, ...]] = []
    for start in range(n):
        if visited[start]:
            continue
        cycle: list[int] = []
        current = start
        while not visited[current]:
            visited[current] = True
            cycle.append(current)
            current = perm[current]
        cycles.append(tuple(cycle))
    # Canonical: order cycles by smallest element, rotate each to start there.
    cycles.sort(key=lambda c: min(c))
    lengths = tuple(sorted((len(c) for c in cycles), reverse=True))
    fixed = tuple(i for i in range(n) if perm[i] == i)
    return tuple(cycles), lengths, lengths, fixed


def _support(perm: tuple[int, ...]) -> tuple[int, ...]:
    return tuple(i for i in range(len(perm)) if perm[i] != i)


def _element_cycles_data(
    action: FinitePermutationAction,
    element: int,
) -> tuple[
    tuple[int, ...],
    tuple[tuple[int, ...], ...],
    tuple[int, ...],
    tuple[int, ...],
    tuple[int, ...],
    tuple[int, ...],
]:
    group = _enumerate_group(action)
    if element < 0 or element >= len(group):
        raise ValueError("element index is out of range for the group order")
    perm = group[element]
    cycles, lengths, cycle_type, fixed = _cycle_decomposition(perm)
    support = _support(perm)
    return perm, cycles, lengths, cycle_type, fixed, support


def _cycle_type_counts(
    action: FinitePermutationAction,
) -> tuple[CycleTypeCount, ...]:
    """Return the cycle-type multiplicity table as a sorted tuple of (type, count)."""
    group = _enumerate_group(action)
    counts: dict[tuple[int, ...], int] = {}
    for perm in group:
        _, _, cycle_type, _ = _cycle_decomposition(perm)
        counts[cycle_type] = counts.get(cycle_type, 0) + 1
    return tuple(sorted(counts.items()))


def _cycle_index_data(
    action: FinitePermutationAction,
) -> tuple[int, int, tuple[CycleTypeCount, ...]]:
    """Return ``(group_order, degree, cycle_type_counts)``."""
    group = _enumerate_group(action)
    degree = len(action.domain)
    counts = _cycle_type_counts(action)
    return len(group), degree, counts


def _burnside_data(
    action: FinitePermutationAction,
) -> tuple[int, tuple[int, ...], int]:
    """Return ``(group_order, fixed_point_contributions, orbit_count)``."""
    group = _enumerate_group(action)
    contributions: list[int] = []
    for perm in group:
        _, _, _, fixed = _cycle_decomposition(perm)
        contributions.append(len(fixed))
    group_order = len(group)
    total = sum(contributions)
    if total % group_order != 0:
        raise ValueError("Burnside orbit count is not an integer")
    orbit_count = total // group_order
    return group_order, tuple(contributions), orbit_count


def _polya_inventory_data(
    action: FinitePermutationAction,
    colors: int,
) -> tuple[int, tuple[tuple[tuple[int, ...], int], ...]]:
    """Return ``(degree, terms)`` for the Pólya inventory polynomial.

    For a colouring ``X -> {1..k}``, each group element ``g`` contributes
    ``prod_i a_i^{c_i(g)}`` to the cycle index.  Substituting
    ``a_i <- sum_c y_c^i`` and expanding gives the inventory polynomial whose
    monomials are exponent tuples of length ``colors`` and coefficients count
    colouring orbits by colour multiplicity.
    """
    group = _enumerate_group(action)
    degree = len(action.domain)
    if colors < 1:
        raise ValueError("colors must be at least 1")
    orbit_count: dict[tuple[int, ...], int] = {}
    for perm in group:
        cycles, _, _, _ = _cycle_decomposition(perm)
        # Build the monomial exponent-tuple contribution of this element.
        # cycle of length i contributes sum_c y_c^i, so for each monomial we
        # choose one term per cycle.  Accumulate the product over cycles.
        # Each cycle of length L contributes (y_c)^L for some colour c.
        # We represent each cycle's choice as an exponent vector of length
        # colors, where entry c is L if that colour is chosen.
        cycle_choices: list[list[tuple[int, ...]]] = []
        for cycle in cycles:
            length = len(cycle)
            choices = []
            for c in range(colors):
                exponents = [0] * colors
                exponents[c] = length
                choices.append(tuple(exponents))
            cycle_choices.append(choices)
        # Cartesian product over cycles
        from itertools import product as _product

        for assignment in _product(*cycle_choices):
            monomial = tuple(
                sum(assignment[j][c] for j in range(len(assignment)))
                for c in range(colors)
            )
            orbit_count[monomial] = orbit_count.get(monomial, 0) + 1
    group_order = len(group)
    terms: list[tuple[tuple[int, ...], int]] = []
    for monomial, count in orbit_count.items():
        if count % group_order != 0:
            raise ValueError("Pólya inventory coefficient is not an integer")
        terms.append((monomial, count // group_order))
    terms.sort(key=lambda t: t[0])
    return degree, tuple(terms)


def compute_element_cycles(
    request: ElementCyclesRequest,
) -> ElementCyclesResult:
    """Compute the cycle decomposition of one group element."""
    perm, cycles, lengths, cycle_type, fixed, support = _element_cycles_data(
        request.action, request.element
    )
    return ElementCyclesResult._from_kernel(
        request.action,
        request.element,
        perm,
        cycles,
        lengths,
        cycle_type,
        fixed,
        support,
    )


def compute_subset_canonicalization(
    request: SubsetCanonicalizationRequest,
) -> SubsetCanonicalizationResult:
    """Canonicalize one action-bound subset under its permutation action."""
    action = request.subset.action
    canonical, transporter, orbit_size, stabilizer_size = _subset_canonicalization_data(
        action, request.subset.positions
    )
    return SubsetCanonicalizationResult._from_kernel(
        request.subset,
        ActionBoundSubset(action=action, positions=canonical),
        transporter,
        orbit_size,
        stabilizer_size,
    )


def compute_cycle_index(request: CycleIndexRequest) -> CycleIndexResult:
    """Compute the cycle-index polynomial of the action."""
    group_order, degree, counts = _cycle_index_data(request.action)
    return CycleIndexResult._from_kernel(request.action, group_order, degree, counts)


def compute_burnside_count(request: BurnsideCountRequest) -> BurnsideCountResult:
    """Compute the number of orbits under the action via Burnside's lemma."""
    group_order, contributions, orbit_count = _burnside_data(request.action)
    return BurnsideCountResult._from_kernel(
        request.action, group_order, contributions, orbit_count
    )


def compute_polya_inventory(request: PolyaInventoryRequest) -> PolyaInventoryResult:
    """Compute the Pólya enumeration inventory polynomial."""
    degree, terms = _polya_inventory_data(request.action, request.colors)
    return PolyaInventoryResult._from_kernel(
        request.action, request.colors, degree, terms
    )


def verify_subset_canonicalization_result(
    result: SubsetCanonicalizationResult,
) -> bool:
    """Replay one independently supplied subset-canonicalization claim."""
    try:
        canonical, transporter, orbit_size, stabilizer_size = (
            _subset_canonicalization_data(
                result.source_subset.action, result.source_subset.positions
            )
        )
    except ValueError:
        return False
    return (
        result.canonical_subset.positions == canonical
        and result.transporter == transporter
        and result.orbit_size == orbit_size
        and result.stabilizer_size == stabilizer_size
    )


def verify_element_cycles_result(result: ElementCyclesResult) -> bool:
    """Replay one independently supplied element-cycle claim."""
    try:
        expected = _element_cycles_data(result.action, result.element)
    except ValueError:
        return False
    return expected == (
        result.permutation,
        result.cycles,
        result.cycle_lengths,
        result.cycle_type,
        result.fixed_points,
        result.support,
    )


def verify_cycle_index_result(result: CycleIndexResult) -> bool:
    """Replay one independently supplied cycle-index claim."""
    try:
        return _cycle_index_data(result.action) == (
            result.group_order,
            result.degree,
            result.cycle_type_counts,
        )
    except ValueError:
        return False


def verify_burnside_count_result(result: BurnsideCountResult) -> bool:
    """Replay one independently supplied Burnside-count claim."""
    try:
        group_order, contributions, orbit_count = _burnside_data(result.action)
    except ValueError:
        return False
    return (
        result.group_order == group_order
        and result.fixed_point_contributions == contributions
        and result.fixed_point_sum == sum(contributions)
        and result.orbit_count == orbit_count
    )


def verify_polya_inventory_result(result: PolyaInventoryResult) -> bool:
    """Replay one independently supplied Pólya inventory claim."""
    try:
        return _polya_inventory_data(result.action, result.colors) == (
            result.degree,
            result.terms,
        )
    except ValueError:
        return False


__all__ = [
    "compute_burnside_count",
    "compute_cycle_index",
    "compute_element_cycles",
    "compute_polya_inventory",
    "compute_subset_canonicalization",
    "verify_burnside_count_result",
    "verify_cycle_index_result",
    "verify_element_cycles_result",
    "verify_polya_inventory_result",
    "verify_subset_canonicalization_result",
]
