"""Native-value mathematical APIs supported by Jacobian."""

from jacobian.math import (
    algebraic_combinatorics,
    arithmetic,
    arithmetic_dynamics,
    combinatorics,
    diophantine_approximation,
    finite_abelian_groups,
    finite_fields,
    finite_metric_spaces,
    finite_state_transducers,
    formal_power_series,
    graphical_models,
    graphs,
    impartial_games,
    matrices,
    numerical_semigroups,
    petri_nets,
    polynomials,
    prime_field_linear_algebra,
    probability,
    regular_languages,
    term_rewriting,
    tree_automata,
    words,
)

__all__ = [
    "algebraic_combinatorics",
    "arithmetic",
    "arithmetic_dynamics",
    "combinatorics",
    "diophantine_approximation",
    "finite_abelian_groups",
    "finite_fields",
    "finite_metric_spaces",
    "finite_state_transducers",
    "formal_power_series",
    "graphical_models",
    "graphs",
    "impartial_games",
    "matrices",
    "numerical_semigroups",
    "petri_nets",
    "polynomials",
    "prime_field_linear_algebra",
    "probability",
    "regular_languages",
    "term_rewriting",
    "tree_automata",
    "words",
]
