"""Native mathematical APIs supported by Jacobian."""

from jacobian.math import (
    analysis,
    cluster_algebras,
    coalgebras,
    combinatorics,
    crossed_products,
    dynamics,
    finite_categories,
    finite_dim_algebras,
    finite_fields,
    finite_semigroups,
    geometry,
    graphs,
    groups,
    lattices,
    logic,
    matrices,
    number_theory,
    optimization,
    polynomials,
    probability,
    topology,
    universal_algebra,
)

__all__ = [
    "analysis",
    "cluster_algebras",
    "coalgebras",
    "combinatorics",
    "crossed_products",
    "dynamics",
    "finite_categories",
    "finite_dim_algebras",
    "finite_fields",
    "finite_semigroups",
    "geometry",
    "graphs",
    "groups",
    "lattices",
    "logic",
    "matrices",
    "number_theory",
    "optimization",
    "polynomials",
    "probability",
    "topology",
    "universal_algebra",
]
