"""Exact rational polytope values and native operations."""

from jacobian.math.geometry.polytopes._models import (
    EdgeProfileResult,
    JoinResult,
    JoinVertexMap,
    PolytopeEdge,
    PolytopeSupportResult,
    PrismResult,
    PrismVertexMap,
    PyramidBaseVertexMap,
    PyramidResult,
    RationalCoordinateSpace,
    RationalCovector,
    RationalExposedFace,
    RationalPolytopeVertex,
    RationalVPolytope,
    VertexFigurePolytope,
    VertexFigureResult,
    VertexFigureVertexMap,
)
from jacobian.math.geometry.polytopes.operations import (
    convex_hull_volume,
    polytope_edge_profile,
    polytope_join,
    polytope_prism,
    polytope_pyramid,
    polytope_support,
    polytope_vertex_figure,
    verify_facet_incidence,
    verify_primitive_facet,
)
from jacobian.math.geometry.polytopes.polyhedron_conversion import (
    halfspaces_to_v_presentation,
)
from jacobian.math.geometry.polytopes.values import (
    Halfspace,
    RationalAffineHalfspace,
    RationalHPolyhedron,
    RationalPolyhedronSpace,
    RationalPolyhedronVPresentation,
    Vertex,
)

__all__ = [
    "EdgeProfileResult",
    "Halfspace",
    "JoinResult",
    "JoinVertexMap",
    "PolytopeEdge",
    "PolytopeSupportResult",
    "PrismResult",
    "PrismVertexMap",
    "PyramidBaseVertexMap",
    "PyramidResult",
    "RationalAffineHalfspace",
    "RationalCoordinateSpace",
    "RationalCovector",
    "RationalExposedFace",
    "RationalHPolyhedron",
    "RationalPolyhedronSpace",
    "RationalPolyhedronVPresentation",
    "RationalPolytopeVertex",
    "RationalVPolytope",
    "Vertex",
    "VertexFigurePolytope",
    "VertexFigureResult",
    "VertexFigureVertexMap",
    "convex_hull_volume",
    "halfspaces_to_v_presentation",
    "polytope_edge_profile",
    "polytope_join",
    "polytope_prism",
    "polytope_pyramid",
    "polytope_support",
    "polytope_vertex_figure",
    "verify_facet_incidence",
    "verify_primitive_facet",
]
