"""Exact image lattices of bounded integer generator configurations."""

from __future__ import annotations

from jacobian._models import StrictModel
from jacobian.catalog.models import OperationDomainValidationError
from jacobian.math.affine_semigroups.semigroup import AffineConfiguration
from jacobian.math.lattices._models import IntegerLattice
from jacobian.math.lattices.operations import hermite_normal_form
from jacobian.math.matrices.values import IntegerMatrix


class AffineGroupLattice(StrictModel):
    """The subgroup of the ambient integer lattice generated by ``A``."""

    configuration: AffineConfiguration
    lattice: IntegerLattice


def compute_group_lattice(configuration: AffineConfiguration) -> AffineGroupLattice:
    """Return the canonical row-HNF basis of the column lattice ``Z A``."""

    if type(configuration) is not AffineConfiguration:
        raise OperationDomainValidationError(
            location=("configuration",),
            code="affine_semigroup.configuration",
            message="configuration must be a canonical affine configuration",
        )
    try:
        config = AffineConfiguration.model_validate(
            configuration.model_dump(mode="python")
        )
    except Exception as exc:
        raise OperationDomainValidationError(
            location=("configuration",),
            code="affine_semigroup.configuration",
            message="configuration is malformed",
        ) from exc

    generators = [
        [config.entries[row][column] for row in range(config.rows)]
        for column in range(config.columns)
    ]
    basis, _ = hermite_normal_form(generators)
    basis_rows = tuple(
        row_values
        for row_values in (
            tuple(int(basis[row, column]) for column in range(basis.ncols()))
            for row in range(basis.nrows())
        )
        if any(row_values)
    )
    basis_matrix = IntegerMatrix(
        row_count=len(basis_rows),
        column_count=config.rows,
        entries=basis_rows,
    )
    lattice = IntegerLattice(ambient_dimension=config.rows, basis=basis_matrix)
    return AffineGroupLattice(configuration=config, lattice=lattice)


__all__ = ["AffineGroupLattice", "compute_group_lattice"]
