from jacobian.catalog.models import (
    MathTool,
    OperationDomainValidationError,
    OperationExample,
    OperationResourceAdmissionError,
)
from jacobian.math.affine_semigroups.semigroup import (
    AffineFiber,
    AffineMembershipResult,
    PositiveAffineSemigroup,
    PositiveGradingResult,
    construct,
    fiber,
    membership,
    positive_grading,
)
from jacobian.math.affine_semigroups.semigroup_models import (
    AffineFiberRequest,
    AffineMembershipRequest,
    AffineSemigroupRequest,
    PositiveGradingRequest,
)


def _grading(r: PositiveGradingRequest) -> PositiveGradingResult:
    try:
        return positive_grading(r.configuration)
    except OperationResourceAdmissionError:
        raise
    except ValueError as e:
        raise OperationDomainValidationError(
            location=("configuration",), code="affine_semigroup.grading", message=str(e)
        ) from e


def _construct(r: AffineSemigroupRequest) -> PositiveAffineSemigroup:
    try:
        return construct(r.configuration, r.grading)
    except ValueError as e:
        raise OperationDomainValidationError(
            location=("grading",), code="affine_semigroup.grading", message=str(e)
        ) from e


def _fiber(r: AffineFiberRequest) -> AffineFiber:
    try:
        return fiber(r.semigroup, r.target)
    except OperationResourceAdmissionError:
        raise
    except (TypeError, ValueError, IndexError, OverflowError) as e:
        raise OperationDomainValidationError(
            location=("target",), code="affine_semigroup.fiber", message=str(e)
        ) from e


def _membership(r: AffineMembershipRequest) -> AffineMembershipResult:
    try:
        return membership(r.semigroup, r.target)
    except OperationResourceAdmissionError:
        raise
    except (TypeError, ValueError, IndexError, OverflowError) as e:
        raise OperationDomainValidationError(
            location=("target",), code="affine_semigroup.membership", message=str(e)
        ) from e


TOOLS = (
    MathTool(
        operation_id="integer_configuration.positive_grading.compute",
        title="Find an exact positive grading",
        description="Find an exact rational covector positive on every labelled generator; bounded search exhaustion is an admission failure, not a nonmembership claim.",
        request_type=PositiveGradingRequest,
        result_type=PositiveGradingResult,
        run=_grading,
        tags=("affine-semigroup", "grading", "exact"),
        examples=(
            OperationExample(
                name="positive_ray",
                description="Find a positive grading for generators (1,0) and (0,1).",
                input={
                    "configuration": {
                        "row_labels": ["x", "y"],
                        "generator_labels": ["a", "b"],
                        "entries": [["1", "0"], ["0", "1"]],
                    }
                },
            ),
        ),
    ),
    MathTool(
        operation_id="affine_semigroup.from_generators.compute",
        title="Construct a positive affine semigroup",
        description="Construct the canonical positive affine semigroup from labelled integer generators and an exact positive grading.",
        request_type=AffineSemigroupRequest,
        result_type=PositiveAffineSemigroup,
        run=_construct,
        tags=("affine-semigroup", "exact"),
        examples=(
            OperationExample(
                name="quadrant",
                description="Construct the positive semigroup generated by (1,0),(0,1); the grading must be positive on both generators.",
                input={
                    "configuration": {
                        "row_labels": ["x", "y"],
                        "generator_labels": ["a", "b"],
                        "entries": [["1", "0"], ["0", "1"]],
                    },
                    "grading": [{"num": "1", "den": "1"}, {"num": "1", "den": "1"}],
                },
            ),
        ),
    ),
    MathTool(
        operation_id="affine_semigroup.factorizations.compute",
        title="Compute a complete affine-semigroup fiber",
        description="Return every nonnegative integer factorization Au=b for one positive labelled affine semigroup.",
        request_type=AffineFiberRequest,
        result_type=AffineFiber,
        run=_fiber,
        tags=("affine-semigroup", "fiber", "exact"),
        examples=(
            OperationExample(
                name="fiber_2",
                description="Compute all factorizations of (2,0) in the quadrant semigroup; the target uses the labelled row axis.",
                input={
                    "semigroup": {
                        "configuration": {
                            "row_labels": ["x", "y"],
                            "generator_labels": ["a", "b"],
                            "entries": [["1", "0"], ["0", "1"]],
                        },
                        "grading": [{"num": "1", "den": "1"}, {"num": "1", "den": "1"}],
                    },
                    "target": ["2", "0"],
                },
            ),
        ),
    ),
    MathTool(
        operation_id="affine_semigroup.membership.compute",
        title="Classify affine-semigroup membership",
        description="Distinguish exact cone, ambient lattice, and nonnegative semigroup membership and return a factorization when present.",
        request_type=AffineMembershipRequest,
        result_type=AffineMembershipResult,
        run=_membership,
        tags=("affine-semigroup", "membership", "exact"),
        examples=(
            OperationExample(
                name="member",
                description="Classify (2,1) in the quadrant semigroup; the target uses the labelled row axis.",
                input={
                    "semigroup": {
                        "configuration": {
                            "row_labels": ["x", "y"],
                            "generator_labels": ["a", "b"],
                            "entries": [["1", "0"], ["0", "1"]],
                        },
                        "grading": [{"num": "1", "den": "1"}, {"num": "1", "den": "1"}],
                    },
                    "target": ["2", "1"],
                },
            ),
        ),
    ),
)
__all__ = ["TOOLS"]
