"""Supported native exact finite-incidence APIs."""

from jacobian.math.combinatorics.designs.incidence_structures._models import (
    ComputedSteinerTripleSystem,
    ContainmentProfileResult,
    IncidenceMomentComparison,
    IncidenceStructure,
    IncidenceTradeResult,
    SteinerTripleSystemNotFound,
    SteinerTripleSystemOutcome,
    SteinerTripleSystemRequest,
    SteinerTripleSystemResult,
    SteinerTripleSystemShard,
    SteinerTripleSystemUnknown,
)
from jacobian.math.combinatorics.designs.incidence_structures.operations import (
    check_incidence_trade,
    complement,
    construct_steiner_triple_system,
    containment_profile,
    degree_profile,
    derived_residual,
    dual,
    gram,
    incidence_matrix,
    intersections,
    levi_graph,
    restriction,
)

__all__ = [
    "ComputedSteinerTripleSystem",
    "ContainmentProfileResult",
    "IncidenceMomentComparison",
    "IncidenceStructure",
    "IncidenceTradeResult",
    "SteinerTripleSystemNotFound",
    "SteinerTripleSystemOutcome",
    "SteinerTripleSystemRequest",
    "SteinerTripleSystemResult",
    "SteinerTripleSystemShard",
    "SteinerTripleSystemUnknown",
    "check_incidence_trade",
    "complement",
    "construct_steiner_triple_system",
    "containment_profile",
    "degree_profile",
    "derived_residual",
    "dual",
    "gram",
    "incidence_matrix",
    "intersections",
    "levi_graph",
    "restriction",
]
