"""Exact finite relational structures with homomorphism check and search."""

from jacobian.math.logic.relational_structures._models import (
    CspAssignmentProfile,
    CspSolutions,
    CspConstraintEvaluation,
    EmbeddingSearchResult,
    FiniteCspConstraint,
    FiniteCspInstance,
    HomomorphismCheckResult,
    HomomorphismCoreResult,
    HomomorphismCountResult,
    HomomorphismEnumerationResult,
    HomomorphismSearchResult,
    HomomorphismSearchStatus,
    HomomorphismStatus,
    HomomorphismViolationWitness,
    InducedEmbeddingCheckResult,
    InducedRelationProfile,
    InducedSubstructureResult,
    RelationalDisjointUnionResult,
    RelationalPolymorphism,
    RelationalPolymorphismCheckResult,
    RelationalPolymorphismRelationProfile,
    RelationalPolymorphismStatus,
    RelationalPolymorphismWitness,
    RelationalQuotient,
    RelationalReductResult,
    SymbolTransportProfile,
)
from jacobian.math.logic.relational_structures.operations import (
    check_homomorphism,
    check_polymorphism,
    compose_homomorphisms,
    compute_core,
    count_homomorphisms,
    csp_instance_to_source_structure,
    disjoint_union_structure,
    enumerate_csp_solutions,
    enumerate_homomorphisms,
    homomorphism_identity,
    induced_substructure,
    profile_csp_assignment,
    quotient_structure,
    reduct_structure,
    search_embedding,
    search_homomorphism,
    transpose_binary_relation,
)
from jacobian.math.logic.relational_structures.values import (
    FiniteRelationalStructure,
    FiniteRelationSymbol,
    RelationalCarrierMap,
    RelationalHomomorphism,
)

# The authoritative native surface: every export accepts domain values
# directly. Wire-envelope request handlers live in ``_tools.py`` and are not
# part of this native API.
__all__ = [
    "CspAssignmentProfile",
    "CspSolutions",
    "CspConstraintEvaluation",
    "EmbeddingSearchResult",
    "FiniteCspConstraint",
    "FiniteCspInstance",
    "FiniteRelationSymbol",
    "FiniteRelationalStructure",
    "HomomorphismCheckResult",
    "HomomorphismCoreResult",
    "HomomorphismCountResult",
    "HomomorphismEnumerationResult",
    "HomomorphismSearchResult",
    "HomomorphismSearchStatus",
    "HomomorphismStatus",
    "HomomorphismViolationWitness",
    "InducedEmbeddingCheckResult",
    "InducedRelationProfile",
    "InducedSubstructureResult",
    "RelationalDisjointUnionResult",
    "RelationalCarrierMap",
    "RelationalHomomorphism",
    "RelationalPolymorphism",
    "RelationalPolymorphismCheckResult",
    "RelationalPolymorphismRelationProfile",
    "RelationalPolymorphismStatus",
    "RelationalPolymorphismWitness",
    "RelationalQuotient",
    "RelationalReductResult",
    "SymbolTransportProfile",
    "check_homomorphism",
    "check_polymorphism",
    "compose_homomorphisms",
    "compute_core",
    "count_homomorphisms",
    "csp_instance_to_source_structure",
    "disjoint_union_structure",
    "enumerate_csp_solutions",
    "enumerate_homomorphisms",
    "homomorphism_identity",
    "induced_substructure",
    "profile_csp_assignment",
    "quotient_structure",
    "reduct_structure",
    "search_embedding",
    "search_homomorphism",
    "transpose_binary_relation",
]
