"""Exact bounded native APIs for finite-state transducers."""

from jacobian.math.logic.automata.transducers.operations import (
    coaccessible_states,
    compose_subsequential,
    identity_transducer,
    invert_rational,
    minimize_subsequential,
    project_rational_relation,
    rational_relation_outputs_for_input,
    reachable_state_witnesses,
    reachable_states,
    replay_rational_path,
    run_subsequential,
    trim_subsequential,
    verify_composition,
    verify_minimization,
    verify_subsequential_run,
    word_morphism_to_subsequential,
)
from jacobian.math.logic.automata.transducers.values import (
    FiniteAlphabet,
    RationalEdge,
    RationalTransducer,
    SubseqFinalOutput,
    SubseqTransition,
    SubsequentialTransducer,
)

__all__ = [
    "FiniteAlphabet",
    "RationalEdge",
    "RationalTransducer",
    "SubseqFinalOutput",
    "SubseqTransition",
    "SubsequentialTransducer",
    "coaccessible_states",
    "compose_subsequential",
    "identity_transducer",
    "invert_rational",
    "minimize_subsequential",
    "project_rational_relation",
    "rational_relation_outputs_for_input",
    "reachable_state_witnesses",
    "reachable_states",
    "replay_rational_path",
    "run_subsequential",
    "trim_subsequential",
    "verify_composition",
    "verify_minimization",
    "verify_subsequential_run",
    "word_morphism_to_subsequential",
]
