"""Exact coding theory kernels over prime fields."""

from __future__ import annotations

__all__ = ["parity_check_matrix", "puncture_code", "shorten_code"]


def _row_reduce(
    rows: list[list[int]], n_cols: int, field_order: int
) -> list[list[int]]:
    """Gaussian elimination, returns RREF."""
    mat = [list(row) for row in rows]
    n_rows = len(mat)
    pivot_row = 0
    for col in range(n_cols):
        pivot = next(
            (i for i in range(pivot_row, n_rows) if mat[i][col] % field_order != 0),
            None,
        )
        if pivot is None:
            continue
        mat[pivot_row], mat[pivot] = mat[pivot], mat[pivot_row]
        inv = pow(int(mat[pivot_row][col]) % field_order, -1, field_order)
        mat[pivot_row] = [(v * inv) % field_order for v in mat[pivot_row]]
        for i in range(n_rows):
            if i == pivot_row:
                continue
            factor = int(mat[i][col]) % field_order
            if factor == 0:
                continue
            mat[i] = [
                (mat[i][j] - factor * mat[pivot_row][j]) % field_order
                for j in range(n_cols)
            ]
        pivot_row += 1
        if pivot_row == n_rows:
            break
    return mat


def parity_check_matrix(
    generator: list[list[int]], field_order: int
) -> list[list[int]]:
    """Compute the parity-check matrix H from a generator matrix G.

    H is the nullspace of G over GF(field_order).
    Returns rows of H such that G * H^T = 0.
    """
    n_rows = len(generator)
    n_cols = len(generator[0])
    rref = _row_reduce(generator, n_cols, field_order)
    rank = sum(1 for row in rref if any(v % field_order != 0 for v in row))

    # The nullspace has dimension n_cols - rank
    # We find the nullspace by solving G * x = 0
    # Using the RREF, identify pivot and free columns
    pivot_cols = []
    free_cols = []
    current_pivot_row = 0
    for col in range(n_cols):
        found = False
        for i in range(current_pivot_row, min(rank, n_rows)):
            if rref[i][col] % field_order != 0:
                pivot_cols.append(col)
                current_pivot_row = i + 1
                found = True
                break
        if not found:
            free_cols.append(col)

    # Build nullspace basis vectors
    nullspace = []
    for free_col in free_cols:
        vec = [0] * n_cols
        vec[free_col] = 1
        for i, pc in enumerate(pivot_cols):
            if i < len(rref):
                vec[pc] = (-rref[i][free_col]) % field_order
        nullspace.append(vec)

    return nullspace


def puncture_code(
    generator: list[list[int]], field_order: int, position: int
) -> list[list[int]]:
    """Puncture a code by deleting one coordinate column."""
    return [[row[j] for j in range(len(row)) if j != position] for row in generator]


def shorten_code(
    generator: list[list[int]], field_order: int, position: int, value: int
) -> list[list[int]]:
    """Shorten a code by fixing one coordinate to a value and deleting it.

    This selects codewords with the given value at the position,
    then punctures at that position.
    """
    # Select rows whose codeword has value at position
    # But we work with generator rows, not individual codewords.
    # For shortening, we find the subcode generated by rows
    # whose codeword has the given value at position.
    # This is equivalent to: find a linear combination of generator rows
    # that gives value at position, then subtract that from all rows,
    # and keep only rows that are zero at position.

    n_rows = len(generator)
    n_cols = len(generator[0])

    # Find a row that has nonzero at position
    pivot_row = None
    for i in range(n_rows):
        if generator[i][position] % field_order != 0:
            pivot_row = i
            break

    if pivot_row is None:
        # All rows are zero at position; shortening = puncturing
        if value == 0:
            return puncture_code(generator, field_order, position)
        else:
            return []  # No codewords with nonzero value at position

    # Normalize pivot row so that generator[pivot_row][position] = 1
    inv = pow(generator[pivot_row][position] % field_order, -1, field_order)
    normalized = []
    for i in range(n_rows):
        row = [
            (generator[i][j] - value * inv * generator[pivot_row][j]) % field_order
            for j in range(n_cols)
        ]
        normalized.append(row)

    # Now all rows except pivot_row have 0 at position
    result = []
    for i in range(n_rows):
        if i == pivot_row:
            continue
        if normalized[i][position] % field_order != 0:
            # Subtract to make zero
            factor = normalized[i][position]
            normalized[i] = [
                (normalized[i][j] - factor * normalized[pivot_row][j]) % field_order
                for j in range(n_cols)
            ]
        # Remove the position column
        row = [normalized[i][j] for j in range(n_cols) if j != position]
        result.append(row)

    return result
