"""Exact coding theory kernels over prime fields."""

from __future__ import annotations

__all__ = ["matrix_rank", "parity_check_matrix", "puncture_code", "shorten_code"]


def _row_reduce(
    rows: list[list[int]], n_cols: int, field_order: int
) -> list[list[int]]:
    """Gaussian elimination, returns RREF."""
    mat = [list(row) for row in rows]
    n_rows = len(mat)
    pivot_row = 0
    for col in range(n_cols):
        pivot = next(
            (i for i in range(pivot_row, n_rows) if mat[i][col] % field_order != 0),
            None,
        )
        if pivot is None:
            continue
        mat[pivot_row], mat[pivot] = mat[pivot], mat[pivot_row]
        inv = pow(int(mat[pivot_row][col]) % field_order, -1, field_order)
        mat[pivot_row] = [(v * inv) % field_order for v in mat[pivot_row]]
        for i in range(n_rows):
            if i == pivot_row:
                continue
            factor = int(mat[i][col]) % field_order
            if factor == 0:
                continue
            mat[i] = [
                (mat[i][j] - factor * mat[pivot_row][j]) % field_order
                for j in range(n_cols)
            ]
        pivot_row += 1
        if pivot_row == n_rows:
            break
    return mat


def matrix_rank(generator: list[list[int]], field_order: int) -> int:
    """Return the rank of a generator matrix over GF(field_order).

    The rank is the number of nonzero rows in the row-reduced form, which is
    the dimension of the code the matrix generates (independent of any
    dependent or zero generator rows).
    """
    if not generator or not generator[0]:
        return 0
    n_cols = len(generator[0])
    rref = _row_reduce(generator, n_cols, field_order)
    return sum(1 for row in rref if any(v % field_order != 0 for v in row))


def parity_check_matrix(
    generator: list[list[int]], field_order: int
) -> list[list[int]]:
    """Compute the parity-check matrix H from a generator matrix G.

    H is the nullspace of G over GF(field_order).
    Returns rows of H such that G * H^T = 0.
    """
    n_rows = len(generator)
    n_cols = len(generator[0])
    rref = _row_reduce(generator, n_cols, field_order)
    rank = sum(1 for row in rref if any(v % field_order != 0 for v in row))

    # The nullspace has dimension n_cols - rank
    # We find the nullspace by solving G * x = 0
    # Using the RREF, identify pivot and free columns
    pivot_cols = []
    free_cols = []
    current_pivot_row = 0
    for col in range(n_cols):
        found = False
        for i in range(current_pivot_row, min(rank, n_rows)):
            if rref[i][col] % field_order != 0:
                pivot_cols.append(col)
                current_pivot_row = i + 1
                found = True
                break
        if not found:
            free_cols.append(col)

    # Build nullspace basis vectors
    nullspace = []
    for free_col in free_cols:
        vec = [0] * n_cols
        vec[free_col] = 1
        for i, pc in enumerate(pivot_cols):
            if i < len(rref):
                vec[pc] = (-rref[i][free_col]) % field_order
        nullspace.append(vec)

    return nullspace


def puncture_code(
    generator: list[list[int]], field_order: int, position: int
) -> list[list[int]]:
    """Puncture a code by deleting one coordinate column."""
    return [[row[j] for j in range(len(row)) if j != position] for row in generator]


def shorten_code(
    generator: list[list[int]], field_order: int, position: int
) -> list[list[int]]:
    """Shorten a code by fixing one coordinate to zero and deleting it.

    The shortened code is the subcode of codewords that are zero at the
    given coordinate, with that coordinate then deleted (punctured). This
    is a linear code: it is generated by the generator rows that are
    already zero at the position, after eliminating the position from the
    remaining rows using a nonzero pivot row (which is then dropped).
    """
    n_rows = len(generator)
    n_cols = len(generator[0])

    # Find a row that is nonzero at position (a pivot).
    pivot_row = None
    for i in range(n_rows):
        if generator[i][position] % field_order != 0:
            pivot_row = i
            break

    if pivot_row is None:
        # Every row is already zero at position; shortening = puncturing.
        return puncture_code(generator, field_order, position)

    # Normalize the pivot row so its position entry is 1, then eliminate the
    # position from every other row. Scaling by the pivot inverse (rather
    # than subtracting the raw pivot value) is what makes this correct over
    # GF(p) for p > 2.
    pivot_entry = generator[pivot_row][position] % field_order
    pivot_inv = pow(pivot_entry, -1, field_order)
    pivot_row_scaled = [(v * pivot_inv) % field_order for v in generator[pivot_row]]

    result = []
    for i in range(n_rows):
        if i == pivot_row:
            continue
        row = generator[i]
        if generator[i][position] % field_order != 0:
            factor = generator[i][position] % field_order
            row = [
                (generator[i][j] - factor * pivot_row_scaled[j]) % field_order
                for j in range(n_cols)
            ]
        # Delete the position column.
        result.append([row[j] for j in range(n_cols) if j != position])

    return result
