"""Compile the authoritative test plan manifest into topology and CI impact views."""

from __future__ import annotations

import argparse
import json
import tomllib
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

DEFAULT_MANIFEST = Path("tests/plan_manifest.toml")
DEFAULT_TOPOLOGY = Path("tests/topology.toml")
DEFAULT_IMPACT = Path(".github/ci-impact.json")


@dataclass(frozen=True, slots=True)
class LaneSpec:
    name: str
    kind: str
    tier: str | None
    paths: tuple[str, ...]
    command: str
    workers: int
    distribution: str
    timeout_seconds: int
    required_environment: tuple[str, ...]
    required_provider: str
    timing_sharding: bool
    runs_on: Mapping[str, bool]
    matrix: bool
    providers: tuple[str, ...]
    local_subsumes: tuple[str, ...]
    local_only: bool
    topology_lane: bool


@dataclass(frozen=True, slots=True)
class ImpactRule:
    name: str
    patterns: tuple[str, ...]
    suites: tuple[str, ...]
    suppresses: tuple[str, ...] = ()


@dataclass(frozen=True, slots=True)
class TestPlanManifest:
    version: int
    lanes: tuple[LaneSpec, ...]
    impact_rules: tuple[ImpactRule, ...]
    fallback_suites: tuple[str, ...]
    source: Path

    @property
    def pytest_lanes(self) -> tuple[LaneSpec, ...]:
        return tuple(lane for lane in self.lanes if lane.kind == "pytest")

    @property
    def suite_order(self) -> tuple[str, ...]:
        return tuple(
            lane.name
            for lane in self.lanes
            if lane.kind in {"pytest", "gate"} and not lane.local_only
        )


def _bool_map(
    raw: Mapping[str, Any] | None, *, default: bool = True
) -> dict[str, bool]:
    keys = ("pull_request", "merge_queue", "main", "scheduled")
    raw = raw or {}
    return {key: bool(raw.get(key, default)) for key in keys}


def load_manifest(path: Path) -> TestPlanManifest:
    payload = tomllib.loads(path.read_text(encoding="utf-8"))
    version = int(payload.get("version", 1))
    lanes: list[LaneSpec] = []
    for raw in payload.get("lanes", ()):
        lanes.append(
            LaneSpec(
                name=str(raw["name"]),
                kind=str(raw.get("kind", "pytest")),
                tier=str(raw["tier"]) if "tier" in raw else None,
                paths=tuple(str(item) for item in raw.get("paths", ())),
                command=str(raw["command"]),
                workers=int(raw.get("workers", 0)),
                distribution=str(raw.get("distribution", "none")),
                timeout_seconds=int(raw.get("timeout_seconds", 30)),
                required_environment=tuple(
                    str(item) for item in raw.get("required_environment", ())
                ),
                required_provider=str(raw.get("required_provider", "")),
                timing_sharding=bool(raw.get("timing_sharding", False)),
                runs_on=_bool_map(raw.get("ci") or raw.get("runs_on")),
                matrix=bool(raw.get("matrix", False)),
                providers=tuple(str(item) for item in raw.get("providers", ())),
                local_subsumes=tuple(
                    str(item) for item in raw.get("local_subsumes", ())
                ),
                local_only=bool(raw.get("local_only", False)),
                topology_lane=bool(
                    raw.get("topology_lane", raw.get("kind", "pytest") == "pytest")
                ),
            )
        )
    rules = tuple(
        ImpactRule(
            name=str(raw["name"]),
            patterns=tuple(str(item) for item in raw.get("patterns", ())),
            suites=tuple(str(item) for item in raw.get("suites", ())),
            suppresses=tuple(str(item) for item in raw.get("suppresses", ())),
        )
        for raw in payload.get("impact_rules", ())
    )
    fallback = payload.get("fallback", {})
    return TestPlanManifest(
        version=version,
        lanes=tuple(lanes),
        impact_rules=rules,
        fallback_suites=tuple(str(item) for item in fallback.get("suites", ())),
        source=path,
    )


def render_topology(manifest: TestPlanManifest) -> str:
    lines = [
        "version = 1",
        "",
        "# Generated by tools.test_plan.compile from tests/plan_manifest.toml.",
        "# Edit the manifest and run `make compile-test-plan`.",
        "",
    ]
    for lane in manifest.pytest_lanes:
        lines.append("[[lanes]]")
        lines.append(f'name = "{lane.name}"')
        lines.append(f'tier = "{lane.tier or lane.name}"')
        paths = ", ".join(f'"{path}"' for path in lane.paths)
        lines.append(f"paths = [{paths}]")
        lines.append(f"workers = {lane.workers}")
        lines.append(f'distribution = "{lane.distribution}"')
        lines.append(f"timeout_seconds = {lane.timeout_seconds}")
        envs = ", ".join(f'"{item}"' for item in lane.required_environment)
        lines.append(f"required_environment = [{envs}]")
        lines.append(f'required_provider = "{lane.required_provider}"')
        lines.append(f"timing_sharding = {'true' if lane.timing_sharding else 'false'}")
        ci = lane.runs_on
        lines.append(
            "ci = { "
            f"pull_request = {'true' if ci['pull_request'] else 'false'}, "
            f"merge_queue = {'true' if ci['merge_queue'] else 'false'}, "
            f"main = {'true' if ci['main'] else 'false'}, "
            f"scheduled = {'true' if ci['scheduled'] else 'false'}"
            " }"
        )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _catalog_entry(lane: LaneSpec) -> dict[str, Any]:
    entry: dict[str, Any] = {
        "command": lane.command,
        "topology_lane": lane.name if lane.topology_lane else None,
    }
    if lane.providers:
        entry["providers"] = list(lane.providers)
    if lane.local_subsumes:
        entry["local_subsumes"] = list(lane.local_subsumes)
    if lane.local_only:
        entry["local_only"] = True
    return entry


def render_impact(manifest: TestPlanManifest) -> dict[str, Any]:
    catalog = {lane.name: _catalog_entry(lane) for lane in manifest.lanes}
    # Auto-derive test-directory ownership rules for pytest lanes.
    derived_rules: list[dict[str, Any]] = []
    for lane in manifest.pytest_lanes:
        patterns = [f"{path.rstrip('/')}/**" for path in lane.paths]
        suites = [lane.name, "static"] if "static" in catalog else [lane.name]
        derived_rules.append(
            {
                "name": f"{lane.name}-tests",
                "patterns": patterns,
                "suites": suites,
            }
        )
    explicit_rules = [
        {
            "name": rule.name,
            "patterns": list(rule.patterns),
            "suites": list(rule.suites),
            **({"suppresses": list(rule.suppresses)} if rule.suppresses else {}),
        }
        for rule in manifest.impact_rules
    ]
    suites = list(manifest.suite_order)
    # Ensure deploy appears in catalog even if local_only.
    return {
        "version": 2,
        "suites": suites,
        "catalog": catalog,
        "rules": explicit_rules + derived_rules,
        "fallback": {"suites": list(manifest.fallback_suites or suites)},
        "meta": {
            "generated_from": str(manifest.source).replace("\\", "/"),
            "compiler": "tools.test_plan.compile",
        },
    }


def suppression_map(manifest: TestPlanManifest) -> dict[str, tuple[str, ...]]:
    return {
        rule.name: rule.suppresses for rule in manifest.impact_rules if rule.suppresses
    }


@dataclass
class CompileResult:
    topology: str
    impact: dict[str, Any]
    suppressions: dict[str, tuple[str, ...]] = field(default_factory=dict)


def compile_manifest(path: Path) -> CompileResult:
    manifest = load_manifest(path)
    return CompileResult(
        topology=render_topology(manifest),
        impact=render_impact(manifest),
        suppressions=suppression_map(manifest),
    )


def write_outputs(
    result: CompileResult,
    *,
    topology_path: Path,
    impact_path: Path,
) -> None:
    topology_path.parent.mkdir(parents=True, exist_ok=True)
    impact_path.parent.mkdir(parents=True, exist_ok=True)
    topology_path.write_text(result.topology, encoding="utf-8")
    impact_path.write_text(
        json.dumps(result.impact, indent=2, sort_keys=False) + "\n",
        encoding="utf-8",
    )


def check_outputs(
    result: CompileResult,
    *,
    topology_path: Path,
    impact_path: Path,
) -> list[str]:
    errors: list[str] = []
    if not topology_path.is_file():
        errors.append(f"missing topology: {topology_path}")
    elif topology_path.read_text(encoding="utf-8") != result.topology:
        errors.append(f"stale topology: {topology_path}")
    return errors


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--topology", type=Path, default=DEFAULT_TOPOLOGY)
    parser.add_argument("--impact", type=Path, default=DEFAULT_IMPACT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when generated outputs are missing or stale.",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="Write the topology.toml projection from the manifest.",
    )
    parser.add_argument(
        "--write-impact",
        action="store_true",
        help="Write ci-impact.json (experimental; prefer embedding suppressions).",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)
    result = compile_manifest(args.manifest)
    if args.check:
        errors = check_outputs(
            result, topology_path=args.topology, impact_path=args.impact
        )
        if errors:
            for error in errors:
                print(error)
            return 1
        print("test plan projections are up to date")
        return 0
    if args.write or args.write_impact:
        if args.write:
            args.topology.parent.mkdir(parents=True, exist_ok=True)
            args.topology.write_text(result.topology, encoding="utf-8")
            print(f"wrote {args.topology}")
        if args.write_impact:
            args.impact.parent.mkdir(parents=True, exist_ok=True)
            args.impact.write_text(
                json.dumps(result.impact, indent=2, sort_keys=False) + "\n",
                encoding="utf-8",
            )
            print(f"wrote {args.impact}")
        return 0
    print(result.topology)
    print(json.dumps(result.impact, indent=2))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
