"""Finite stochastic process operation declarations."""

from typing import Any

from jacobian.catalog.models import (
    MathTool,
    OperationDomainValidationError,
    OperationExample,
)
from jacobian.math.probability.stochastic_processes import operations as native
from jacobian.math.probability.stochastic_processes._models import (
    ConditionalExpectationRequest,
    DoobMartingaleRequest,
    DoobMartingaleResult,
    FiltrationRequest,
    FiltrationResult,
    FromObservationRequest,
    JoinRequest,
)
from jacobian.math.probability.stochastic_processes._poisson_binomial_models import (
    PoissonBinomialAdmissionError,
    PoissonBinomialRequest,
    PoissonBinomialResult,
)
from jacobian.math.probability.stochastic_processes.values import (
    FiniteRandomVariable,
    FiniteSigmaAlgebra,
)


def compute_poisson_binomial(
    request: PoissonBinomialRequest,
) -> PoissonBinomialResult:
    try:
        count_distribution = native.poisson_binomial(request.probabilities)
    except PoissonBinomialAdmissionError as exc:
        raise OperationDomainValidationError(
            location=("probabilities",),
            code="probability.poisson_binomial.admission",
            message=str(exc),
        ) from exc
    return PoissonBinomialResult._from_kernel(request, count_distribution)


def compute_sigma_from_observation(
    request: FromObservationRequest,
) -> FiniteSigmaAlgebra:
    return native.sigma_algebra_from_observation(request.space, request.observation)


def compute_join(request: JoinRequest) -> FiniteSigmaAlgebra:
    return native.sigma_algebra_join(request.sigma1, request.sigma2)


def compute_conditional_expectation(
    request: ConditionalExpectationRequest,
) -> FiniteRandomVariable:
    return native.conditional_expectation(request.rv, request.sigma)


def compute_filtration(request: FiltrationRequest) -> FiltrationResult:
    return FiltrationResult(
        space=request.space,
        observations=request.observations,
        sigmas=native.filtration_natural(request.space, request.observations),
    )


def compute_doob_martingale(
    request: DoobMartingaleRequest,
) -> DoobMartingaleResult:
    return DoobMartingaleResult(
        space=request.space,
        observations=request.observations,
        payoff=request.payoff,
        martingale=tuple(
            FiniteRandomVariable(space=request.space, values=values)
            for values in native.doob_martingale(
                request.space, request.observations, request.payoff
            )
        ),
    )


def _rational(numerator: int, denominator: int = 1) -> dict[str, str]:
    return {"num": str(numerator), "den": str(denominator)}


# A fair coin: samples {H, T}, masses 1/2, 1/2.
_SPACE = {
    "samples": ["H", "T"],
    "masses": [_rational(1, 2), _rational(1, 2)],
}

TOOLS: tuple[MathTool[Any, Any], ...] = (
    MathTool(
        operation_id="probability.finite_sigma_algebra.from_observation.compute",
        title="Construct a sigma algebra from an observation map",
        description="Return the sigma algebra generated by an observation map Y: Omega -> "
        "labels, whose blocks are equal-value fibers.",
        request_type=FromObservationRequest,
        result_type=FiniteSigmaAlgebra,
        run=compute_sigma_from_observation,
        tags=("stochastic-process", "sigma-algebra", "exact"),
        examples=(
            OperationExample(
                name="coin_observation",
                description="Sigma algebra from observing a fair coin.",
                input={"space": _SPACE, "observation": ["heads", "tails"]},
            ),
        ),
    ),
    MathTool(
        operation_id="probability.finite_sigma_algebra.join.compute",
        title="Compute the join of two sigma algebras",
        description="Return the least sigma algebra containing both input sigma algebras. "
        "Under the partition representation, this is the finest partition "
        "that refines both input partitions.",
        request_type=JoinRequest,
        result_type=FiniteSigmaAlgebra,
        run=compute_join,
        tags=("stochastic-process", "sigma-algebra", "exact"),
        examples=(
            OperationExample(
                name="trivial_join",
                description="Join of two trivial sigma algebras on a fair coin.",
                input={
                    "sigma1": {"space": _SPACE, "blocks": [["H", "T"]]},
                    "sigma2": {"space": _SPACE, "blocks": [["H", "T"]]},
                },
            ),
        ),
    ),
    MathTool(
        operation_id="probability.conditional_expectation.finite.compute",
        title="Compute E[X | G] as a block-constant random variable",
        description="Return the conditional expectation of a random variable with respect "
        "to a finite sigma algebra. On each block, the value is the "
        "probability-weighted average of X over the samples in that block.",
        request_type=ConditionalExpectationRequest,
        result_type=FiniteRandomVariable,
        run=compute_conditional_expectation,
        tags=("stochastic-process", "conditional-expectation", "exact"),
        examples=(
            OperationExample(
                name="coin_conditional_expectation",
                description="Conditional expectation of a coin payoff on the trivial sigma algebra.",
                input={
                    "rv": {
                        "space": _SPACE,
                        "values": [_rational(1), _rational(0)],
                    },
                    "sigma": {"space": _SPACE, "blocks": [["H", "T"]]},
                },
            ),
        ),
    ),
    MathTool(
        operation_id="probability.filtration.natural.compute",
        title="Compute the natural filtration of observations",
        description="Return the natural filtration F_t = sigma(Y_0, ..., Y_t) for each "
        "time t. Each F_t is a finite sigma algebra, and F_t refines F_{t-1}.",
        request_type=FiltrationRequest,
        result_type=FiltrationResult,
        run=compute_filtration,
        tags=("stochastic-process", "filtration", "exact"),
        examples=(
            OperationExample(
                name="single_step_filtration",
                description="Natural filtration of a single coin observation.",
                input={"space": _SPACE, "observations": [["heads", "tails"]]},
            ),
        ),
    ),
    MathTool(
        operation_id="probability.process.doob_martingale.compute",
        title="Compute the Doob martingale M_t = E[payoff | F_t]",
        description="Return the Doob martingale of a payoff random variable with respect "
        "to the natural filtration of observations. The result is one tuple "
        "of canonical rational values per time step.",
        request_type=DoobMartingaleRequest,
        result_type=DoobMartingaleResult,
        run=compute_doob_martingale,
        tags=("stochastic-process", "doob-martingale", "exact"),
        examples=(
            OperationExample(
                name="coin_doob_martingale",
                description="Doob martingale of a coin payoff process.",
                input={
                    "space": _SPACE,
                    "observations": [["heads", "tails"]],
                    "payoff": [_rational(1), _rational(0)],
                },
            ),
        ),
    ),
    MathTool(
        operation_id="probability.poisson_binomial.distribution.compute",
        title="Compute exact Poisson-binomial count distribution",
        description=(
            "Given independent Bernoulli trials with success probabilities, "
            "compute the exact probability of exactly k successes for each k."
        ),
        request_type=PoissonBinomialRequest,
        result_type=PoissonBinomialResult,
        run=compute_poisson_binomial,
        tags=("probability", "poisson-binomial", "exact"),
        examples=(
            OperationExample(
                name="poisson_binomial_basic",
                description="Compute the count distribution for two fair coins.",
                input={
                    "probabilities": [
                        {"num": "1", "den": "2"},
                        {"num": "1", "den": "2"},
                    ]
                },
            ),
        ),
    ),
)

__all__ = ["TOOLS"]
