"""Exact native kernels for finite stochastic processes."""

from __future__ import annotations

from fractions import Fraction

from jacobian._exact import CanonicalRational, require_bounded_rational
from jacobian.catalog.models import OperationDomainValidationError
from jacobian.math.probability._distribution import (
    FiniteDistributionAtom,
    FiniteRationalDistribution,
)
from jacobian.math.probability.stochastic_processes._admission import (
    admit_partition,
    admit_probability_space,
    admit_time_axis,
)
from jacobian.math.probability.stochastic_processes._models import (
    MAX_STOCHASTIC_VALUE_DIGITS,
    DoobMartingaleResult,
    FiltrationResult,
)
from jacobian.math.probability.stochastic_processes._poisson_binomial_models import (
    PoissonBinomialResult,
    _admit_probabilities,
)

from .values import FiniteProbabilitySpace, FiniteRandomVariable, FiniteSigmaAlgebra

__all__ = [
    "conditional_expectation",
    "doob_martingale",
    "filtration_natural",
    "poisson_binomial",
    "sigma_algebra_from_observation",
    "sigma_algebra_join",
    "verify_doob_martingale",
    "verify_filtration",
    "verify_poisson_binomial",
]


def poisson_binomial(
    probabilities: tuple[CanonicalRational, ...],
) -> FiniteRationalDistribution:
    """Return the exact count distribution of independent Bernoulli trials."""
    values = tuple(probability.as_fraction() for probability in probabilities)
    _admit_probabilities(values)
    return _poisson_binomial_kernel(values)


def verify_poisson_binomial(claim: PoissonBinomialResult) -> bool:
    """Verify a serialized count law against its retained Bernoulli parameters."""

    try:
        expected = poisson_binomial(claim.probabilities)
    except (TypeError, ValueError):
        return False
    return expected == claim.count_distribution


def _poisson_binomial_kernel(
    values: tuple[Fraction, ...],
) -> FiniteRationalDistribution:
    """Run the recurrence from one already-admitted probability tuple."""

    distribution = [Fraction(0)] * (len(values) + 1)
    distribution[0] = Fraction(1)
    for probability in values:
        for index in range(len(values), 0, -1):
            distribution[index] = (
                distribution[index] * (1 - probability)
                + distribution[index - 1] * probability
            )
        distribution[0] *= 1 - probability
    return FiniteRationalDistribution(
        atoms=tuple(
            FiniteDistributionAtom(
                value=CanonicalRational.from_fraction(Fraction(index)),
                probability=CanonicalRational.from_fraction(probability),
            )
            for index, probability in enumerate(distribution)
        )
    )


def _index_of(space: FiniteProbabilitySpace) -> dict[str, int]:
    return {s: i for i, s in enumerate(space.samples)}


def _mass(space: FiniteProbabilitySpace) -> list[Fraction]:
    return [mass.as_fraction() for mass in space.masses]


def sigma_algebra_from_observation(
    space: FiniteProbabilitySpace,
    observation: tuple[str, ...],
) -> FiniteSigmaAlgebra:
    """Return the sigma algebra generated by an observation map Y: Omega -> labels.

    Blocks are equal-value fibers.
    """
    admit_probability_space(space)
    return _sigma_from_observation(space, observation)


def _sigma_from_observation(
    space: FiniteProbabilitySpace, observation: tuple[str, ...]
) -> FiniteSigmaAlgebra:
    if len(observation) != len(space.samples):
        raise ValueError("observation must have one entry per sample")
    fibers: dict[str, set[str]] = {}
    for sample, obs in zip(space.samples, observation, strict=True):
        fibers.setdefault(obs, set()).add(sample)
    blocks = tuple(tuple(sorted(f)) for f in fibers.values())
    result = FiniteSigmaAlgebra(space=space, blocks=blocks)
    # Construction is structural; admit the generated partition once at the
    # operation boundary before publishing it to callers.
    admit_partition(result)
    return result


def sigma_algebra_join(
    sigma1: FiniteSigmaAlgebra,
    sigma2: FiniteSigmaAlgebra,
) -> FiniteSigmaAlgebra:
    """Return the least sigma algebra containing both sigma algebras.

    The join is the finest partition that refines both input partitions.
    """
    if sigma1.space != sigma2.space:
        raise ValueError("sigma algebras must share the same probability space")
    admit_probability_space(sigma1.space)
    admit_partition(sigma1)
    admit_partition(sigma2)
    return _sigma_join(sigma1, sigma2)


def _sigma_join(
    sigma1: FiniteSigmaAlgebra, sigma2: FiniteSigmaAlgebra
) -> FiniteSigmaAlgebra:
    blocks: list[tuple[str, ...]] = []
    for b1 in sigma1.blocks:
        for b2 in sigma2.blocks:
            intersection = frozenset(b1) & frozenset(b2)
            if intersection:
                blocks.append(tuple(sorted(intersection)))
    return FiniteSigmaAlgebra(space=sigma1.space, blocks=tuple(b for b in blocks))


def conditional_expectation(
    rv: FiniteRandomVariable,
    sigma: FiniteSigmaAlgebra,
) -> FiniteRandomVariable:
    """Return E[X | G] as a block-constant random variable.

    On each block, the conditional expectation is the probability-weighted
    average of X over the samples in that block.
    """
    if rv.space != sigma.space:
        raise ValueError("random variable and sigma algebra must share the same space")
    admit_probability_space(rv.space)
    admit_partition(sigma)
    return _conditional_expectation(rv, sigma)


def _conditional_expectation(
    rv: FiniteRandomVariable, sigma: FiniteSigmaAlgebra
) -> FiniteRandomVariable:
    for value in rv.values:
        require_bounded_rational(
            value,
            max_digits=MAX_STOCHASTIC_VALUE_DIGITS,
            label="random-variable value",
        )
    if rv.space != sigma.space:
        raise ValueError("random variable and sigma algebra must share the same space")
    idx = _index_of(rv.space)
    masses = _mass(rv.space)
    values = [value.as_fraction() for value in rv.values]
    ce_values: list[CanonicalRational] = []
    for sample in rv.space.samples:
        block = None
        for b in sigma.blocks:
            if sample in frozenset(b):
                block = b
                break
        if block is None:
            raise ValueError("sample not in any block")
        total_mass = Fraction(0)
        weighted_sum = Fraction(0)
        for s in block:
            si = idx[s]
            total_mass += masses[si]
            weighted_sum += masses[si] * values[si]
        ce_values.append(CanonicalRational.from_fraction(weighted_sum / total_mass))
    return FiniteRandomVariable(space=rv.space, values=tuple(ce_values))


def filtration_natural(
    space: FiniteProbabilitySpace,
    observations: tuple[tuple[str, ...], ...],
) -> tuple[FiniteSigmaAlgebra, ...]:
    """Return the natural filtration F_t = sigma(Y_0, ..., Y_t) for each time t."""
    admit_probability_space(space)
    admit_time_axis(space, observations)
    return _filtration_natural(space, observations)


def _filtration_natural(
    space: FiniteProbabilitySpace, observations: tuple[tuple[str, ...], ...]
) -> tuple[FiniteSigmaAlgebra, ...]:
    if not observations:
        return ()
    sigmas: list[FiniteSigmaAlgebra] = []
    accumulated: FiniteSigmaAlgebra | None = None
    for _t, obs in enumerate(observations):
        current = _sigma_from_observation(space, obs)
        if accumulated is None:
            accumulated = current
        else:
            accumulated = _sigma_join(accumulated, current)
        sigmas.append(accumulated)
    return tuple(sigmas)


def doob_martingale(
    space: FiniteProbabilitySpace,
    observations: tuple[tuple[str, ...], ...],
    payoff: tuple[CanonicalRational, ...],
) -> tuple[tuple[CanonicalRational, ...], ...]:
    """Return the Doob martingale M_t = E[payoff | F_t] for each time t.

    The payoff is a rational-valued random variable. The result is one
    tuple of canonical rational values per time step.
    """
    for value in payoff:
        require_bounded_rational(
            value, max_digits=MAX_STOCHASTIC_VALUE_DIGITS, label="payoff"
        )
    if len(payoff) != len(space.samples):
        raise ValueError("payoff must have one entry per sample")
    admit_probability_space(space)
    admit_time_axis(space, observations)
    sigmas = _filtration_natural(space, observations)
    rv = FiniteRandomVariable(space=space, values=payoff)
    result: list[tuple[CanonicalRational, ...]] = []
    for sigma in sigmas:
        ce = _conditional_expectation(rv, sigma)
        result.append(ce.values)
    return tuple(result)


def verify_filtration(claim: FiltrationResult) -> bool:
    """Verify filtration steps against the retained observations and space."""
    try:
        if not isinstance(claim, FiltrationResult):
            return False
        expected = filtration_natural(claim.space, claim.observations)
    except (
        AttributeError,
        ArithmeticError,
        IndexError,
        KeyError,
        OperationDomainValidationError,
        RuntimeError,
        TypeError,
        ValueError,
    ):
        return False
    return expected == claim.sigmas


def verify_doob_martingale(claim: DoobMartingaleResult) -> bool:
    """Verify conditional-expectation rows against retained process sources."""
    try:
        if not isinstance(claim, DoobMartingaleResult):
            return False
        expected = doob_martingale(claim.space, claim.observations, claim.payoff)
    except (
        AttributeError,
        ArithmeticError,
        IndexError,
        KeyError,
        OperationDomainValidationError,
        RuntimeError,
        TypeError,
        ValueError,
    ):
        return False
    return (
        len(claim.martingale) == len(expected)
        and all(row.space == claim.space for row in claim.martingale)
        and tuple(row.values for row in claim.martingale) == expected
    )
