"""Partial typing boundary for the untyped z3-solver Python package."""

from typing import Any

class Z3Exception(Exception): ...

def And(*args: Any, **kwargs: Any) -> Any: ...
def Bool(*args: Any, **kwargs: Any) -> Any: ...
def BoolVal(*args: Any, **kwargs: Any) -> Any: ...
def Context(*args: Any, **kwargs: Any) -> Any: ...
def Distinct(*args: Any, **kwargs: Any) -> Any: ...
def FreshBool(*args: Any, **kwargs: Any) -> Any: ...
def Goal(*args: Any, **kwargs: Any) -> Any: ...
def If(*args: Any, **kwargs: Any) -> Any: ...
def Implies(*args: Any, **kwargs: Any) -> Any: ...
def Int(*args: Any, **kwargs: Any) -> Any: ...
def IntVal(*args: Any, **kwargs: Any) -> Any: ...
def Not(*args: Any, **kwargs: Any) -> Any: ...
def Optimize(*args: Any, **kwargs: Any) -> Any: ...
def Or(*args: Any, **kwargs: Any) -> Any: ...
def PbGe(*args: Any, **kwargs: Any) -> Any: ...
def PbLe(*args: Any, **kwargs: Any) -> Any: ...
def Probe(*args: Any, **kwargs: Any) -> Any: ...
def RealVal(*args: Any, **kwargs: Any) -> Any: ...
def Solver(*args: Any, **kwargs: Any) -> Any: ...
def SolverFor(*args: Any, **kwargs: Any) -> Any: ...
def Sum(*args: Any, **kwargs: Any) -> Any: ...
def is_app(*args: Any, **kwargs: Any) -> Any: ...
def is_arith(*args: Any, **kwargs: Any) -> Any: ...
def is_bool(*args: Any, **kwargs: Any) -> Any: ...
def is_false(*args: Any, **kwargs: Any) -> Any: ...
def is_int_value(*args: Any, **kwargs: Any) -> Any: ...
def is_rational_value(*args: Any, **kwargs: Any) -> Any: ...
def is_true(*args: Any, **kwargs: Any) -> Any: ...
def parse_smt2_string(*args: Any, **kwargs: Any) -> Any: ...

sat: Any
unknown: Any
unsat: Any

Z3_INT_SORT: int
Z3_REAL_SORT: int
Z3_OP_ADD: int
Z3_OP_AND: int
Z3_OP_DISTINCT: int
Z3_OP_DIV: int
Z3_OP_EQ: int
Z3_OP_FALSE: int
Z3_OP_GE: int
Z3_OP_GT: int
Z3_OP_IDIV: int
Z3_OP_IMPLIES: int
Z3_OP_ITE: int
Z3_OP_LE: int
Z3_OP_LT: int
Z3_OP_MUL: int
Z3_OP_NOT: int
Z3_OP_OR: int
Z3_OP_SUB: int
Z3_OP_TRUE: int
Z3_OP_UMINUS: int
Z3_OP_UNINTERPRETED: int
Z3_OP_XOR: int
