"""Public declaration for the degenerate-chain subcomplex operation."""

from jacobian.catalog.models import MathTool, OperationExample
from jacobian.math.topology.simplicial_sets.degenerate_submodule import (
    DegenerateSubmoduleRequest,
    DegenerateSubmoduleResult,
    degenerate_submodule,
)
from jacobian.math.topology.simplicial_sets.standard import standard_simplex

_DELTA_ONE = standard_simplex(1, 2).model_dump(mode="json")

TOOLS = (
    MathTool(
        operation_id="topology.simplicial_set.degenerate_submodule.compute",
        title="Compute the degenerate subcomplex of a finite simplicial set",
        description=(
            "Return the exact subcomplex of unnormalized chains generated by all "
            "in-range degeneracies. Each degree retains the degenerate source "
            "basis indices, its injection into the full simplex basis, and the "
            "restricted boundary, over ZZ, QQ, or a bounded prime field."
        ),
        request_type=DegenerateSubmoduleRequest,
        result_type=DegenerateSubmoduleResult,
        run=degenerate_submodule,
        tags=("topology", "simplicial-set", "chains", "degenerate", "exact"),
        discovery_terms=(
            "degenerate simplices",
            "degenerate chains",
            "degenerate subcomplex",
            "unnormalized chains",
        ),
        examples=(
            OperationExample(
                name="delta_one_degenerate_chains",
                description=(
                    "Compute the degenerate chain subcomplex of the degree-0..2 "
                    "prefix of Delta[1], retaining its source-basis inclusions."
                ),
                input={"simplicial_set": _DELTA_ONE},
            ),
        ),
    ),
)

__all__ = ["TOOLS"]
