# Generated by tools.test_plan.compile — do not edit.
.PHONY: test-unit test-component test-domain test-composition test-storage test-process test-mcp test-provider test-lean test-e2e

test-unit: ## Pytest lane unit (10s, sequential).
	$(call run_topology_lane,unit)

test-component: ## Pytest lane component (30s, 4 workers).
	$(call run_topology_lane,component)

test-domain: ## Pytest lane domain (120s, 4 workers).
	$(call run_topology_lane,domain)

test-composition: ## Pytest lane composition (120s, 2 workers).
	$(call run_topology_lane,composition)

test-storage: ## Pytest lane storage (120s, sequential).
	$(call run_topology_lane,storage)

test-process: ## Pytest lane process (120s, 2 workers).
	$(call run_topology_lane,process)

test-mcp: ## Pytest lane mcp (120s, 2 workers).
	$(call run_topology_lane,mcp)

test-provider: ## Pytest lane provider (180s, 1 workers).
	$(call run_topology_lane,provider)

test-lean: ## Pytest lane lean (300s, sequential).
	$(call run_topology_lane,lean)

test-e2e: ## Pytest lane e2e (180s, sequential).
	$(call run_topology_lane,e2e)
