"""Exact type-A highest-weight characters by Freudenthal recursion."""

from __future__ import annotations

from collections.abc import Iterator
from math import comb

from jacobian.catalog.models import (
    OperationDomainValidationError,
    OperationResourceAdmissionError,
)
from jacobian.math.groups.root_systems._models import (
    MAX_HIGHEST_WEIGHT_BITS,
    CartanMatrix,
)
from jacobian.math.groups.root_systems._weight_character_models import (
    MAX_CHARACTER_MULTIPLICITY_BITS,
    MAX_CHARACTER_STATES,
    IrreducibleWeightCharacter,
    WeightMultiplicity,
    _type_a_axis_order,
)
from jacobian.math.groups.root_systems.operations import (
    _admit_cartan_finite_type,
    _as_cartan,
)

MAX_CHARACTER_WORK = 50_000_000
MAX_CHARACTER_OUTPUT_DIGITS = 64_000


def _compositions(total: int, slots: int) -> Iterator[tuple[int, ...]]:
    """Yield weak compositions in lexicographic order."""
    if slots == 1:
        yield (total,)
        return
    for first in range(total + 1):
        for rest in _compositions(total - first, slots - 1):
            yield (first, *rest)


def _partition_dominates(left: tuple[int, ...], right: tuple[int, ...]) -> bool:
    return all(
        sum(left[:index]) >= sum(right[:index]) for index in range(1, len(left) + 1)
    )


def _type_a_candidates(
    partition: tuple[int, ...], total: int
) -> tuple[tuple[int, ...], ...]:
    """Enumerate the complete type-A weight set using the Kostka criterion.

    For type A_(n-1), a weight is the content of a semistandard tableau of
    shape ``partition``. Such contents are precisely nonnegative weak
    compositions whose decreasing rearrangement is dominated by that shape.
    This avoids an incomplete rectangular guess of the weight polytope.
    """
    states: list[tuple[int, ...]] = []
    for content in _compositions(total, len(partition)):
        if _partition_dominates(partition, tuple(sorted(content, reverse=True))):
            states.append(content)
    return tuple(states)


def highest_weight_character(
    matrix: CartanMatrix | tuple[tuple[int, ...], ...],
    highest_weight: tuple[int, ...],
) -> IrreducibleWeightCharacter:
    """Return the full irreducible character for a finite type-A datum.

    The operation uses Freudenthal's recursion. Complete candidate weights
    are independently generated by the type-A content/Kostka criterion.
    Other finite types are rejected explicitly; no partial character is
    returned.
    """
    cartan = _as_cartan(matrix)
    rank = len(cartan)
    if (
        not isinstance(highest_weight, (tuple, list))
        or len(highest_weight) != rank
        or any(type(value) is not int or value < 0 for value in highest_weight)
    ):
        raise OperationDomainValidationError(
            location=("highest_weight",),
            code="root_system.invalid_dominant_weight",
            message="highest weight must be nonnegative and match the Cartan rank",
        )
    highest = tuple(highest_weight)
    if (
        max((value.bit_length() for value in highest), default=0)
        > MAX_HIGHEST_WEIGHT_BITS
    ):
        raise OperationResourceAdmissionError(
            location=("highest_weight",),
            code="root_system.character_bounds",
            message="highest-weight coordinates exceed the admitted bit bound",
        )

    # Recognize the bounded Cartan axis before computing an exact output
    # envelope: a worst-permutation estimate would reject useful valid inputs.
    axis_order = _type_a_axis_order(cartan.entries)
    if axis_order is None:
        raise OperationDomainValidationError(
            location=("matrix",),
            code="root_system.character_type_unsupported",
            message="highest-weight character enumeration currently supports irreducible type A only",
        )
    kernel_highest = tuple(highest[index] for index in axis_order)
    inverse_axis = tuple(axis_order.index(index) for index in range(rank))
    # A dominant A_(n-1) weight a_i has GL_n partition
    # (a_1+...+a_(n-1), a_2+...+a_(n-1), ..., a_(n-1), 0).
    n = rank + 1
    partition = (*(sum(kernel_highest[index:]) for index in range(rank)), 0)
    total = sum(partition)
    # Every candidate content has total ``total``. The number of all weak
    # compositions is a sound upper bound on both candidate states and output.
    # Reject large totals before computing a potentially huge binomial.
    if total + 1 > MAX_CHARACTER_STATES:
        raise OperationResourceAdmissionError(
            location=("highest_weight",),
            code="root_system.character_bounds",
            message="type-A character candidate-state envelope exceeds its admitted bound",
        )
    state_bound = comb(total + n - 1, n - 1)
    root_count = rank * n // 2
    work_bound = state_bound * root_count * max(total, 1) * 2
    dimension_bits_bound = root_count * (total + n).bit_length() + 2
    intermediate_bits_bound = (
        dimension_bits_bound + (4 * root_count * max(total, 1) ** 2 + 1).bit_length()
    )
    output_bound = state_bound * (
        128 + rank * ((total + 1).bit_length() + 2) + intermediate_bits_bound // 3 + 4
    )
    if (
        state_bound > MAX_CHARACTER_STATES
        or work_bound > MAX_CHARACTER_WORK
        or intermediate_bits_bound > MAX_CHARACTER_MULTIPLICITY_BITS
        or output_bound > MAX_CHARACTER_OUTPUT_DIGITS
    ):
        raise OperationResourceAdmissionError(
            location=("highest_weight",),
            code="root_system.character_bounds",
            message="complete type-A character exceeds its admitted state, work, integer, or output bound",
        )

    # Admission precedes all candidate and root expansion.
    _admit_cartan_finite_type(cartan.entries)
    contents = _type_a_candidates(partition, total)
    if len(contents) > state_bound:
        raise RuntimeError(
            "type-A content enumeration exceeded its admitted state bound"
        )
    content_set = set(contents)
    # Convert GL_n content to the simple-coroot pairings, i.e. fundamental
    # weight coordinates. Fixed total makes this map injective.
    content_to_weight = {
        content: tuple(content[index] - content[index + 1] for index in range(rank))
        for content in contents
    }

    # Increasing root height puts all higher weights before the weight whose
    # recurrence consumes them. In type A, alpha_(p,q)=e_p-e_q.
    def height(content: tuple[int, ...]) -> int:
        return sum(
            sum(partition[index] - content[index] for index in range(prefix))
            for prefix in range(1, n)
        )

    ordered = sorted(contents, key=lambda value: (height(value), value))
    multiplicities: dict[tuple[int, ...], int] = {}
    rho_twice = tuple(n - 1 - 2 * index for index in range(n))
    highest_norm_shift = sum(
        (partition[index] ** 2) + partition[index] * rho_twice[index]
        for index in range(n)
    )
    positive_roots = tuple((p, q) for p in range(n) for q in range(p + 1, n))

    for content in ordered:
        if content == partition:
            multiplicities[content] = 1
            continue
        denominator = highest_norm_shift - sum(
            content[index] ** 2 + content[index] * rho_twice[index]
            for index in range(n)
        )
        if denominator <= 0:
            raise RuntimeError(
                "Freudenthal denominator was not positive below the top weight"
            )
        numerator = 0
        for p, q in positive_roots:
            for step in range(1, content[q] + 1):
                raised = list(content)
                raised[p] += step
                raised[q] -= step
                raised_content = tuple(raised)
                if raised_content not in content_set:
                    continue
                pairing = content[p] - content[q] + 2 * step
                numerator += 2 * pairing * multiplicities[raised_content]
        quotient, remainder = divmod(numerator, denominator)
        if remainder or quotient < 1:
            raise RuntimeError(
                "Freudenthal recursion did not yield a positive integer multiplicity"
            )
        multiplicities[content] = quotient

    terms = tuple(
        sorted(
            (
                WeightMultiplicity(
                    weight=tuple(
                        content_to_weight[content][index] for index in inverse_axis
                    ),
                    multiplicity=multiplicities[content],
                )
                for content in contents
            ),
            key=lambda term: term.weight,
        )
    )
    return IrreducibleWeightCharacter._from_kernel(cartan, highest, terms)
