from __future__ import annotations

import pytest
from pydantic import ValidationError

from jacobian.math.group._models import GroupOrbitRequest


def test_group_orbit_contract_binds_the_point_to_the_declared_degree() -> None:
    with pytest.raises(ValidationError, match="point"):
        GroupOrbitRequest(degree=2, generators=((1, 0),), point=3)


def _s3_request():
    from jacobian.math.group._models import GroupConjugacyClassesRequest

    return GroupConjugacyClassesRequest(
        degree=3,
        generators=((1, 2, 0), (1, 0, 2)),
    )


def _s3_result():
    from jacobian.math.group._operations import compute_conjugacy_classes

    return compute_conjugacy_classes(_s3_request())


def test_group_conjugacy_classes_partition_s3() -> None:
    """S3 has three conjugacy classes of sizes 1, 2, 3."""
    result = _s3_result()
    assert result.class_count == 3
    sizes = sorted(cls.size for cls in result.classes)
    assert sizes == [1, 2, 3]
    # classes partition the group: total elements == |S3| = 6
    assert sum(cls.size for cls in result.classes) == 6
    # the identity (0,1,2) is its own class
    identity_class = [cls for cls in result.classes if cls.elements == ((0, 1, 2),)]
    assert len(identity_class) == 1
    assert identity_class[0].size == 1


def test_group_conjugacy_classes_abelian_group_is_singletons() -> None:
    """In an abelian group every element is its own conjugacy class."""
    from jacobian.math.group._models import GroupConjugacyClassesRequest
    from jacobian.math.group._operations import (
        compute_conjugacy_classes,
        compute_group_order,
    )

    # Cyclic group C3 generated by the 3-cycle (1,2,0).
    gens = ((1, 2, 0),)
    request = GroupConjugacyClassesRequest(degree=3, generators=gens)
    result = compute_conjugacy_classes(request)
    order = int(compute_group_order(request).order)
    assert order == 3
    assert result.class_count == 3
    for cls in result.classes:
        assert cls.size == 1


def test_group_conjugacy_classes_canonical_order_s3() -> None:
    """Members are lexicographically sorted; classes sort by first element."""
    result = _s3_result()
    assert tuple(cls.elements for cls in result.classes) == (
        ((0, 1, 2),),
        ((0, 2, 1), (1, 0, 2), (2, 1, 0)),
        ((1, 2, 0), (2, 0, 1)),
    )


def test_group_conjugacy_classes_serialization_is_hash_seed_independent() -> None:
    """Separate processes serialize the same partition identically."""
    import os
    import subprocess
    import sys

    script = (
        "from jacobian.math.group.operations import conjugacy_classes;"
        "import json;"
        "print(json.dumps(conjugacy_classes(3, [[1, 2, 0], [1, 0, 2]])))"
    )
    outputs = set()
    for seed in ("0", "1", "424242"):
        env = dict(os.environ)
        env["PYTHONHASHSEED"] = seed
        proc = subprocess.run(
            [sys.executable, "-c", script],
            capture_output=True,
            text=True,
            env=env,
            check=True,
        )
        outputs.add(proc.stdout.strip())
    assert len(outputs) == 1


def test_group_subgroup_lattice_serialization_is_hash_seed_independent() -> None:
    """Separate processes serialize the same lattice identically."""
    import os
    import subprocess
    import sys

    script = (
        "from jacobian.math.group.operations import subgroup_lattice;"
        "import json;"
        "print(json.dumps(subgroup_lattice(4, [[1, 2, 3, 0]])))"
    )
    outputs = set()
    for seed in ("0", "1", "424242"):
        env = dict(os.environ)
        env["PYTHONHASHSEED"] = seed
        proc = subprocess.run(
            [sys.executable, "-c", script],
            capture_output=True,
            text=True,
            env=env,
            check=True,
        )
        outputs.add(proc.stdout.strip())
    assert len(outputs) == 1


def test_group_conjugacy_classes_result_accepts_trivial_and_abelian_partitions() -> (
    None
):
    from jacobian.math.group._models import GroupConjugacyClassesResult

    trivial = GroupConjugacyClassesResult(
        degree=1,
        generators=((0,),),
        classes=({"elements": ((0,),), "size": 1},),
        class_count=1,
    )
    assert trivial.class_count == 1
    cyclic_c4 = GroupConjugacyClassesResult(
        degree=4,
        generators=((1, 2, 3, 0),),
        classes=tuple(
            {"elements": (cycle,), "size": 1}
            for cycle in [(0, 1, 2, 3), (1, 2, 3, 0), (2, 3, 0, 1), (3, 0, 1, 2)]
        ),
        class_count=4,
    )
    assert cyclic_c4.class_count == 4


def _mutated_s3_payload(mutation) -> dict:
    payload = _s3_result().model_dump(mode="json")
    mutation(payload)
    return payload


def test_group_conjugacy_classes_result_rejects_non_permutations() -> None:
    from jacobian.math.group._models import GroupConjugacyClassesResult

    def inject(payload):
        payload["classes"][0]["elements"] = [[0, 0]]

    with pytest.raises(ValidationError):
        GroupConjugacyClassesResult.model_validate(_mutated_s3_payload(inject))


def test_group_conjugacy_classes_result_rejects_duplicate_elements() -> None:
    from jacobian.math.group._models import GroupConjugacyClassesResult

    def duplicate(payload):
        payload["classes"][1]["elements"].append([0, 2, 1])
        payload["classes"][1]["size"] = len(payload["classes"][1]["elements"])

    with pytest.raises(ValidationError):
        GroupConjugacyClassesResult.model_validate(_mutated_s3_payload(duplicate))


def test_group_conjugacy_classes_result_rejects_wrong_partition_of_valid_group() -> (
    None
):
    """A valid group split into non-conjugacy classes must be rejected."""
    from jacobian.math.group._models import GroupConjugacyClassesResult

    def repartition(payload):
        payload["classes"] = [
            {"elements": [[0, 1, 2]], "size": 1},
            {"elements": [[0, 2, 1], [2, 1, 0]], "size": 2},
            {"elements": [[1, 0, 2]], "size": 1},
            {"elements": [[1, 2, 0], [2, 0, 1]], "size": 2},
        ]
        payload["class_count"] = 4

    with pytest.raises(ValidationError, match="conjugacy partition"):
        GroupConjugacyClassesResult.model_validate(_mutated_s3_payload(repartition))


def test_group_conjugacy_classes_result_requires_canonical_member_order() -> None:
    from jacobian.math.group._models import GroupConjugacyClassesResult

    def unsort_members(payload):
        transposition_class = next(
            entry
            for entry in payload["classes"]
            if {tuple(p) for p in entry["elements"]}
            == {(0, 2, 1), (1, 0, 2), (2, 1, 0)}
        )
        transposition_class["elements"] = list(
            reversed(transposition_class["elements"])
        )

    with pytest.raises(ValidationError, match="canonical element and class order"):
        GroupConjugacyClassesResult.model_validate(_mutated_s3_payload(unsort_members))


def test_group_conjugacy_classes_result_requires_representative_class_order() -> None:
    from jacobian.math.group._models import GroupConjugacyClassesResult

    def reorder_classes(payload):
        payload["classes"] = list(reversed(payload["classes"]))

    with pytest.raises(ValidationError, match="canonical element and class order"):
        GroupConjugacyClassesResult.model_validate(_mutated_s3_payload(reorder_classes))


def test_group_subgroup_lattice_result_requires_canonical_entry_order() -> None:
    from jacobian.math.group._models import (
        GroupSubgroupLatticeRequest,
        GroupSubgroupLatticeResult,
    )
    from jacobian.math.group._operations import compute_subgroup_lattice

    result = compute_subgroup_lattice(
        GroupSubgroupLatticeRequest(degree=4, generators=((1, 2, 3, 0),))
    )
    payload = result.model_dump(mode="json")
    payload["subgroups"] = list(reversed(payload["subgroups"]))
    with pytest.raises(ValidationError, match="canonical element and entry order"):
        GroupSubgroupLatticeResult.model_validate(payload)


def test_group_conjugacy_classes_result_round_trips_through_model_dump() -> None:
    from jacobian.math.group._models import GroupConjugacyClassesResult

    result = _s3_result()
    revived = GroupConjugacyClassesResult.model_validate(result.model_dump())
    assert revived == result
