from __future__ import annotations

import pytest
from pydantic import ValidationError

from jacobian.math.group._models import GroupOrbitRequest


def test_group_orbit_contract_binds_the_point_to_the_declared_degree() -> None:
    with pytest.raises(ValidationError, match="point"):
        GroupOrbitRequest(degree=2, generators=((1, 0),), point=3)


def test_group_conjugacy_classes_partition_s3() -> None:
    """S3 has three conjugacy classes of sizes 1, 2, 3."""
    from jacobian.math.group._models import GroupConjugacyClassesRequest
    from jacobian.math.group._operations import compute_group_conjugacy_classes

    gens = ((1, 2, 0), (1, 0, 2))
    result = compute_group_conjugacy_classes(
        GroupConjugacyClassesRequest(degree=3, generators=gens),
    )
    assert len(result.classes) == 3
    sizes = sorted(len(cls) for cls in result.classes)
    assert sizes == [1, 2, 3]
    # classes partition the group: total elements == |S3| = 6
    assert sum(len(cls) for cls in result.classes) == 6
    # the identity (0,1,2) is its own class
    identity_class = [cls for cls in result.classes if (0, 1, 2) in cls]
    assert len(identity_class) == 1
    assert len(identity_class[0]) == 1


def test_group_conjugacy_classes_abelian_group_is_singletons() -> None:
    """In an abelian group every element is its own conjugacy class."""
    from jacobian.math.group._models import (
        GroupConjugacyClassesRequest,
        PermutationGroupRequest,
    )
    from jacobian.math.group._operations import (
        compute_group_conjugacy_classes,
        compute_group_order,
    )

    # Cyclic group C3 generated by the 3-cycle (1,2,0).
    gens = ((1, 2, 0),)
    result = compute_group_conjugacy_classes(
        GroupConjugacyClassesRequest(degree=3, generators=gens),
    )
    order = int(compute_group_order(PermutationGroupRequest(degree=3, generators=gens)).order)
    assert order == 3
    assert len(result.classes) == 3
    for cls in result.classes:
        assert len(cls) == 1
