"""Immutable catalog declarations for finite integer-sequence operations."""

from typing import Any

from jacobian._models import StrictModel
from jacobian.catalog._examples import example
from jacobian.catalog.models import MathTool
from jacobian.math.number_theory.sequences.core._models import (
    IntegerSequenceBooleanResult,
    IntegerSequenceFrequenciesResult,
    IntegerSequenceIndexListResult,
    IntegerSequenceListResult,
    IntegerSequenceRationalResult,
    IntegerSequenceValueResult,
)
from jacobian.math.number_theory.sequences.core._support import sequence_operation
from jacobian.math.number_theory.sequences.core.operations import (
    decide_arithmetic,
    decide_geometric,
    decide_nondecreasing,
    decide_strictly_increasing,
    first_differences,
    frequencies,
    parities,
    prefix_gcds,
    prefix_lcms,
    prefix_maxima,
    prefix_minima,
    prefix_products,
    prefix_sums,
    reverse_sequence,
    second_differences,
    sequence_distinct_count,
    sequence_gcd,
    sequence_lcm,
    sequence_maximum,
    sequence_mean,
    sequence_median,
    sequence_minimum,
    sequence_product,
    sequence_range,
    sequence_sum,
    signs,
    sort_sequence,
    sorted_unique,
    zero_indices,
)
from jacobian.math.number_theory.sequences.core.values import IntegerSequence


def _tool[ResultT: StrictModel](
    operation_id: str,
    title: str,
    description: str,
    result_type: type[ResultT],
    operation: Any,
    *tags: str,
    example_name: str,
    example_description: str,
    example_input: dict[str, Any],
) -> MathTool[IntegerSequence, ResultT]:
    return sequence_operation(
        operation_id,
        title,
        description,
        IntegerSequence,
        result_type,
        operation,
        *tags,
        examples=(example(example_name, example_description, example_input),),
    )


_SEQ = {"values": ["1", "2", "3"]}

TOOLS: tuple[MathTool[Any, Any], ...] = (
    _tool(
        "sequence.compute.sum",
        "Sum integer sequence",
        "Compute the exact sum of a finite integer sequence.",
        IntegerSequenceValueResult,
        sequence_sum,
        "sequence",
        "exact",
        example_name="sum",
        example_description="Sum 1, 2, and 3.",
        example_input=_SEQ,
    ),
    _tool(
        "sequence.compute.product",
        "Multiply integer sequence",
        "Compute the exact product of a finite integer sequence.",
        IntegerSequenceValueResult,
        sequence_product,
        "sequence",
        "exact",
        example_name="product",
        example_description="Multiply 1, 2, and 3.",
        example_input=_SEQ,
    ),
    _tool(
        "sequence.compute.gcd",
        "Compute sequence gcd",
        "Compute the gcd of every value in a finite integer sequence.",
        IntegerSequenceValueResult,
        sequence_gcd,
        "sequence",
        "divisibility",
        example_name="gcd",
        example_description="Compute the gcd of 12 and 18.",
        example_input={"values": ["12", "18"]},
    ),
    _tool(
        "sequence.compute.lcm",
        "Compute sequence lcm",
        "Compute the lcm of every value in a finite integer sequence.",
        IntegerSequenceValueResult,
        sequence_lcm,
        "sequence",
        "divisibility",
        example_name="lcm",
        example_description="Compute the lcm of 4 and 6.",
        example_input={"values": ["4", "6"]},
    ),
    _tool(
        "sequence.compute.minimum",
        "Compute sequence minimum",
        "Compute the least value in a finite integer sequence.",
        IntegerSequenceValueResult,
        sequence_minimum,
        "sequence",
        "order",
        example_name="minimum",
        example_description="Find the minimum of 3, 1, and 2.",
        example_input={"values": ["3", "1", "2"]},
    ),
    _tool(
        "sequence.compute.maximum",
        "Compute sequence maximum",
        "Compute the greatest value in a finite integer sequence.",
        IntegerSequenceValueResult,
        sequence_maximum,
        "sequence",
        "order",
        example_name="maximum",
        example_description="Find the maximum of 1, 3, and 2.",
        example_input={"values": ["1", "3", "2"]},
    ),
    _tool(
        "sequence.compute.range",
        "Compute sequence range",
        "Compute maximum minus minimum for a finite integer sequence.",
        IntegerSequenceValueResult,
        sequence_range,
        "sequence",
        "statistic",
        example_name="range",
        example_description="Compute the range of 1, 4, and 2.",
        example_input={"values": ["1", "4", "2"]},
    ),
    _tool(
        "sequence.compute.distinct_count",
        "Count distinct sequence values",
        "Count distinct values in a finite integer sequence.",
        IntegerSequenceValueResult,
        sequence_distinct_count,
        "sequence",
        "counting",
        example_name="distinct",
        example_description="Count distinct values in 1, 2, and 1.",
        example_input={"values": ["1", "2", "1"]},
    ),
    _tool(
        "sequence.compute.mean",
        "Compute sequence mean",
        "Compute the reduced arithmetic mean of a finite integer sequence.",
        IntegerSequenceRationalResult,
        sequence_mean,
        "sequence",
        "statistic",
        example_name="mean",
        example_description="Compute the mean of 1, 2, and 3.",
        example_input=_SEQ,
    ),
    _tool(
        "sequence.compute.median",
        "Compute sequence median",
        "Compute the reduced median of a finite integer sequence.",
        IntegerSequenceRationalResult,
        sequence_median,
        "sequence",
        "statistic",
        example_name="median",
        example_description="Compute the median of 1, 3, and 2.",
        example_input={"values": ["1", "3", "2"]},
    ),
    _tool(
        "sequence.compute.prefix_sums",
        "Compute prefix sums",
        "Compute every nonempty prefix sum of a finite integer sequence.",
        IntegerSequenceListResult,
        prefix_sums,
        "sequence",
        "transform",
        example_name="prefix_sums",
        example_description="Compute prefix sums of 1, 2, and 3.",
        example_input=_SEQ,
    ),
    _tool(
        "sequence.compute.first_differences",
        "Compute first differences",
        "Compute adjacent first differences of a finite integer sequence.",
        IntegerSequenceListResult,
        first_differences,
        "sequence",
        "transform",
        example_name="first_differences",
        example_description="Compute differences of consecutive squares.",
        example_input={"values": ["1", "4", "9", "16"]},
    ),
    _tool(
        "sequence.compute.prefix_products",
        "Compute prefix products",
        "Compute every nonempty prefix product of a finite integer sequence.",
        IntegerSequenceListResult,
        prefix_products,
        "sequence",
        "transform",
        example_name="prefix_products",
        example_description="Compute prefix products of 2, 3, and 4.",
        example_input={"values": ["2", "3", "4"]},
    ),
    _tool(
        "sequence.compute.prefix_minima",
        "Compute prefix minima",
        "Compute the minimum of every nonempty prefix.",
        IntegerSequenceListResult,
        prefix_minima,
        "sequence",
        "transform",
        example_name="prefix_minima",
        example_description="Compute prefix minima of 3, 1, and 2.",
        example_input={"values": ["3", "1", "2"]},
    ),
    _tool(
        "sequence.compute.prefix_maxima",
        "Compute prefix maxima",
        "Compute the maximum of every nonempty prefix.",
        IntegerSequenceListResult,
        prefix_maxima,
        "sequence",
        "transform",
        example_name="prefix_maxima",
        example_description="Compute prefix maxima of 1, 3, and 2.",
        example_input={"values": ["1", "3", "2"]},
    ),
    _tool(
        "sequence.compute.prefix_gcds",
        "Compute prefix gcds",
        "Compute the gcd of every nonempty prefix.",
        IntegerSequenceListResult,
        prefix_gcds,
        "sequence",
        "divisibility",
        example_name="prefix_gcds",
        example_description="Compute prefix gcds of 18, 24, and 15.",
        example_input={"values": ["18", "24", "15"]},
    ),
    _tool(
        "sequence.compute.prefix_lcms",
        "Compute prefix lcms",
        "Compute the lcm of every nonempty prefix.",
        IntegerSequenceListResult,
        prefix_lcms,
        "sequence",
        "divisibility",
        example_name="prefix_lcms",
        example_description="Compute prefix lcms of 2, 3, and 4.",
        example_input={"values": ["2", "3", "4"]},
    ),
    _tool(
        "sequence.compute.second_differences",
        "Compute second differences",
        "Compute adjacent differences of the first-difference sequence.",
        IntegerSequenceListResult,
        second_differences,
        "sequence",
        "transform",
        example_name="second_differences",
        example_description="Compute second differences of consecutive squares.",
        example_input={"values": ["1", "4", "9", "16"]},
    ),
    _tool(
        "sequence.transform.sorted_unique",
        "Sort and deduplicate sequence",
        "Return the strictly increasing values occurring in a finite integer sequence.",
        IntegerSequenceListResult,
        sorted_unique,
        "sequence",
        "transform",
        example_name="sorted_unique",
        example_description="Sort and deduplicate a sequence.",
        example_input={"values": ["3", "1", "3", "2"]},
    ),
    _tool(
        "sequence.transform.sort",
        "Sort integer sequence",
        "Return a nondecreasing ordering retaining multiplicities.",
        IntegerSequenceListResult,
        sort_sequence,
        "sequence",
        "transform",
        example_name="sort",
        example_description="Sort an integer sequence.",
        example_input={"values": ["3", "1", "2"]},
    ),
    _tool(
        "sequence.transform.reverse",
        "Reverse integer sequence",
        "Return the finite integer sequence in reverse order.",
        IntegerSequenceListResult,
        reverse_sequence,
        "sequence",
        "transform",
        example_name="reverse",
        example_description="Reverse an integer sequence.",
        example_input=_SEQ,
    ),
    _tool(
        "sequence.transform.parities",
        "Compute parity sequence",
        "Return 0 for even and 1 for odd at each position.",
        IntegerSequenceListResult,
        parities,
        "sequence",
        "transform",
        example_name="parities",
        example_description="Compute parities of 1, 2, and 3.",
        example_input=_SEQ,
    ),
    _tool(
        "sequence.transform.signs",
        "Compute sign sequence",
        "Return -1, 0, or 1 for each sequence value.",
        IntegerSequenceListResult,
        signs,
        "sequence",
        "transform",
        example_name="signs",
        example_description="Compute signs of negative, zero, and positive values.",
        example_input={"values": ["-2", "0", "5"]},
    ),
    _tool(
        "sequence.decide.arithmetic",
        "Decide arithmetic progression",
        "Decide whether consecutive terms have one common difference.",
        IntegerSequenceBooleanResult,
        decide_arithmetic,
        "sequence",
        "predicate",
        example_name="arithmetic",
        example_description="Recognize an arithmetic sequence.",
        example_input={"values": ["3", "6", "9", "12"]},
    ),
    _tool(
        "sequence.decide.geometric",
        "Decide geometric progression",
        "Decide whether a finite integer sequence has a consistent rational ratio.",
        IntegerSequenceBooleanResult,
        decide_geometric,
        "sequence",
        "predicate",
        example_name="geometric",
        example_description="Recognize powers of two.",
        example_input={"values": ["2", "4", "8", "16"]},
    ),
    _tool(
        "sequence.decide.nondecreasing",
        "Decide nondecreasing order",
        "Decide whether every term is at least its predecessor.",
        IntegerSequenceBooleanResult,
        decide_nondecreasing,
        "sequence",
        "predicate",
        example_name="nondecreasing",
        example_description="Check nondecreasing order.",
        example_input={"values": ["1", "1", "3", "5"]},
    ),
    _tool(
        "sequence.decide.strictly_increasing",
        "Decide strict increase",
        "Decide whether every term is greater than its predecessor.",
        IntegerSequenceBooleanResult,
        decide_strictly_increasing,
        "sequence",
        "predicate",
        example_name="strictly_increasing",
        example_description="Check strict increase.",
        example_input={"values": ["1", "2", "4", "7"]},
    ),
    _tool(
        "sequence.compute.frequencies",
        "Compute value frequencies",
        "Count each distinct value in a finite integer sequence.",
        IntegerSequenceFrequenciesResult,
        frequencies,
        "sequence",
        "counting",
        example_name="frequencies",
        example_description="Count frequencies in 1, 2, and 1.",
        example_input={"values": ["1", "2", "1"]},
    ),
    _tool(
        "sequence.compute.zero_indices",
        "Locate zero terms",
        "Return zero-based indices whose sequence value is zero.",
        IntegerSequenceIndexListResult,
        zero_indices,
        "sequence",
        "search",
        example_name="zero_indices",
        example_description="Locate zero terms in 2, 0, and 3.",
        example_input={"values": ["2", "0", "3"]},
    ),
)

__all__ = ["TOOLS"]
