"""Finitely generated abelian group operation declarations."""

from typing import Any

from jacobian.catalog.models import MathTool, OperationExample
from jacobian.math.groups.abelian._models import (
    CyclicFactorPresentation,
    ElementEqualRequest,
    ElementEqualResult,
    ElementOrderRequest,
    ElementOrderResult,
    ElementReduceRequest,
    ElementReduceResult,
    PresentationNormalizeRequest,
    PresentationNormalizeResult,
    QuotientRequest,
    QuotientResult,
    SubgroupGeneratedRequest,
    SubgroupGeneratedResult,
)
from jacobian.math.groups.abelian.operations import (
    element_order,
    elements_equal,
    generated_subgroup,
    normalize_presentation,
    quotient_group,
    reduce_element,
)


def _run_presentation_normalize(
    request: PresentationNormalizeRequest,
) -> PresentationNormalizeResult:
    return normalize_presentation(
        CyclicFactorPresentation(invariant_factors=request.invariant_factors)
    )


def _run_element_reduce(request: ElementReduceRequest) -> ElementReduceResult:
    return reduce_element(request.group, request.coordinates)


def _run_element_equal(request: ElementEqualRequest) -> ElementEqualResult:
    return elements_equal(request.group, request.coordinates_a, request.coordinates_b)


def _run_element_order(request: ElementOrderRequest) -> ElementOrderResult:
    return element_order(request.group, request.coordinates)


def _run_subgroup_generated(
    request: SubgroupGeneratedRequest,
) -> SubgroupGeneratedResult:
    return generated_subgroup(request.group, request.generators)


def _run_quotient(request: QuotientRequest) -> QuotientResult:
    return quotient_group(request.group, request.subgroup_generators)


TOOLS: tuple[MathTool[Any, Any], ...] = (
    MathTool(
        operation_id="abelian_group.presentation.normalize",
        title="Normalize a finitely generated abelian group presentation",
        description="Compute the Smith normal form of a finite cyclic-factor presentation, "
        "returning canonical invariant factors, group order, and rank. Input "
        "factors need not already be in invariant-factor order.",
        request_type=PresentationNormalizeRequest,
        result_type=PresentationNormalizeResult,
        run=_run_presentation_normalize,
        tags=("abelian-group", "smith-normal-form", "exact"),
        examples=(
            OperationExample(
                name="z6_z4",
                description="Normalize Z/6 x Z/4.",
                input={"invariant_factors": [6, 4]},
            ),
        ),
    ),
    MathTool(
        operation_id="abelian_group.element.reduce",
        title="Reduce an element to canonical form",
        description="Reduce group element coordinates modulo the invariant factors.",
        request_type=ElementReduceRequest,
        result_type=ElementReduceResult,
        run=_run_element_reduce,
        tags=("abelian-group", "element", "exact"),
        examples=(
            OperationExample(
                name="reduce_z6",
                description="Reduce 7 mod 6 in Z/6.",
                input={"group": {"invariant_factors": [6]}, "coordinates": [7]},
            ),
        ),
    ),
    MathTool(
        operation_id="abelian_group.element.equal.decide",
        title="Decide equality of two group elements",
        description="Check whether two elements are equal by reducing both modulo the "
        "invariant factors and comparing.",
        request_type=ElementEqualRequest,
        result_type=ElementEqualResult,
        run=_run_element_equal,
        tags=("abelian-group", "element", "exact"),
        examples=(
            OperationExample(
                name="equal_elements",
                description="Check 1 and 7 are equal in Z/6.",
                input={
                    "group": {"invariant_factors": [6]},
                    "coordinates_a": [1],
                    "coordinates_b": [7],
                },
            ),
        ),
    ),
    MathTool(
        operation_id="abelian_group.element.order.compute",
        title="Compute the order of a group element",
        description="Compute the order of a group element as the lcm of component orders.",
        request_type=ElementOrderRequest,
        result_type=ElementOrderResult,
        run=_run_element_order,
        tags=("abelian-group", "element", "exact"),
        examples=(
            OperationExample(
                name="order_in_z6",
                description="Order of 2 in Z/6.",
                input={"group": {"invariant_factors": [6]}, "coordinates": [2]},
            ),
        ),
    ),
    MathTool(
        operation_id="abelian_group.subgroup.generated.compute",
        title="Compute the index of a generated subgroup",
        description="Compute the index of the subgroup generated by the given elements "
        "via coset enumeration.",
        request_type=SubgroupGeneratedRequest,
        result_type=SubgroupGeneratedResult,
        run=_run_subgroup_generated,
        tags=("abelian-group", "subgroup", "exact"),
        examples=(
            OperationExample(
                name="subgroup_z6",
                description="Index of <2> in Z/6.",
                input={
                    "group": {"invariant_factors": [6]},
                    "generators": [[2]],
                },
            ),
        ),
    ),
    MathTool(
        operation_id="abelian_group.quotient.compute",
        title="Compute the quotient group G/H",
        description="Compute the quotient group G/H via Smith normal form of the "
        "presentation matrix.",
        request_type=QuotientRequest,
        result_type=QuotientResult,
        run=_run_quotient,
        tags=("abelian-group", "quotient", "exact"),
        examples=(
            OperationExample(
                name="quotient_z6_by_2z",
                description="Quotient Z/6 / <2>.",
                input={
                    "group": {"invariant_factors": [6]},
                    "subgroup_generators": [[2]],
                },
            ),
        ),
    ),
)

__all__ = ["TOOLS"]
