"""Finitely generated abelian group operation declarations."""

from collections.abc import Callable
from typing import Any

from jacobian._models import StrictModel
from jacobian.catalog._examples import example
from jacobian.catalog.models import MathTool, OperationExample
from jacobian.math.groups.abelian._models import (
    ElementEqualRequest,
    ElementEqualResult,
    ElementOrderRequest,
    ElementOrderResult,
    ElementReduceRequest,
    ElementReduceResult,
    PresentationNormalizeRequest,
    PresentationNormalizeResult,
    QuotientRequest,
    QuotientResult,
    SubgroupGeneratedRequest,
    SubgroupGeneratedResult,
)
from jacobian.math.groups.abelian._operations import (
    compute_element_equal,
    compute_element_order,
    compute_element_reduce,
    compute_presentation_normalize,
    compute_quotient,
    compute_subgroup_generated,
)


def _op[RequestT: StrictModel, ResultT: StrictModel](
    operation_id: str,
    title: str,
    description: str,
    request_model: type[RequestT],
    result_model: type[ResultT],
    operation: Callable[[RequestT], ResultT],
    *tags: str,
    examples: tuple[OperationExample, ...] = (),
) -> MathTool[RequestT, ResultT]:
    return MathTool(
        operation_id=operation_id,
        title=title,
        description=description,
        request_type=request_model,
        result_type=result_model,
        run=operation,
        tags=tags,
        examples=examples,
    )


TOOLS: tuple[MathTool[Any, Any], ...] = (
    _op(
        "abelian_group.presentation.normalize",
        "Normalize a finitely generated abelian group presentation",
        "Compute the Smith normal form of a finite cyclic-factor presentation, "
        "returning canonical invariant factors, group order, and rank. Input "
        "factors need not already be in invariant-factor order.",
        PresentationNormalizeRequest,
        PresentationNormalizeResult,
        compute_presentation_normalize,
        "abelian-group",
        "smith-normal-form",
        "exact",
        examples=(
            example(
                "z6_z4",
                "Normalize Z/6 x Z/4.",
                {"invariant_factors": [6, 4]},
            ),
        ),
    ),
    _op(
        "abelian_group.element.reduce",
        "Reduce an element to canonical form",
        "Reduce group element coordinates modulo the invariant factors.",
        ElementReduceRequest,
        ElementReduceResult,
        compute_element_reduce,
        "abelian-group",
        "element",
        "exact",
        examples=(
            example(
                "reduce_z6",
                "Reduce 7 mod 6 in Z/6.",
                {"invariant_factors": [6], "coordinates": [7]},
            ),
        ),
    ),
    _op(
        "abelian_group.element.equal.decide",
        "Decide equality of two group elements",
        "Check whether two elements are equal by reducing both modulo the "
        "invariant factors and comparing.",
        ElementEqualRequest,
        ElementEqualResult,
        compute_element_equal,
        "abelian-group",
        "element",
        "exact",
        examples=(
            example(
                "equal_elements",
                "Check 1 and 7 are equal in Z/6.",
                {
                    "invariant_factors": [6],
                    "coordinates_a": [1],
                    "coordinates_b": [7],
                },
            ),
        ),
    ),
    _op(
        "abelian_group.element.order.compute",
        "Compute the order of a group element",
        "Compute the order of a group element as the lcm of component orders.",
        ElementOrderRequest,
        ElementOrderResult,
        compute_element_order,
        "abelian-group",
        "element",
        "exact",
        examples=(
            example(
                "order_in_z6",
                "Order of 2 in Z/6.",
                {"invariant_factors": [6], "coordinates": [2]},
            ),
        ),
    ),
    _op(
        "abelian_group.subgroup.generated.compute",
        "Compute the index of a generated subgroup",
        "Compute the index of the subgroup generated by the given elements "
        "via coset enumeration.",
        SubgroupGeneratedRequest,
        SubgroupGeneratedResult,
        compute_subgroup_generated,
        "abelian-group",
        "subgroup",
        "exact",
        examples=(
            example(
                "subgroup_z6",
                "Index of <2> in Z/6.",
                {
                    "invariant_factors": [6],
                    "generators": [[2]],
                },
            ),
        ),
    ),
    _op(
        "abelian_group.quotient.compute",
        "Compute the quotient group G/H",
        "Compute the quotient group G/H via Smith normal form of the "
        "presentation matrix.",
        QuotientRequest,
        QuotientResult,
        compute_quotient,
        "abelian-group",
        "quotient",
        "exact",
        examples=(
            example(
                "quotient_z6_by_2z",
                "Quotient Z/6 / <2>.",
                {
                    "invariant_factors": [6],
                    "subgroup_generators": [[2]],
                },
            ),
        ),
    ),
)

__all__ = ["TOOLS"]
