"""Exact native operations for finitely generated abelian groups."""

from __future__ import annotations

from math import gcd, lcm

from jacobian.math.groups.abelian._models import (
    ElementEqualResult,
    ElementOrderResult,
    ElementReduceResult,
    PresentationNormalizeResult,
    QuotientResult,
    SubgroupGeneratedResult,
)


def normalize_presentation(
    invariant_factors: tuple[int, ...],
) -> PresentationNormalizeResult:
    from sympy import Matrix, diag
    from sympy.matrices.normalforms import smith_normal_form

    matrix = Matrix(diag(*invariant_factors))
    smith = smith_normal_form(matrix, domain=None)
    factors = tuple(int(smith[i, i]) for i in range(min(smith.rows, smith.cols)))
    cleaned = tuple(factor for factor in factors if factor > 1)
    order = 1
    for factor in cleaned:
        order *= factor
    return PresentationNormalizeResult(
        invariant_factors=cleaned,
        order=order,
        rank=0,
    )


def reduce_element(
    invariant_factors: tuple[int, ...], coordinates: tuple[int, ...]
) -> ElementReduceResult:
    reduced = tuple(
        coordinate % factor
        for coordinate, factor in zip(coordinates, invariant_factors, strict=True)
    )
    return ElementReduceResult(reduced=reduced)


def elements_equal(
    invariant_factors: tuple[int, ...],
    coordinates_a: tuple[int, ...],
    coordinates_b: tuple[int, ...],
) -> ElementEqualResult:
    reduced_a = tuple(
        coordinate % factor
        for coordinate, factor in zip(coordinates_a, invariant_factors, strict=True)
    )
    reduced_b = tuple(
        coordinate % factor
        for coordinate, factor in zip(coordinates_b, invariant_factors, strict=True)
    )
    return ElementEqualResult(equal=reduced_a == reduced_b)


def element_order(
    invariant_factors: tuple[int, ...], coordinates: tuple[int, ...]
) -> ElementOrderResult:
    reduced = [
        coordinate % factor
        for coordinate, factor in zip(coordinates, invariant_factors, strict=True)
    ]
    order = 1
    for coordinate, factor in zip(reduced, invariant_factors, strict=True):
        if coordinate != 0:
            order = lcm(order, factor // gcd(coordinate, factor))
    return ElementOrderResult(order=order)


def _smith_diagonal(augmented_rows: list[list[int]]) -> list[int]:
    """Compute diagonal entries of the exact integer Smith normal form."""
    from sympy import Matrix
    from sympy.matrices.normalforms import smith_normal_form

    smith = smith_normal_form(Matrix(augmented_rows), domain=None)
    return [abs(int(smith[i, i])) for i in range(min(smith.rows, smith.cols))]


def generated_subgroup(
    invariant_factors: tuple[int, ...], generators: tuple[tuple[int, ...], ...]
) -> SubgroupGeneratedResult:
    """Compute the index of a subgroup generated by given elements."""
    factors = invariant_factors
    rows = [[0] * len(factors) for _ in factors]
    for index, factor in enumerate(factors):
        rows[index][index] = factor
    for generator in generators:
        for index, coordinate in enumerate(generator):
            rows[index].append(coordinate)
    diagonal = _smith_diagonal(rows)
    index = 1
    for factor in diagonal:
        if factor > 1:
            index *= factor
    return SubgroupGeneratedResult(index=index)


def quotient_group(
    invariant_factors: tuple[int, ...],
    subgroup_generators: tuple[tuple[int, ...], ...],
) -> QuotientResult:
    """Compute the quotient group via Smith normal form."""
    factors = invariant_factors
    rows = [[0] * len(factors) for _ in factors]
    for index, factor in enumerate(factors):
        rows[index][index] = factor
    for generator in subgroup_generators:
        for index, coordinate in enumerate(generator):
            rows[index].append(coordinate)
    diagonal = _smith_diagonal(rows)
    quotient_factors = tuple(factor for factor in diagonal if factor > 1)
    order = 1
    for factor in quotient_factors:
        order *= factor
    return QuotientResult(
        quotient_invariant_factors=quotient_factors,
        quotient_order=order,
    )


__all__ = [
    "element_order",
    "elements_equal",
    "generated_subgroup",
    "normalize_presentation",
    "quotient_group",
    "reduce_element",
]
