"""Exact native operations for finitely generated abelian groups."""

from __future__ import annotations

from math import gcd, lcm

from jacobian.math.groups.abelian._models import (
    AbelianPresentation,
    ElementEqualRequest,
    ElementEqualResult,
    ElementOrderRequest,
    ElementOrderResult,
    ElementReduceResult,
    PresentationNormalizeResult,
    QuotientRequest,
    QuotientResult,
    SubgroupGeneratedRequest,
    SubgroupGeneratedResult,
)


def normalize_presentation(
    invariant_factors: tuple[int, ...],
) -> PresentationNormalizeResult:
    from sympy import Matrix, diag
    from sympy.matrices.normalforms import smith_normal_form

    matrix = Matrix(diag(*invariant_factors))
    smith = smith_normal_form(matrix, domain=None)
    factors = tuple(int(smith[i, i]) for i in range(min(smith.rows, smith.cols)))
    cleaned = tuple(factor for factor in factors if factor > 1)
    return PresentationNormalizeResult(
        presentation=AbelianPresentation(invariant_factors=cleaned),
    )


def reduce_element(
    invariant_factors: tuple[int, ...], coordinates: tuple[int, ...]
) -> ElementReduceResult:
    reduced = tuple(
        coordinate % factor
        for coordinate, factor in zip(coordinates, invariant_factors, strict=True)
    )
    return ElementReduceResult(reduced=reduced)


def elements_equal(
    invariant_factors: tuple[int, ...],
    coordinates_a: tuple[int, ...],
    coordinates_b: tuple[int, ...],
) -> ElementEqualResult:
    reduced_a = tuple(
        coordinate % factor
        for coordinate, factor in zip(coordinates_a, invariant_factors, strict=True)
    )
    reduced_b = tuple(
        coordinate % factor
        for coordinate, factor in zip(coordinates_b, invariant_factors, strict=True)
    )
    return ElementEqualResult(
        request=ElementEqualRequest(
            invariant_factors=invariant_factors,
            coordinates_a=coordinates_a,
            coordinates_b=coordinates_b,
        ),
        equal=reduced_a == reduced_b,
    )


def verify_elements_equal(claim: ElementEqualResult) -> bool:
    """Check the equality relation asserted by a serialized element claim."""

    return (
        elements_equal(
            claim.request.invariant_factors,
            claim.request.coordinates_a,
            claim.request.coordinates_b,
        ).equal
        is claim.equal
    )


def element_order(
    invariant_factors: tuple[int, ...], coordinates: tuple[int, ...]
) -> ElementOrderResult:
    reduced = [
        coordinate % factor
        for coordinate, factor in zip(coordinates, invariant_factors, strict=True)
    ]
    order = 1
    for coordinate, factor in zip(reduced, invariant_factors, strict=True):
        if coordinate != 0:
            order = lcm(order, factor // gcd(coordinate, factor))
    return ElementOrderResult(
        request=ElementOrderRequest(
            invariant_factors=invariant_factors,
            coordinates=coordinates,
        ),
        order=order,
    )


def verify_element_order(claim: ElementOrderResult) -> bool:
    """Check the order relation asserted by a serialized element claim."""

    return (
        element_order(
            claim.request.invariant_factors,
            claim.request.coordinates,
        ).order
        == claim.order
    )


def _smith_diagonal(augmented_rows: list[list[int]]) -> list[int]:
    """Compute diagonal entries of the exact integer Smith normal form."""
    from sympy import Matrix
    from sympy.matrices.normalforms import smith_normal_form

    smith = smith_normal_form(Matrix(augmented_rows), domain=None)
    return [abs(int(smith[i, i])) for i in range(min(smith.rows, smith.cols))]


def generated_subgroup(
    invariant_factors: tuple[int, ...], generators: tuple[tuple[int, ...], ...]
) -> SubgroupGeneratedResult:
    """Compute the index of a subgroup generated by given elements."""
    factors = invariant_factors
    rows = [[0] * len(factors) for _ in factors]
    for index, factor in enumerate(factors):
        rows[index][index] = factor
    for generator in generators:
        for index, coordinate in enumerate(generator):
            rows[index].append(coordinate)
    diagonal = _smith_diagonal(rows)
    index = 1
    for factor in diagonal:
        if factor > 1:
            index *= factor
    return SubgroupGeneratedResult(
        request=SubgroupGeneratedRequest(
            invariant_factors=invariant_factors, generators=generators
        ),
        index=index,
    )


def quotient_group(
    invariant_factors: tuple[int, ...],
    subgroup_generators: tuple[tuple[int, ...], ...],
) -> QuotientResult:
    """Compute the quotient group via Smith normal form."""
    factors = invariant_factors
    rows = [[0] * len(factors) for _ in factors]
    for index, factor in enumerate(factors):
        rows[index][index] = factor
    for generator in subgroup_generators:
        for index, coordinate in enumerate(generator):
            rows[index].append(coordinate)
    diagonal = _smith_diagonal(rows)
    quotient_factors = tuple(factor for factor in diagonal if factor > 1)
    order = 1
    for factor in quotient_factors:
        order *= factor
    return QuotientResult(
        request=QuotientRequest(
            invariant_factors=invariant_factors,
            subgroup_generators=subgroup_generators,
        ),
        quotient_invariant_factors=quotient_factors,
        quotient_order=order,
    )


def verify_generated_subgroup(claim: SubgroupGeneratedResult) -> bool:
    """Check the index relation asserted by a serialized subgroup claim."""

    return (
        generated_subgroup(
            claim.request.invariant_factors, claim.request.generators
        ).index
        == claim.index
    )


def verify_quotient_group(claim: QuotientResult) -> bool:
    """Check the quotient presentation asserted by a serialized claim."""

    expected = quotient_group(
        claim.request.invariant_factors, claim.request.subgroup_generators
    )
    return (
        expected.quotient_invariant_factors == claim.quotient_invariant_factors
        and expected.quotient_order == claim.quotient_order
    )


__all__ = [
    "element_order",
    "elements_equal",
    "generated_subgroup",
    "normalize_presentation",
    "quotient_group",
    "reduce_element",
    "verify_element_order",
    "verify_elements_equal",
    "verify_generated_subgroup",
    "verify_quotient_group",
]
